In [22]:
import pandas as pd

In [23]:
df_cognitive_complexity = pd.read_csv('elements separated/cognitive_complexity.csv')
df_creativity = pd.read_csv('elements separated/creativity.csv')
df_data_structure = pd.read_csv('elements separated/data_structure.csv')
df_decision_accountability = pd.read_csv('elements separated/decision_accountability.csv')
df_physical_requirements = pd.read_csv('elements separated/physical_requirements.csv')
df_routine_structure = pd.read_csv('elements separated/routine_structure.csv')
df_social_interactions = pd.read_csv('elements separated/social_interactions.csv')

In [24]:
dfs = [
    df_cognitive_complexity,
    df_creativity,
    df_data_structure,
    df_decision_accountability,
    df_physical_requirements,
    df_routine_structure,
    df_social_interactions
]

In [25]:
import pandas as pd
import numpy as np

ID_COLS = ["O*NET-SOC Code", "Title"]

# (optional but recommended) give your dfs names so the outputs are nicely labeled
df_names = [
    "cognitive_complexity",
    "creativity",
    "data_structure",
    "decision_accountability",
    "physical_requirements",
    "routine_structure",
    "social_interactions",
]

avg_dfs = {}   # name -> dataframe of averages
avg_list = []  # same outputs but as a list (if you prefer)

for name, df in zip(df_names, dfs):
    # safety: verify required cols exist
    missing = [c for c in ID_COLS if c not in df.columns]
    if missing:
        raise KeyError(f"{name} is missing required columns: {missing}")

    # choose columns to average: numeric columns excluding ID_COLS
    numeric_cols = df.drop(columns=ID_COLS, errors="ignore").select_dtypes(include="number").columns

    if len(numeric_cols) == 0:
        raise ValueError(f"{name} has no numeric columns to average (besides {ID_COLS}).")

    out = df[ID_COLS].copy()
    out[f"{name}_avg"] = df[numeric_cols].mean(axis=1, skipna=True)

    avg_dfs[name] = out
    avg_list.append(out)

for name, out in avg_dfs.items():
    globals()[f"df_{name}_avg"] = out

# Example: access one
avg_dfs["creativity"].head()

  O*NET-SOC Code                                Title  creativity_avg
0     11-1011.00                     Chief Executives        2.456682
1     11-1011.03        Chief Sustainability Officers        2.497004
2     11-1021.00      General and Operations Managers        2.003393
3     11-2011.00  Advertising and Promotions Managers        2.297464
4     11-2021.00                   Marketing Managers        2.261386

In [34]:
avg_dfs = [
    df_cognitive_complexity_avg,
    df_creativity_avg,
    df_data_structure_avg,
    df_decision_accountability_avg,
    df_physical_requirements_avg,
    df_routine_structure_avg,
    df_social_interactions_avg
]

In [35]:
import pandas as pd
from functools import reduce

# Define the columns to merge on
merge_cols = ['O*NET-SOC Code', 'Title']

# Use reduce to merge all DataFrames sequentially
merged_df = reduce(lambda left, right: pd.merge(left, right, on=merge_cols, how='inner'), avg_dfs)
merged_df

,O*NET-SOC Code,Title,cognitive_complexity_avg,creativity_avg,data_structure_avg,decision_accountability_avg,physical_requirements_avg,routine_structure_avg,social_interactions_avg
0,11-1011.00,Chief Executives,2.484455,2.456682,2.842733,4.194010,1.481282,2.732,3.475114
1,11-1011.03,Chief Sustainability Officers,2.205002,2.497004,2.935123,3.280978,1.474703,2.008,3.102473
2,11-1021.00,General and Operations Managers,2.120659,2.003393,2.639833,3.978757,1.586159,2.622,3.007441
3,11-2011.00,Advertising and Promotions Managers,1.998732,2.297464,2.481961,3.254776,1.447422,2.522,2.837929
4,11-2021.00,Marketing Managers,2.104659,2.261386,2.494049,3.291586,1.397116,2.568,3.051097
...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,2.012125,1.621000,2.500994,4.081876,2.616804,3.274,2.310364
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",1.999092,1.635725,2.218989,3.826473,2.516200,3.152,2.205520
891,53-7073.00,Wellhead Pumpers,1.875128,1.495757,2.358553,3.672010,2.537516,2.826,2.239722
892,53-7081.00,Refuse and Recyclable Material Collectors,1.521986,1.144950,1.284449,3.003655,2.392783,3.316,1.893437
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.010257,1.646918,2.448500,4.159657,2.894719,3.630,2.479141

Very dumb version for average. Not signed to account for differences in types.

In [39]:
merged_df['weighted_average_GPT_v1_non_overlap'] = (
    merged_df['cognitive_complexity_avg'] * 0.15 +
    merged_df['creativity_avg'] * 0.15 +
    merged_df['data_structure_avg'] * 0.10 +
    merged_df['decision_accountability_avg'] * 0.10 +
    merged_df['physical_requirements_avg'] * 0.15 +
    merged_df['routine_structure_avg'] * 0.20 +
    merged_df['social_interactions_avg'] * 0.15
)

merged_df

,O*NET-SOC Code,Title,cognitive_complexity_avg,creativity_avg,data_structure_avg,decision_accountability_avg,physical_requirements_avg,routine_structure_avg,social_interactions_avg,weighted_average_GPT_v1_non_overlap
0,11-1011.00,Chief Executives,2.484455,2.456682,2.842733,4.194010,1.481282,2.732,3.475114,2.734704
1,11-1011.03,Chief Sustainability Officers,2.205002,2.497004,2.935123,3.280978,1.474703,2.008,3.102473,2.415087
2,11-1021.00,General and Operations Managers,2.120659,2.003393,2.639833,3.978757,1.586159,2.622,3.007441,2.493907
3,11-2011.00,Advertising and Promotions Managers,1.998732,2.297464,2.481961,3.254776,1.447422,2.522,2.837929,2.365306
4,11-2021.00,Marketing Managers,2.104659,2.261386,2.494049,3.291586,1.397116,2.568,3.051097,2.414302
...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,2.012125,1.621000,2.500994,4.081876,2.616804,3.274,2.310364,2.597131
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",1.999092,1.635725,2.218989,3.826473,2.516200,3.152,2.205520,2.488427
891,53-7073.00,Wellhead Pumpers,1.875128,1.495757,2.358553,3.672010,2.537516,2.826,2.239722,2.390475
892,53-7081.00,Refuse and Recyclable Material Collectors,1.521986,1.144950,1.284449,3.003655,2.392783,3.316,1.893437,2.134984
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.010257,1.646918,2.448500,4.159657,2.894719,3.630,2.479141,2.741471

In [ ]:
Routine - 20%

Cognitive complexity - 15%

Physical requirements - 15%

Social interactions - 15%

Creativity - 15%

Decision accountability 10%

Data structure 10%

In [28]:
df_cognitive_complexity_avg

,O*NET-SOC Code,Title,cognitive_complexity_avg
0,11-1011.00,Chief Executives,2.484455
1,11-1011.03,Chief Sustainability Officers,2.205002
2,11-1021.00,General and Operations Managers,2.120659
3,11-2011.00,Advertising and Promotions Managers,1.998732
4,11-2021.00,Marketing Managers,2.104659
...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,2.012125
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",1.999092
891,53-7073.00,Wellhead Pumpers,1.875128
892,53-7081.00,Refuse and Recyclable Material Collectors,1.521986
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.010257

In [30]:
df_creativity_avg

,O*NET-SOC Code,Title,creativity_avg
0,11-1011.00,Chief Executives,2.456682
1,11-1011.03,Chief Sustainability Officers,2.497004
2,11-1021.00,General and Operations Managers,2.003393
3,11-2011.00,Advertising and Promotions Managers,2.297464
4,11-2021.00,Marketing Managers,2.261386
...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,1.621000
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",1.635725
891,53-7073.00,Wellhead Pumpers,1.495757
892,53-7081.00,Refuse and Recyclable Material Collectors,1.144950
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.646918