In [20]:
import pandas as pd
# df_technology_skills = pd.read_csv('ONET data/Technology Skills.csv')
# df_tools_used = pd.read_csv('ONET data/Tools Used.csv')
# df_task_statements = pd.read_csv('ONET data/Task Statements.csv')
# df_skills = pd.read_csv('ONET data/Skills.csv')
# df_abilities = pd.read_csv('ONET data/Abilities.csv')
# df_occupation_data = pd.read_csv('ONET data/Occupation Data.csv')
# df_work_activities = pd.read_csv('ONET data/Work Activities.csv')
# df_knowledge = pd.read_csv('ONET data/Knowledge.csv')

df_work_context = pd.read_csv('ONET data/Work Context.csv')

In [21]:
df_work_context

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Category,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CX,Context,NaN,3.07,37.0,0.2851,2.4923,3.6486,N,NaN,08/2023,Incumbent
1,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CXP,Context (Categories 1-5),1.0,0.13,37.0,0.1370,0.0160,1.0770,N,NaN,08/2023,Incumbent
2,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CXP,Context (Categories 1-5),2.0,39.49,37.0,11.0101,20.4073,62.4299,N,NaN,08/2023,Incumbent
3,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CXP,Context (Categories 1-5),3.0,33.07,37.0,7.1359,20.4456,48.7245,N,NaN,08/2023,Incumbent
4,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CXP,Context (Categories 1-5),4.0,7.79,37.0,4.3613,2.4093,22.4457,N,NaN,08/2023,Incumbent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297671,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.4,Work Schedules,CTP,Context (Categories 1-3),3.0,0.89,32.0,0.9750,0.0947,7.8674,N,NaN,08/2019,Incumbent
297672,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.8,Duration of Typical Work Week,CT,Context,NaN,2.82,32.0,0.0983,2.6238,3.0000,N,NaN,08/2019,Incumbent
297673,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.8,Duration of Typical Work Week,CTP,Context (Categories 1-3),1.0,0.00,32.0,0.0000,NaN,NaN,N,NaN,08/2019,Incumbent
297674,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.8,Duration of Typical Work Week,CTP,Context (Categories 1-3),2.0,17.56,32.0,9.8350,5.0617,45.9881,N,NaN,08/2019,Incumbent
297675,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.8,Duration of Typical Work Week,CTP,Context (Categories 1-3),3.0,82.44,32.0,9.8350,54.0119,94.9383,N,NaN,08/2019,Incumbent

# Pivoting - A little different this time

In [3]:
df_cx = df_work_context[df_work_context["Scale ID"] == "CX"].copy()

In [6]:
df_cx_wide = df_cx.pivot_table(
    index=["O*NET-SOC Code", "Title"],
    columns="Element Name",
    values="Data Value"
).reset_index()

In [7]:
df_cx_wide

Element Name,O*NET-SOC Code,Title,Conflict Situations,Consequence of Error,Contact With Others,Coordinate or Lead Others in Accomplishing Work Activities,Deal With External Customers or the Public in General,"Dealing With Unpleasant, Angry, or Discourteous People",Dealing with Violent or Physically Aggressive People,Degree of Automation,...,Spend Time Standing,"Spend Time Using Your Hands to Handle, Control, or Feel Objects, Tools, or Controls",Spend Time Walking or Running,Telephone Conversations,Time Pressure,"Wear Common Protective or Safety Equipment such as Safety Shoes, Glasses, Gloves, Hearing Protection, Hard Hats, or Life Jackets","Wear Specialized Protective or Safety Equipment such as Breathing Apparatus, Safety Harness, Full Protection Suits, or Radiation Protection",Work Outcomes and Results of Other Workers,Work With or Contribute to a Work Group or Team,Written Letters and Memos
0,11-1011.00,Chief Executives,3.86,3.02,4.58,4.29,4.33,3.24,1.46,2.23,...,2.13,2.17,1.72,4.92,4.16,1.77,1.21,4.70,4.36,4.14
1,11-1011.03,Chief Sustainability Officers,3.04,2.15,4.41,4.22,3.85,2.41,1.19,1.56,...,2.31,1.73,1.89,4.74,3.48,1.89,1.37,3.85,4.78,3.44
2,11-1021.00,General and Operations Managers,3.35,2.52,4.63,4.48,4.49,3.24,1.62,2.31,...,2.90,2.42,2.53,4.76,4.08,3.06,1.18,4.33,4.62,4.01
3,11-2011.00,Advertising and Promotions Managers,3.15,2.19,4.68,4.11,4.19,2.92,1.14,2.01,...,2.11,2.07,1.97,4.80,4.40,1.24,1.00,3.80,4.47,3.78
4,11-2021.00,Marketing Managers,3.18,2.76,4.61,4.32,4.25,2.74,1.16,2.10,...,2.09,2.31,1.95,4.92,4.21,1.30,1.04,4.04,4.67,3.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,2.59,4.41,4.07,3.42,2.36,2.50,1.17,2.77,...,3.00,3.65,3.10,4.76,3.76,5.00,2.33,3.61,4.51,2.73
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",1.92,3.59,4.25,3.11,2.90,2.21,1.15,2.11,...,3.44,4.11,2.33,4.48,3.31,4.99,1.55,3.03,3.85,2.38
891,53-7073.00,Wellhead Pumpers,2.62,3.67,4.12,3.13,3.43,2.52,1.38,2.00,...,2.95,3.38,2.59,4.95,3.52,5.00,1.59,3.24,3.81,3.20
892,53-7081.00,Refuse and Recyclable Material Collectors,2.44,3.17,3.61,2.56,2.78,2.91,1.34,2.33,...,3.09,4.15,2.66,2.80,3.74,4.99,1.42,2.21,2.93,1.62
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",3.71,4.74,4.47,4.07,3.05,2.82,1.30,1.87,...,3.62,4.31,3.49,4.39,4.47,4.94,4.18,3.67,4.61,3.09

In [8]:
df_cx_wide.to_csv('transformed data/Work Context Frequency Weighted Average.csv', index=False)

# Z Score

In [12]:
df_z = df_cx_wide.copy()

# Identify numeric skill columns
skill_cols = df_cx_wide.select_dtypes(include="number").columns


for col in skill_cols:
    df_z[col] = (
        (df_cx_wide[col] - df_cx_wide[col].mean()) /
        df_cx_wide[col].std()
    )

In [13]:
meta_cols = ["O*NET-SOC Code", "Title"]

level_cols = [
    col for col in df_z.columns
    if "Level" in col
]

import_cols = [
    col for col in df_z.columns
    if "Importance" in col
]

In [14]:
df_z

Element Name,O*NET-SOC Code,Title,Conflict Situations,Consequence of Error,Contact With Others,Coordinate or Lead Others in Accomplishing Work Activities,Deal With External Customers or the Public in General,"Dealing With Unpleasant, Angry, or Discourteous People",Dealing with Violent or Physically Aggressive People,Degree of Automation,...,Spend Time Standing,"Spend Time Using Your Hands to Handle, Control, or Feel Objects, Tools, or Controls",Spend Time Walking or Running,Telephone Conversations,Time Pressure,"Wear Common Protective or Safety Equipment such as Safety Shoes, Glasses, Gloves, Hearing Protection, Hard Hats, or Life Jackets","Wear Specialized Protective or Safety Equipment such as Breathing Apparatus, Safety Harness, Full Protection Suits, or Radiation Protection",Work Outcomes and Results of Other Workers,Work With or Contribute to a Work Group or Team,Written Letters and Memos
0,11-1011.00,Chief Executives,1.750470,-0.007903,0.551497,1.343743,1.098326,0.549113,-0.155049,0.280336,...,-1.032985,-1.126267,-1.031980,0.985142,0.628683,-0.842775,-0.628498,2.256575,0.367305,1.463209
1,11-1011.03,Chief Sustainability Officers,0.277756,-1.172003,0.173400,1.213377,0.539500,-0.743444,-0.659779,-1.005489,...,-0.841496,-1.559699,-0.812804,0.780271,-0.710686,-0.760304,-0.433765,0.882273,1.250645,0.510432
2,11-1021.00,General and Operations Managers,0.834514,-0.676926,0.662703,1.697595,1.284601,0.549113,0.144050,0.433868,...,-0.213837,-0.879999,0.012330,0.803034,0.471110,0.043796,-0.665010,1.658350,0.914135,1.286265
3,11-2011.00,Advertising and Promotions Managers,0.475315,-1.118481,0.773908,1.008516,0.935335,0.050778,-0.753247,-0.141875,...,-1.054262,-1.224774,-0.709662,0.848561,1.101401,-1.207026,-0.884085,0.801432,0.598656,0.973209
4,11-2021.00,Marketing Managers,0.529195,-0.355795,0.618221,1.399615,1.005189,-0.229536,-0.715860,0.030848,...,-1.075539,-0.988357,-0.735448,0.985142,0.727166,-1.165790,-0.835402,1.189470,1.019294,0.619321
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,-0.530441,1.851981,-0.582794,-0.276523,-1.195188,-0.603287,-0.697166,1.316673,...,-0.107454,0.331641,0.747216,0.803034,-0.159181,1.377089,0.734632,0.494235,0.682784,-0.455957
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",-1.733756,0.754784,-0.182456,-0.853859,-0.566509,-1.054903,-0.734553,0.050039,...,0.360631,0.784775,-0.245524,0.484347,-1.045528,1.370216,-0.214691,-0.443524,-0.705321,-0.932346
891,53-7073.00,Wellhead Pumpers,-0.476561,0.861827,-0.471589,-0.816612,0.050528,-0.572141,-0.304598,-0.161066,...,-0.160645,0.065672,0.089687,1.019287,-0.631899,1.377089,-0.166008,-0.103990,-0.789449,0.183765
892,53-7081.00,Refuse and Recyclable Material Collectors,-0.799839,0.192804,-1.605881,-1.878166,-0.706216,0.035205,-0.379373,0.472251,...,-0.011709,0.824178,0.179936,-1.427781,-0.198574,1.370216,-0.372911,-1.769321,-2.640256,-1.966790
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.481071,2.293537,0.306846,0.934021,-0.391876,-0.104952,-0.454148,-0.410555,...,0.552120,0.981790,1.250032,0.381911,1.239277,1.335853,2.986230,0.591245,0.893103,0.034043

In [15]:
df_z.to_csv('transformed data/9-Work Context Freq Avg Z-Scores.csv', index=False)

# Z Score Aggs

In [16]:
df_z_aggs = df_z.copy()



df_z_aggs["z_level_mean"] = df_z_aggs[level_cols].mean(axis=1)
df_z_aggs["z_level_median"] = df_z_aggs[level_cols].median(axis=1)
df_z_aggs["z_level_max"] = df_z_aggs[level_cols].max(axis=1)
df_z_aggs["z_level_min"] = df_z_aggs[level_cols].min(axis=1)
df_z_aggs["z_level_min+max"] = df_z_aggs["z_level_min"] + df_z_aggs["z_level_max"]

df_z_aggs["z_import_mean"] = df_z_aggs[import_cols].mean(axis=1)
df_z_aggs["z_import_median"] = df_z_aggs[import_cols].median(axis=1)
df_z_aggs["z_import_max"] = df_z_aggs[import_cols].max(axis=1)
df_z_aggs["z_import_min"] = df_z_aggs[import_cols].min(axis=1)
df_z_aggs["z_import_min+max"] = df_z_aggs["z_import_min"] + df_z_aggs["z_import_max"]

# Drop level_cols and import_cols as defined earlier
df_z_aggs = df_z_aggs.drop(columns=level_cols)
df_z_aggs = df_z_aggs.drop(columns=import_cols)

In [17]:
df_z_aggs

Element Name,O*NET-SOC Code,Title,Conflict Situations,Consequence of Error,Contact With Others,Coordinate or Lead Others in Accomplishing Work Activities,Deal With External Customers or the Public in General,"Dealing With Unpleasant, Angry, or Discourteous People",Dealing with Violent or Physically Aggressive People,Degree of Automation,...,z_level_mean,z_level_median,z_level_max,z_level_min,z_level_min+max,z_import_mean,z_import_median,z_import_max,z_import_min,z_import_min+max
0,11-1011.00,Chief Executives,1.750470,-0.007903,0.551497,1.343743,1.098326,0.549113,-0.155049,0.280336,...,-0.099660,-0.099660,0.906492,-1.105811,-0.199319,0.409952,0.409952,0.652419,0.167484,0.819903
1,11-1011.03,Chief Sustainability Officers,0.277756,-1.172003,0.173400,1.213377,0.539500,-0.743444,-0.659779,-1.005489,...,0.050332,0.050332,1.129158,-1.028494,0.100664,-1.834727,-1.834727,-1.442476,-2.226977,-3.669453
2,11-1021.00,General and Operations Managers,0.834514,-0.676926,0.662703,1.697595,1.284601,0.549113,0.144050,0.433868,...,-0.425575,-0.425575,0.563928,-1.415078,-0.851150,-0.043179,-0.043179,0.145234,-0.231593,-0.086359
3,11-2011.00,Advertising and Promotions Managers,0.475315,-1.118481,0.773908,1.008516,0.935335,0.050778,-0.753247,-0.141875,...,-0.142000,-0.142000,0.512543,-0.796544,-0.284000,-0.291682,-0.291682,0.277543,-0.860907,-0.583363
4,11-2021.00,Marketing Managers,0.529195,-0.355795,0.618221,1.399615,1.005189,-0.229536,-0.715860,0.030848,...,0.402500,0.402500,1.557364,-0.752363,0.805001,-0.770548,-0.770548,-0.738114,-0.802981,-1.541095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,-0.530441,1.851981,-0.582794,-0.276523,-1.195188,-0.603287,-0.697166,1.316673,...,0.953321,0.953321,1.788047,0.118595,1.906642,0.363137,0.363137,0.735401,-0.009126,0.726274
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",-1.733756,0.754784,-0.182456,-0.853859,-0.566509,-1.054903,-0.734553,0.050039,...,0.101875,0.101875,0.650385,-0.446636,0.203749,0.198825,0.198825,1.134478,-0.736827,0.397651
891,53-7073.00,Wellhead Pumpers,-0.476561,0.861827,-0.471589,-0.816612,0.050528,-0.572141,-0.304598,-0.161066,...,0.809493,0.809493,1.346237,0.272748,1.618985,-0.256787,-0.256787,0.443768,-0.957342,-0.513574
892,53-7081.00,Refuse and Recyclable Material Collectors,-0.799839,0.192804,-1.605881,-1.878166,-0.706216,0.035205,-0.379373,0.472251,...,-0.059162,-0.059162,0.550978,-0.669303,-0.118325,-1.224240,-1.224240,0.228880,-2.677361,-2.448481
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.481071,2.293537,0.306846,0.934021,-0.391876,-0.104952,-0.454148,-0.410555,...,0.767152,0.767152,1.655504,-0.121200,1.534304,1.227778,1.227778,1.825188,0.630368,2.455556

In [18]:
# Define columns to prefix
cols_to_prefix = df_z_aggs.drop(columns=['O*NET-SOC Code', 'Title']).columns
# Apply prefix to these columns
df_z_aggs_pref = df_z_aggs.rename(columns={c: f'FREQUENCY_{c}' for c in cols_to_prefix})
df_z_aggs_pref

Element Name,O*NET-SOC Code,Title,FREQUENCY_Conflict Situations,FREQUENCY_Consequence of Error,FREQUENCY_Contact With Others,FREQUENCY_Coordinate or Lead Others in Accomplishing Work Activities,FREQUENCY_Deal With External Customers or the Public in General,"FREQUENCY_Dealing With Unpleasant, Angry, or Discourteous People",FREQUENCY_Dealing with Violent or Physically Aggressive People,FREQUENCY_Degree of Automation,...,FREQUENCY_z_level_mean,FREQUENCY_z_level_median,FREQUENCY_z_level_max,FREQUENCY_z_level_min,FREQUENCY_z_level_min+max,FREQUENCY_z_import_mean,FREQUENCY_z_import_median,FREQUENCY_z_import_max,FREQUENCY_z_import_min,FREQUENCY_z_import_min+max
0,11-1011.00,Chief Executives,1.750470,-0.007903,0.551497,1.343743,1.098326,0.549113,-0.155049,0.280336,...,-0.099660,-0.099660,0.906492,-1.105811,-0.199319,0.409952,0.409952,0.652419,0.167484,0.819903
1,11-1011.03,Chief Sustainability Officers,0.277756,-1.172003,0.173400,1.213377,0.539500,-0.743444,-0.659779,-1.005489,...,0.050332,0.050332,1.129158,-1.028494,0.100664,-1.834727,-1.834727,-1.442476,-2.226977,-3.669453
2,11-1021.00,General and Operations Managers,0.834514,-0.676926,0.662703,1.697595,1.284601,0.549113,0.144050,0.433868,...,-0.425575,-0.425575,0.563928,-1.415078,-0.851150,-0.043179,-0.043179,0.145234,-0.231593,-0.086359
3,11-2011.00,Advertising and Promotions Managers,0.475315,-1.118481,0.773908,1.008516,0.935335,0.050778,-0.753247,-0.141875,...,-0.142000,-0.142000,0.512543,-0.796544,-0.284000,-0.291682,-0.291682,0.277543,-0.860907,-0.583363
4,11-2021.00,Marketing Managers,0.529195,-0.355795,0.618221,1.399615,1.005189,-0.229536,-0.715860,0.030848,...,0.402500,0.402500,1.557364,-0.752363,0.805001,-0.770548,-0.770548,-0.738114,-0.802981,-1.541095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,-0.530441,1.851981,-0.582794,-0.276523,-1.195188,-0.603287,-0.697166,1.316673,...,0.953321,0.953321,1.788047,0.118595,1.906642,0.363137,0.363137,0.735401,-0.009126,0.726274
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",-1.733756,0.754784,-0.182456,-0.853859,-0.566509,-1.054903,-0.734553,0.050039,...,0.101875,0.101875,0.650385,-0.446636,0.203749,0.198825,0.198825,1.134478,-0.736827,0.397651
891,53-7073.00,Wellhead Pumpers,-0.476561,0.861827,-0.471589,-0.816612,0.050528,-0.572141,-0.304598,-0.161066,...,0.809493,0.809493,1.346237,0.272748,1.618985,-0.256787,-0.256787,0.443768,-0.957342,-0.513574
892,53-7081.00,Refuse and Recyclable Material Collectors,-0.799839,0.192804,-1.605881,-1.878166,-0.706216,0.035205,-0.379373,0.472251,...,-0.059162,-0.059162,0.550978,-0.669303,-0.118325,-1.224240,-1.224240,0.228880,-2.677361,-2.448481
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.481071,2.293537,0.306846,0.934021,-0.391876,-0.104952,-0.454148,-0.410555,...,0.767152,0.767152,1.655504,-0.121200,1.534304,1.227778,1.227778,1.825188,0.630368,2.455556

In [19]:
df_z.to_csv('transformed data/9-Work Context Freq Avg Z-Score Aggregates.csv', index=False)