In [25]:
import pandas as pd
df_occupation_data = pd.read_csv('ONET data/Occupation Data.csv')
df_task_statements = pd.read_csv('ONET data/Task Statements.csv')
df_skills = pd.read_csv('ONET data/Skills.csv')
df_abilities = pd.read_csv('ONET data/Abilities.csv')
df_work_activities = pd.read_csv('ONET data/Work Activities.csv')
df_knowledge = pd.read_csv('ONET data/Knowledge.csv')
df_work_context = pd.read_csv('ONET data/Work Context.csv')
df_tools_used = pd.read_csv('ONET data/Tools Used.csv')
df_technology_skills = pd.read_csv('ONET data/Technology Skills.csv')

In [26]:
df_task_statements

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source
0,11-1011.00,Chief Executives,8823,Direct or coordinate an organization's financi...,Core,95.0,08/2023,Incumbent
1,11-1011.00,Chief Executives,8824,"Confer with board members, organization offici...",Core,95.0,08/2023,Incumbent
2,11-1011.00,Chief Executives,8827,"Prepare budgets for approval, including those ...",Core,95.0,08/2023,Incumbent
3,11-1011.00,Chief Executives,8826,"Direct, plan, or implement policies, objective...",Core,94.0,08/2023,Incumbent
4,11-1011.00,Chief Executives,8834,Prepare or present reports concerning activiti...,Core,95.0,08/2023,Incumbent
...,...,...,...,...,...,...,...,...
18791,53-7121.00,"Tank Car, Truck, and Ship Loaders",12807,Unload cars containing liquids by connecting h...,Supplemental,85.0,08/2019,Incumbent
18792,53-7121.00,"Tank Car, Truck, and Ship Loaders",12804,"Clean interiors of tank cars or tank trucks, u...",Supplemental,85.0,08/2019,Incumbent
18793,53-7121.00,"Tank Car, Truck, and Ship Loaders",12803,Lower gauge rods into tanks or read meters to ...,Supplemental,85.0,08/2019,Incumbent
18794,53-7121.00,"Tank Car, Truck, and Ship Loaders",12805,Operate conveyors and equipment to transfer gr...,Supplemental,85.0,08/2019,Incumbent
18795,53-7121.00,"Tank Car, Truck, and Ship Loaders",12810,"Perform general warehouse activities, such as ...",Supplemental,85.0,08/2019,Incumbent

In [27]:
df_task_statements.columns

Index(['O*NET-SOC Code', 'Title', 'Task ID', 'Task', 'Task Type',
       'Incumbents Responding', 'Date', 'Domain Source'],
      dtype='object')

In [50]:
df_task_statements['O*NET-SOC Code'].nunique()

923

In [28]:
df_task_statements['Domain Source'].nunique()

4

In [29]:
df_task_statements['Domain Source'].value_counts()

Domain Source
Incumbent               13193
Occupational Expert      4413
Analyst                   845
Analyst - Transition      345
Name: count, dtype: int64

In [49]:
df_task_statements['Task Type'].value_counts()

Task Type
Core            13643
Supplemental     4308
Name: count, dtype: int64

# Mismatch in Task and Task ID.

In [30]:
df_task_statements['Task'].nunique()

17537

In [31]:
df_task_statements['Task ID'].nunique()

18796

In [32]:
dup_task_text = (
    df_task_statements
    .groupby('Task')['Task ID']
    .nunique()
    .reset_index()
)

dup_task_text = dup_task_text[dup_task_text['Task ID'] > 1]

dup_task_text = dup_task_text.sort_values('Task ID', ascending=False)

dup_task_text

                                                    Task  Task ID
2546   Compile bibliographies of specialized material...       34
9125   Maintain student attendance records, grades, a...       34
25             Act as advisers to student organizations.       34
15298  Serve on academic or administrative committees...       34
10973  Participate in student recruitment, registrati...       34
...                                                  ...      ...
6886   Follow appropriate procedures to get copyright...        2
6626   Explain and demonstrate work tasks to new work...        2
6530   Examine patient to obtain information on medic...        2
6496   Examine instruments, equipment, and operating ...        2
17509  Write supporting code for Web applications or ...        2

[397 rows x 2 columns]

In [33]:
example_task = dup_task_text.iloc[0]['Task']

pd.set_option('display.max_colwidth', None)

df_task_statements[df_task_statements['Task'] == example_task] \
    [['Task ID', 'Title', 'Task']] \
    .drop_duplicates()

,Task ID,Title,Task
5881,5678,"Business Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
5913,5707,"Computer Science Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
5938,5729,"Mathematical Science Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
5956,5744,"Architecture Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
5984,5773,"Engineering Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6006,5798,"Agricultural Sciences Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6031,5819,"Biological Science Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6059,5842,"Forestry and Conservation Science Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6081,5864,"Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6112,5889,"Chemistry Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6134,5912,"Environmental Science Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6159,5936,"Physics Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6188,5953,"Anthropology and Archeology Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6206,5976,"Area, Ethnic, and Cultural Studies Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6229,5999,"Economics Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6257,6024,"Geography Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6276,6048,"Political Science Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6307,6068,"Psychology Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6327,6096,"Sociology Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6356,6119,"Health Specialties Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6377,6140,"Nursing Instructors and Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6407,6165,"Education Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6424,6188,"Library Science Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6450,6209,"Criminal Justice and Law Enforcement Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6478,6232,"Law Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6495,6255,"Social Work Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6531,6282,"Art, Drama, and Music Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6552,6304,"Communications Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6576,6326,"English Language and Literature Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6606,6349,"Foreign Language and Literature Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6631,6373,"History Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6655,6394,"Philosophy and Religion Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6675,6418,"Family and Consumer Sciences Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.
6699,6437,"Recreation and Fitness Studies Teachers, Postsecondary",Compile bibliographies of specialized materials for outside reading assignments.

In [34]:
pd.reset_option('display.max_colwidth', None)

In [35]:
df_task_statements['Task_clean'] = (
    df_task_statements['Task']
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
)

In [36]:
df_task_statements['Task_Concept_ID'] = (
    df_task_statements['Task_clean']
    .astype('category')
    .cat.codes
)

In [42]:
df_task_statements['Concept_Instance_Number'] = (
    df_task_statements
    .groupby('Task_Concept_ID')
    .cumcount() + 1
)

In [43]:
df_task_statements['Semantic_Instance_ID'] = (
    df_task_statements['Task_Concept_ID'].astype(str)
    + '-'
    + df_task_statements['Concept_Instance_Number'].astype(str)
)

In [44]:
df_task_statements

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source,Task_clean,Task_Concept_ID,Concept_Instance_Number,Semantic_Instance_ID
0,11-1011.00,Chief Executives,8823,Direct or coordinate an organization's financi...,Core,95.0,08/2023,Incumbent,Direct or coordinate an organization's financi...,5388,1,5388-1
1,11-1011.00,Chief Executives,8824,"Confer with board members, organization offici...",Core,95.0,08/2023,Incumbent,"Confer with board members, organization offici...",3092,1,3092-1
2,11-1011.00,Chief Executives,8827,"Prepare budgets for approval, including those ...",Core,95.0,08/2023,Incumbent,"Prepare budgets for approval, including those ...",12105,1,12105-1
3,11-1011.00,Chief Executives,8826,"Direct, plan, or implement policies, objective...",Core,94.0,08/2023,Incumbent,"Direct, plan, or implement policies, objective...",5504,1,5504-1
4,11-1011.00,Chief Executives,8834,Prepare or present reports concerning activiti...,Core,95.0,08/2023,Incumbent,Prepare or present reports concerning activiti...,12319,1,12319-1
...,...,...,...,...,...,...,...,...,...,...,...,...
18791,53-7121.00,"Tank Car, Truck, and Ship Loaders",12807,Unload cars containing liquids by connecting h...,Supplemental,85.0,08/2019,Incumbent,Unload cars containing liquids by connecting h...,17006,1,17006-1
18792,53-7121.00,"Tank Car, Truck, and Ship Loaders",12804,"Clean interiors of tank cars or tank trucks, u...",Supplemental,85.0,08/2019,Incumbent,"Clean interiors of tank cars or tank trucks, u...",1975,1,1975-1
18793,53-7121.00,"Tank Car, Truck, and Ship Loaders",12803,Lower gauge rods into tanks or read meters to ...,Supplemental,85.0,08/2019,Incumbent,Lower gauge rods into tanks or read meters to ...,8769,1,8769-1
18794,53-7121.00,"Tank Car, Truck, and Ship Loaders",12805,Operate conveyors and equipment to transfer gr...,Supplemental,85.0,08/2019,Incumbent,Operate conveyors and equipment to transfer gr...,10488,1,10488-1
18795,53-7121.00,"Tank Car, Truck, and Ship Loaders",12810,"Perform general warehouse activities, such as ...",Supplemental,85.0,08/2019,Incumbent,"Perform general warehouse activities, such as ...",11210,1,11210-1

In [46]:
df_task_statements['Semantic_Instance_ID'].nunique()

18796

In [47]:
df_task_statements.shape

(18796, 12)

In [54]:
df_task_statements['Task_clean'] = (
    df_task_statements['Task']
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
)

df_task_statements['Task_String_ID'] = (
    pd.factorize(df_task_statements['Task_clean'])[0] + 1
)

In [55]:
df_task_statements

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source,Task_clean,Task_Concept_ID,Concept_Instance_Number,Semantic_Instance_ID,Task_String_ID
0,11-1011.00,Chief Executives,8823,Direct or coordinate an organization's financi...,Core,95.0,08/2023,Incumbent,Direct or coordinate an organization's financi...,5388,1,5388-1,1
1,11-1011.00,Chief Executives,8824,"Confer with board members, organization offici...",Core,95.0,08/2023,Incumbent,"Confer with board members, organization offici...",3092,1,3092-1,2
2,11-1011.00,Chief Executives,8827,"Prepare budgets for approval, including those ...",Core,95.0,08/2023,Incumbent,"Prepare budgets for approval, including those ...",12105,1,12105-1,3
3,11-1011.00,Chief Executives,8826,"Direct, plan, or implement policies, objective...",Core,94.0,08/2023,Incumbent,"Direct, plan, or implement policies, objective...",5504,1,5504-1,4
4,11-1011.00,Chief Executives,8834,Prepare or present reports concerning activiti...,Core,95.0,08/2023,Incumbent,Prepare or present reports concerning activiti...,12319,1,12319-1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18791,53-7121.00,"Tank Car, Truck, and Ship Loaders",12807,Unload cars containing liquids by connecting h...,Supplemental,85.0,08/2019,Incumbent,Unload cars containing liquids by connecting h...,17006,1,17006-1,17533
18792,53-7121.00,"Tank Car, Truck, and Ship Loaders",12804,"Clean interiors of tank cars or tank trucks, u...",Supplemental,85.0,08/2019,Incumbent,"Clean interiors of tank cars or tank trucks, u...",1975,1,1975-1,17534
18793,53-7121.00,"Tank Car, Truck, and Ship Loaders",12803,Lower gauge rods into tanks or read meters to ...,Supplemental,85.0,08/2019,Incumbent,Lower gauge rods into tanks or read meters to ...,8769,1,8769-1,17535
18794,53-7121.00,"Tank Car, Truck, and Ship Loaders",12805,Operate conveyors and equipment to transfer gr...,Supplemental,85.0,08/2019,Incumbent,Operate conveyors and equipment to transfer gr...,10488,1,10488-1,17536
18795,53-7121.00,"Tank Car, Truck, and Ship Loaders",12810,"Perform general warehouse activities, such as ...",Supplemental,85.0,08/2019,Incumbent,"Perform general warehouse activities, such as ...",11210,1,11210-1,17537

In [63]:
df_task_statements['Task_Concept_ID'].nunique()

17537

In [64]:
df_task_statements['Task_String_ID'].nunique()

17537

# Now with unique identifiers, aggregates can be made properly.

In [66]:
# Find count of unique task by title
total_tasks_by_title = (
    df_task_statements
    .groupby(['O*NET-SOC Code', 'Title'])['Task_String_ID']
    .nunique()
    .reset_index(name='TOTAL_TASKS_BY_JOB')
    .sort_values('TOTAL_TASKS_BY_JOB', ascending=False)
)

In [67]:
total_tasks_by_title

,O*NET-SOC Code,Title,TOTAL_TASKS_BY_JOB
323,25-2058.00,"Special Education Teachers, Secondary School",40
322,25-2057.00,"Special Education Teachers, Middle School",40
717,49-2022.00,Telecommunications Equipment Installers and Re...,39
220,19-2041.03,Industrial Ecologists,38
314,25-2021.00,"Elementary School Teachers, Except Special Edu...",38
...,...,...,...
909,53-7031.00,Dredge Operators,6
871,53-1041.00,Aircraft Cargo Handling Supervisors,6
667,47-2072.00,Pile Driver Operators,5
644,45-2041.00,"Graders and Sorters, Agricultural Products",5
557,39-5093.00,Shampooers,4

In [80]:
# Create column list of all tasks by title
tasks_by_title = (
    df_task_statements
    .groupby('Title')['Task']
    .apply(lambda x: '; '.join(
        f'"{e}"' for e in sorted(x.unique())
    ))
    .reset_index(name='TASK_LIST')
)

In [81]:
tasks_by_title

,Title,TASK_LIST
0,Accountants and Auditors,"""Advise clients in areas such as compensation,..."
1,Actors,"""Attend auditions and casting calls to auditio..."
2,Actuaries,"""Analyze statistical information to estimate m..."
3,Acupuncturists,"""Adhere to local, state, and federal laws, reg..."
4,Acute Care Nurses,"""Adjust settings on patients' assistive device..."
...,...,...
918,Wind Turbine Service Technicians,"""Assist in assembly of individual wind generat..."
919,"Woodworking Machine Setters, Operators, and Te...","""Adjust machine tables or cutting devices and ..."
920,Word Processors and Typists,"""Address envelopes or prepare envelope labels,..."
921,Writers and Authors,"""Collaborate with other writers on specific pr..."
922,Zoologists and Wildlife Biologists,"""Analyze characteristics of animals to identif..."

In [84]:
# Merge
tasks_and_concepts_by_job = total_tasks_by_title.merge(
    tasks_by_title,
    on=['Title'],
    how='left'
)

#tasks_and_concepts_by_job = tasks_and_concepts_by_job.drop('TOTAL_TASK_CONCEPTS_BY_JOB', axis=1)
tasks_and_concepts_by_job

,O*NET-SOC Code,Title,TOTAL_TASKS_BY_JOB,TASK_LIST
0,25-2058.00,"Special Education Teachers, Secondary School",40,"""Administer standardized ability and achieveme..."
1,25-2057.00,"Special Education Teachers, Middle School",40,"""Administer standardized ability and achieveme..."
2,49-2022.00,Telecommunications Equipment Installers and Re...,39,"""Address special issues or situations, such as..."
3,19-2041.03,Industrial Ecologists,38,"""Analyze changes designed to improve the envir..."
4,25-2021.00,"Elementary School Teachers, Except Special Edu...",38,"""Adapt teaching methods and instructional mate..."
...,...,...,...,...
918,53-7031.00,Dredge Operators,6,"""Direct or assist workers placing shore anchor..."
919,53-1041.00,Aircraft Cargo Handling Supervisors,6,"""Accompany aircraft as a member of the flight ..."
920,47-2072.00,Pile Driver Operators,5,"""Clean, lubricate, and refill equipment.""; ""Co..."
921,45-2041.00,"Graders and Sorters, Agricultural Products",5,"""Discard inferior or defective products or for..."
922,39-5093.00,Shampooers,4,"""Advise patrons with chronic or potentially co..."

In [103]:
tasks_and_concepts_by_job.to_csv('transformed data/3-Jobs Agg Tasks.csv', index=False)

In [106]:
df_task_statements

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source,Task_clean,Task_Concept_ID,Concept_Instance_Number,Semantic_Instance_ID,Task_String_ID
0,11-1011.00,Chief Executives,8823,Direct or coordinate an organization's financi...,Core,95.0,08/2023,Incumbent,Direct or coordinate an organization's financi...,5388,1,5388-1,1
1,11-1011.00,Chief Executives,8824,"Confer with board members, organization offici...",Core,95.0,08/2023,Incumbent,"Confer with board members, organization offici...",3092,1,3092-1,2
2,11-1011.00,Chief Executives,8827,"Prepare budgets for approval, including those ...",Core,95.0,08/2023,Incumbent,"Prepare budgets for approval, including those ...",12105,1,12105-1,3
3,11-1011.00,Chief Executives,8826,"Direct, plan, or implement policies, objective...",Core,94.0,08/2023,Incumbent,"Direct, plan, or implement policies, objective...",5504,1,5504-1,4
4,11-1011.00,Chief Executives,8834,Prepare or present reports concerning activiti...,Core,95.0,08/2023,Incumbent,Prepare or present reports concerning activiti...,12319,1,12319-1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18791,53-7121.00,"Tank Car, Truck, and Ship Loaders",12807,Unload cars containing liquids by connecting h...,Supplemental,85.0,08/2019,Incumbent,Unload cars containing liquids by connecting h...,17006,1,17006-1,17533
18792,53-7121.00,"Tank Car, Truck, and Ship Loaders",12804,"Clean interiors of tank cars or tank trucks, u...",Supplemental,85.0,08/2019,Incumbent,"Clean interiors of tank cars or tank trucks, u...",1975,1,1975-1,17534
18793,53-7121.00,"Tank Car, Truck, and Ship Loaders",12803,Lower gauge rods into tanks or read meters to ...,Supplemental,85.0,08/2019,Incumbent,Lower gauge rods into tanks or read meters to ...,8769,1,8769-1,17535
18794,53-7121.00,"Tank Car, Truck, and Ship Loaders",12805,Operate conveyors and equipment to transfer gr...,Supplemental,85.0,08/2019,Incumbent,Operate conveyors and equipment to transfer gr...,10488,1,10488-1,17536
18795,53-7121.00,"Tank Car, Truck, and Ship Loaders",12810,"Perform general warehouse activities, such as ...",Supplemental,85.0,08/2019,Incumbent,"Perform general warehouse activities, such as ...",11210,1,11210-1,17537

# Now jobs by task

In [107]:
# Find count of unique titles by task
total_tasks_by_title = (
    df_task_statements
    .groupby(['Task_String_ID'])['Title']
    .nunique()
    .reset_index(name='TOTAL_JOBS_BY_TASK')
    .sort_values('TOTAL_JOBS_BY_TASK', ascending=False)
)

In [108]:
# Create column list of all titles by task
tasks_by_title = (
    df_task_statements
    .groupby('Task_Concept_ID')['Title']
    .apply(lambda x: '; '.join(
        f'"{e}"' for e in sorted(x.unique())
    ))
    .reset_index(name='JOB_LIST')
)

In [109]:
total_tasks_by_title

       Task_String_ID  TOTAL_JOBS_BY_TASK
5789             5790                  34
5801             5802                  34
5800             5801                  34
5786             5787                  34
5796             5797                  34
...               ...                 ...
5876             5877                   1
5877             5878                   1
5878             5879                   1
5880             5881                   1
17536           17537                   1

[17537 rows x 2 columns]

In [110]:
tasks_by_title

       Task_Concept_ID                                           JOB_LIST
0                    0  "Mail Clerks and Mail Machine Operators, Excep...
1                    1       "Gambling Change Persons and Booth Cashiers"
2                    2                       "Disc Jockeys, Except Radio"
3                    3                    "Fast Food and Counter Workers"
4                    4                     "Loan Interviewers and Clerks"
...                ...                                                ...
17532            17532                                      "Legislators"
17533            17533          "Human Factors Engineers and Ergonomists"
17534            17534                  "Document Management Specialists"
17535            17535                             "Automotive Engineers"
17536            17536                             "Computer Programmers"

[17537 rows x 2 columns]

In [99]:
df_task_statements_big = df_task_statements.merge(
    total_tasks_by_title,
    on=['Task_String_ID'],
    how='left'
)

In [100]:
df_task_statements_big

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source,Task_clean,Task_Concept_ID,Concept_Instance_Number,Semantic_Instance_ID,Task_String_ID,TOTAL_JOBS_BY_TASK
0,11-1011.00,Chief Executives,8823,Direct or coordinate an organization's financi...,Core,95.0,08/2023,Incumbent,Direct or coordinate an organization's financi...,5388,1,5388-1,1,1
1,11-1011.00,Chief Executives,8824,"Confer with board members, organization offici...",Core,95.0,08/2023,Incumbent,"Confer with board members, organization offici...",3092,1,3092-1,2,1
2,11-1011.00,Chief Executives,8827,"Prepare budgets for approval, including those ...",Core,95.0,08/2023,Incumbent,"Prepare budgets for approval, including those ...",12105,1,12105-1,3,1
3,11-1011.00,Chief Executives,8826,"Direct, plan, or implement policies, objective...",Core,94.0,08/2023,Incumbent,"Direct, plan, or implement policies, objective...",5504,1,5504-1,4,1
4,11-1011.00,Chief Executives,8834,Prepare or present reports concerning activiti...,Core,95.0,08/2023,Incumbent,Prepare or present reports concerning activiti...,12319,1,12319-1,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18791,53-7121.00,"Tank Car, Truck, and Ship Loaders",12807,Unload cars containing liquids by connecting h...,Supplemental,85.0,08/2019,Incumbent,Unload cars containing liquids by connecting h...,17006,1,17006-1,17533,1
18792,53-7121.00,"Tank Car, Truck, and Ship Loaders",12804,"Clean interiors of tank cars or tank trucks, u...",Supplemental,85.0,08/2019,Incumbent,"Clean interiors of tank cars or tank trucks, u...",1975,1,1975-1,17534,1
18793,53-7121.00,"Tank Car, Truck, and Ship Loaders",12803,Lower gauge rods into tanks or read meters to ...,Supplemental,85.0,08/2019,Incumbent,Lower gauge rods into tanks or read meters to ...,8769,1,8769-1,17535,1
18794,53-7121.00,"Tank Car, Truck, and Ship Loaders",12805,Operate conveyors and equipment to transfer gr...,Supplemental,85.0,08/2019,Incumbent,Operate conveyors and equipment to transfer gr...,10488,1,10488-1,17536,1
18795,53-7121.00,"Tank Car, Truck, and Ship Loaders",12810,"Perform general warehouse activities, such as ...",Supplemental,85.0,08/2019,Incumbent,"Perform general warehouse activities, such as ...",11210,1,11210-1,17537,1

In [101]:
df_task_statements_big.nlargest(10, 'TOTAL_JOBS_BY_TASK')

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source,Task_clean,Task_Concept_ID,Concept_Instance_Number,Semantic_Instance_ID,Task_String_ID,TOTAL_JOBS_BY_TASK
5871,25-1011.00,"Business Teachers, Postsecondary",5666,"Maintain student attendance records, grades, a...",Core,104.0,08/2019,Incumbent,"Maintain student attendance records, grades, a...",9125,1,9125-1,5787,34
5874,25-1011.00,"Business Teachers, Postsecondary",5669,Maintain regularly scheduled office hours to a...,Core,105.0,08/2019,Incumbent,Maintain regularly scheduled office hours to a...,9108,1,9108-1,5790,34
5879,25-1011.00,"Business Teachers, Postsecondary",5676,Serve on academic or administrative committees...,Core,105.0,08/2019,Incumbent,Serve on academic or administrative committees...,15298,1,15298-1,5795,34
5881,25-1011.00,"Business Teachers, Postsecondary",5678,Compile bibliographies of specialized material...,Core,105.0,08/2019,Incumbent,Compile bibliographies of specialized material...,2546,1,2546-1,5797,34
5885,25-1011.00,"Business Teachers, Postsecondary",5675,"Participate in student recruitment, registrati...",Supplemental,105.0,08/2019,Incumbent,"Participate in student recruitment, registrati...",10973,1,10973-1,5801,34
5886,25-1011.00,"Business Teachers, Postsecondary",5682,Act as advisers to student organizations.,Supplemental,104.0,08/2019,Incumbent,Act as advisers to student organizations.,25,1,25-1,5802,34
5894,25-1021.00,"Computer Science Teachers, Postsecondary",5686,"Maintain student attendance records, grades, a...",Core,90.0,08/2019,Incumbent,"Maintain student attendance records, grades, a...",9125,2,9125-2,5787,34
5897,25-1021.00,"Computer Science Teachers, Postsecondary",5694,Maintain regularly scheduled office hours to a...,Core,90.0,08/2019,Incumbent,Maintain regularly scheduled office hours to a...,9108,2,9108-2,5790,34
5901,25-1021.00,"Computer Science Teachers, Postsecondary",5697,"Participate in student recruitment, registrati...",Core,90.0,08/2019,Incumbent,"Participate in student recruitment, registrati...",10973,2,10973-2,5801,34
5904,25-1021.00,"Computer Science Teachers, Postsecondary",5699,Serve on academic or administrative committees...,Core,90.0,08/2019,Incumbent,Serve on academic or administrative committees...,15298,2,15298-2,5795,34

In [111]:
df_task_statements_big = df_task_statements_big.merge(
    tasks_by_title,
    on=['Task_Concept_ID'],
    how='left'
)

In [112]:
df_task_statements_big

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source,Task_clean,Task_Concept_ID,Concept_Instance_Number,Semantic_Instance_ID,Task_String_ID,TOTAL_JOBS_BY_TASK,JOB_LIST
0,11-1011.00,Chief Executives,8823,Direct or coordinate an organization's financi...,Core,95.0,08/2023,Incumbent,Direct or coordinate an organization's financi...,5388,1,5388-1,1,1,"""Chief Executives"""
1,11-1011.00,Chief Executives,8824,"Confer with board members, organization offici...",Core,95.0,08/2023,Incumbent,"Confer with board members, organization offici...",3092,1,3092-1,2,1,"""Chief Executives"""
2,11-1011.00,Chief Executives,8827,"Prepare budgets for approval, including those ...",Core,95.0,08/2023,Incumbent,"Prepare budgets for approval, including those ...",12105,1,12105-1,3,1,"""Chief Executives"""
3,11-1011.00,Chief Executives,8826,"Direct, plan, or implement policies, objective...",Core,94.0,08/2023,Incumbent,"Direct, plan, or implement policies, objective...",5504,1,5504-1,4,1,"""Chief Executives"""
4,11-1011.00,Chief Executives,8834,Prepare or present reports concerning activiti...,Core,95.0,08/2023,Incumbent,Prepare or present reports concerning activiti...,12319,1,12319-1,5,1,"""Chief Executives"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18791,53-7121.00,"Tank Car, Truck, and Ship Loaders",12807,Unload cars containing liquids by connecting h...,Supplemental,85.0,08/2019,Incumbent,Unload cars containing liquids by connecting h...,17006,1,17006-1,17533,1,"""Tank Car, Truck, and Ship Loaders"""
18792,53-7121.00,"Tank Car, Truck, and Ship Loaders",12804,"Clean interiors of tank cars or tank trucks, u...",Supplemental,85.0,08/2019,Incumbent,"Clean interiors of tank cars or tank trucks, u...",1975,1,1975-1,17534,1,"""Tank Car, Truck, and Ship Loaders"""
18793,53-7121.00,"Tank Car, Truck, and Ship Loaders",12803,Lower gauge rods into tanks or read meters to ...,Supplemental,85.0,08/2019,Incumbent,Lower gauge rods into tanks or read meters to ...,8769,1,8769-1,17535,1,"""Tank Car, Truck, and Ship Loaders"""
18794,53-7121.00,"Tank Car, Truck, and Ship Loaders",12805,Operate conveyors and equipment to transfer gr...,Supplemental,85.0,08/2019,Incumbent,Operate conveyors and equipment to transfer gr...,10488,1,10488-1,17536,1,"""Tank Car, Truck, and Ship Loaders"""
18795,53-7121.00,"Tank Car, Truck, and Ship Loaders",12810,"Perform general warehouse activities, such as ...",Supplemental,85.0,08/2019,Incumbent,"Perform general warehouse activities, such as ...",11210,1,11210-1,17537,1,"""Tank Car, Truck, and Ship Loaders"""

In [113]:
df_task_statements_big.to_csv('transformed data/3-Tasks Agg Jobs.csv', index=False)