In [1]:
import pandas as pd
df_occupation_data = pd.read_csv('ONET data/Occupation Data.csv')
df_task_statements = pd.read_csv('ONET data/Task Statements.csv')
df_skills = pd.read_csv('ONET data/Skills.csv')
df_abilities = pd.read_csv('ONET data/Abilities.csv')
df_work_activities = pd.read_csv('ONET data/Work Activities.csv')
df_knowledge = pd.read_csv('ONET data/Knowledge.csv')
df_work_context = pd.read_csv('ONET data/Work Context.csv')
df_tools_used = pd.read_csv('ONET data/Tools Used.csv')
df_technology_skills = pd.read_csv('ONET data/Technology Skills.csv')

In [2]:
df_skills.columns

Index(['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID',
       'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound',
       'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date',
       'Domain Source'],
      dtype='object')

In [3]:
df_skills

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,LV,Level,4.62,8,0.1830,4.2664,4.9836,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,2.A.1.b,Active Listening,IM,Importance,4.00,8,0.0000,4.0000,4.0000,N,NaN,08/2023,Analyst
3,11-1011.00,Chief Executives,2.A.1.b,Active Listening,LV,Level,4.75,8,0.1637,4.4292,5.0708,N,N,08/2023,Analyst
4,11-1011.00,Chief Executives,2.A.1.c,Writing,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62575,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.b,Management of Financial Resources,LV,Level,1.12,8,0.1250,0.8800,1.3700,N,N,08/2019,Analyst
62576,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,IM,Importance,2.00,8,0.0000,2.0000,2.0000,N,NaN,08/2019,Analyst
62577,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,LV,Level,1.88,8,0.1250,1.6300,2.1200,N,N,08/2019,Analyst
62578,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,IM,Importance,2.88,8,0.1250,2.6300,3.1200,N,NaN,08/2019,Analyst
62579,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,LV,Level,2.75,8,0.1637,2.4292,3.0708,N,N,08/2019,Analyst

In [4]:
df_skills['Recommend Suppress'].value_counts()

Recommend Suppress
N    62433
Y      147
Name: count, dtype: int64

In [5]:
df_skills['Not Relevant'].value_counts()

Not Relevant
N    27907
Y     3383
Name: count, dtype: int64

In [6]:
df_skills['Element ID'].nunique()

35

In [7]:
df_skills['Element ID'].nunique()

35

In [8]:
123

123

# Pivot

In [9]:
df = df_skills.copy()

# Create combined column label
df["Skill_Scale"] = df["Element Name"] + " " + df["Scale Name"]

In [10]:
df_wide = df.pivot_table(
    index=["O*NET-SOC Code", "Title"],
    columns="Skill_Scale",
    values="Data Value"
).reset_index()

In [11]:
df_wide

Skill_Scale,O*NET-SOC Code,Title,Active Learning Importance,Active Learning Level,Active Listening Importance,Active Listening Level,Complex Problem Solving Importance,Complex Problem Solving Level,Coordination Importance,Coordination Level,...,Systems Evaluation Importance,Systems Evaluation Level,Technology Design Importance,Technology Design Level,Time Management Importance,Time Management Level,Troubleshooting Importance,Troubleshooting Level,Writing Importance,Writing Level
0,11-1011.00,Chief Executives,3.75,4.50,4.00,4.75,4.38,4.88,4.25,4.88,...,4.25,5.00,1.75,0.88,4.00,4.75,1.50,0.50,4.12,4.38
1,11-1011.03,Chief Sustainability Officers,3.75,3.88,4.00,4.00,4.00,4.12,3.75,3.88,...,3.88,4.00,1.88,1.12,3.38,3.88,1.00,0.00,4.12,4.25
2,11-1021.00,General and Operations Managers,3.62,3.75,4.00,4.12,3.62,3.88,3.88,4.00,...,3.12,3.25,1.50,0.62,3.62,3.88,1.75,1.00,3.50,3.88
3,11-2011.00,Advertising and Promotions Managers,3.25,4.12,4.12,4.12,3.50,3.88,3.50,4.12,...,3.12,3.75,1.75,0.75,3.50,3.88,1.00,0.00,3.75,3.88
4,11-2021.00,Marketing Managers,3.88,4.12,3.88,4.12,3.62,3.88,3.50,3.75,...,3.50,3.75,1.75,0.88,3.50,3.75,1.00,0.00,3.25,3.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,2.88,2.38,3.12,3.00,3.00,3.00,3.00,2.88,...,2.00,2.12,1.88,1.12,3.00,2.75,3.12,3.12,3.00,2.88
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",2.88,2.88,3.12,3.00,2.88,2.88,2.88,3.00,...,2.12,2.12,1.88,0.88,3.00,2.88,3.00,2.88,2.88,2.75
891,53-7073.00,Wellhead Pumpers,2.38,2.12,2.88,2.75,3.00,2.88,2.25,2.38,...,2.00,1.38,1.50,0.50,2.75,2.75,3.12,3.00,2.62,2.12
892,53-7081.00,Refuse and Recyclable Material Collectors,2.25,1.62,2.88,2.50,2.38,2.12,2.62,2.50,...,1.38,0.75,1.00,0.00,2.50,2.38,2.50,2.00,2.50,2.00
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.75,2.75,3.00,3.00,3.00,2.88,2.88,2.88,...,2.12,2.12,1.75,0.75,3.12,2.88,2.62,2.50,3.00,2.75

In [12]:
df_wide.to_csv('transformed data/4-Skills Pivoted.csv', index=False)

# Compare to average

In [13]:
df_wide = df_wide.copy()

# Identify numeric skill columns
skill_cols = df_wide.select_dtypes(include="number").columns

In [14]:
df_diff = df_wide.copy()

for col in skill_cols:
    df_diff[col] = df_wide[col] - df_wide[col].mean()

In [15]:
df_diff

Skill_Scale,O*NET-SOC Code,Title,Active Learning Importance,Active Learning Level,Active Listening Importance,Active Listening Level,Complex Problem Solving Importance,Complex Problem Solving Level,Coordination Importance,Coordination Level,...,Systems Evaluation Importance,Systems Evaluation Level,Technology Design Importance,Technology Design Level,Time Management Importance,Time Management Level,Troubleshooting Importance,Troubleshooting Level,Writing Importance,Writing Level
0,11-1011.00,Chief Executives,0.632136,1.301454,0.402539,1.19415,1.167975,1.719776,1.123479,1.734653,...,1.599251,2.362908,0.03094,-0.109676,0.903412,1.70774,-0.542327,-1.05396,0.928065,1.068568
1,11-1011.03,Chief Sustainability Officers,0.632136,0.681454,0.402539,0.44415,0.787975,0.959776,0.623479,0.734653,...,1.229251,1.362908,0.16094,0.130324,0.283412,0.83774,-1.042327,-1.55396,0.928065,0.938568
2,11-1021.00,General and Operations Managers,0.502136,0.551454,0.402539,0.56415,0.407975,0.719776,0.753479,0.854653,...,0.469251,0.612908,-0.21906,-0.369676,0.523412,0.83774,-0.292327,-0.55396,0.308065,0.568568
3,11-2011.00,Advertising and Promotions Managers,0.132136,0.921454,0.522539,0.56415,0.287975,0.719776,0.373479,0.974653,...,0.469251,1.112908,0.03094,-0.239676,0.403412,0.83774,-1.042327,-1.55396,0.558065,0.568568
4,11-2021.00,Marketing Managers,0.762136,0.921454,0.282539,0.56415,0.407975,0.719776,0.373479,0.604653,...,0.849251,1.112908,0.03094,-0.109676,0.403412,0.70774,-1.042327,-1.55396,0.058065,0.568568
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,-0.237864,-0.818546,-0.477461,-0.55585,-0.212025,-0.160224,-0.126521,-0.265347,...,-0.650749,-0.517092,0.16094,0.130324,-0.096588,-0.29226,1.077673,1.56604,-0.191935,-0.431432
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",-0.237864,-0.318546,-0.477461,-0.55585,-0.332025,-0.280224,-0.246521,-0.145347,...,-0.530749,-0.517092,0.16094,-0.109676,-0.096588,-0.16226,0.957673,1.32604,-0.311935,-0.561432
891,53-7073.00,Wellhead Pumpers,-0.737864,-1.078546,-0.717461,-0.80585,-0.212025,-0.280224,-0.876521,-0.765347,...,-0.650749,-1.257092,-0.21906,-0.489676,-0.346588,-0.29226,1.077673,1.44604,-0.571935,-1.191432
892,53-7081.00,Refuse and Recyclable Material Collectors,-0.867864,-1.578546,-0.717461,-1.05585,-0.832025,-1.040224,-0.506521,-0.645347,...,-1.270749,-1.887092,-0.71906,-0.989676,-0.596588,-0.66226,0.457673,0.44604,-0.691935,-1.311432
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",-0.367864,-0.448546,-0.597461,-0.55585,-0.212025,-0.280224,-0.246521,-0.265347,...,-0.530749,-0.517092,0.03094,-0.239676,0.023412,-0.16226,0.577673,0.94604,-0.191935,-0.561432

# Percent of mean

In [16]:
df_pct = df_wide.copy()

# Identify numeric skill columns
skill_cols = df_wide.select_dtypes(include="number").columns

for col in skill_cols:
    mean_val = df_wide[col].mean()
    df_pct[col] = (df_wide[col] - mean_val) / mean_val * 100

In [17]:
df_pct

Skill_Scale,O*NET-SOC Code,Title,Active Learning Importance,Active Learning Level,Active Listening Importance,Active Listening Level,Complex Problem Solving Importance,Complex Problem Solving Level,Coordination Importance,Coordination Level,...,Systems Evaluation Importance,Systems Evaluation Level,Technology Design Importance,Technology Design Level,Time Management Importance,Time Management Level,Troubleshooting Importance,Troubleshooting Level,Writing Importance,Writing Level
0,11-1011.00,Chief Executives,20.274668,40.688932,11.189535,33.582683,36.362592,54.419448,35.933827,55.149825,...,60.332015,89.602810,1.799797,-11.081976,29.174418,56.133952,-26.554353,-67.824134,29.075305,32.269070
1,11-1011.03,Chief Sustainability Officers,20.274668,21.305123,11.189535,12.490681,24.532047,30.370517,19.941612,23.356828,...,46.373699,51.682248,9.362068,13.168394,9.152383,27.536786,-51.036235,-100.000000,29.075305,28.343276
2,11-1021.00,General and Operations Managers,16.105146,17.240776,11.189535,15.865401,12.701503,22.776118,24.099588,27.171988,...,17.702562,23.241826,-12.743031,-37.353210,16.902848,27.536786,-14.313412,-35.648268,9.651351,17.169861
3,11-2011.00,Advertising and Promotions Managers,4.238045,28.808533,14.525221,15.865401,8.965541,22.776118,11.945505,30.987148,...,17.702562,42.202107,1.799797,-24.217593,13.027616,27.536786,-51.036235,-100.000000,17.483591,17.169861
4,11-2021.00,Marketing Managers,24.444189,28.808533,7.853849,15.865401,12.701503,22.776118,11.945505,19.223739,...,32.038130,42.202107,1.799797,-11.081976,13.027616,23.263646,-51.036235,-100.000000,1.819112,17.169861
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,-7.629055,-25.591187,-13.272163,-15.631989,-6.600965,-5.070012,-4.046710,-8.436169,...,-24.549640,-19.608409,9.362068,13.168394,-3.119187,-9.606659,52.766946,100.777403,-6.013127,-13.028557
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",-7.629055,-9.959084,-13.272163,-15.631989,-10.336926,-8.867211,-7.884842,-4.621009,...,-20.022618,-19.608409,9.362068,-11.081976,-3.119187,-5.333520,46.891294,85.332988,-9.772602,-16.954351
891,53-7073.00,Wellhead Pumpers,-23.665678,-33.719881,-19.943535,-22.662657,-6.600965,-8.867211,-28.035033,-24.332667,...,-24.549640,-47.669625,-12.743031,-49.478396,-11.192588,-9.606659,52.766946,93.055196,-17.918131,-35.979354
892,53-7081.00,Refuse and Recyclable Material Collectors,-27.835199,-49.351985,-19.943535,-29.693324,-25.903432,-32.916142,-16.200794,-20.517507,...,-47.939251,-71.559579,-41.828687,-100.000000,-19.265989,-21.768672,22.409412,28.703464,-21.677606,-39.603164
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",-11.798577,-14.023431,-16.607849,-15.631989,-6.600965,-8.867211,-7.884842,-8.436169,...,-20.022618,-19.608409,1.799797,-24.217593,0.756046,-5.333520,28.285063,60.879330,-6.013127,-16.954351

In [18]:
meta_cols = ["O*NET-SOC Code", "Title"]

level_cols = [
    col for col in df_pct.columns
    if "Level" in col
]

import_cols = [
    col for col in df_pct.columns
    if "Importance" in col
]

df_pct["z_level_avg"] = df_pct[level_cols].mean(axis=1)
df_pct["z_import_avg"] = df_pct[import_cols].mean(axis=1)

In [19]:
df_pct

Skill_Scale,O*NET-SOC Code,Title,Active Learning Importance,Active Learning Level,Active Listening Importance,Active Listening Level,Complex Problem Solving Importance,Complex Problem Solving Level,Coordination Importance,Coordination Level,...,Technology Design Importance,Technology Design Level,Time Management Importance,Time Management Level,Troubleshooting Importance,Troubleshooting Level,Writing Importance,Writing Level,z_level_avg,z_import_avg
0,11-1011.00,Chief Executives,20.274668,40.688932,11.189535,33.582683,36.362592,54.419448,35.933827,55.149825,...,1.799797,-11.081976,29.174418,56.133952,-26.554353,-67.824134,29.075305,32.269070,32.949320,20.596210
1,11-1011.03,Chief Sustainability Officers,20.274668,21.305123,11.189535,12.490681,24.532047,30.370517,19.941612,23.356828,...,9.362068,13.168394,9.152383,27.536786,-51.036235,-100.000000,29.075305,28.343276,10.971351,9.940843
2,11-1021.00,General and Operations Managers,16.105146,17.240776,11.189535,15.865401,12.701503,22.776118,24.099588,27.171988,...,-12.743031,-37.353210,16.902848,27.536786,-14.313412,-35.648268,9.651351,17.169861,5.688143,7.485602
3,11-2011.00,Advertising and Promotions Managers,4.238045,28.808533,14.525221,15.865401,8.965541,22.776118,11.945505,30.987148,...,1.799797,-24.217593,13.027616,27.536786,-51.036235,-100.000000,17.483591,17.169861,1.449086,1.988136
4,11-2021.00,Marketing Managers,24.444189,28.808533,7.853849,15.865401,12.701503,22.776118,11.945505,19.223739,...,1.799797,-11.081976,13.027616,23.263646,-51.036235,-100.000000,1.819112,17.169861,9.437427,5.764530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,-7.629055,-25.591187,-13.272163,-15.631989,-6.600965,-5.070012,-4.046710,-8.436169,...,9.362068,13.168394,-3.119187,-9.606659,52.766946,100.777403,-6.013127,-13.028557,4.896222,2.125613
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",-7.629055,-9.959084,-13.272163,-15.631989,-10.336926,-8.867211,-7.884842,-4.621009,...,9.362068,-11.081976,-3.119187,-5.333520,46.891294,85.332988,-9.772602,-16.954351,7.743139,4.503635
891,53-7073.00,Wellhead Pumpers,-23.665678,-33.719881,-19.943535,-22.662657,-6.600965,-8.867211,-28.035033,-24.332667,...,-12.743031,-49.478396,-11.192588,-9.606659,52.766946,93.055196,-17.918131,-35.979354,-5.662770,-4.964674
892,53-7081.00,Refuse and Recyclable Material Collectors,-27.835199,-49.351985,-19.943535,-29.693324,-25.903432,-32.916142,-16.200794,-20.517507,...,-41.828687,-100.000000,-19.265989,-21.768672,22.409412,28.703464,-21.677606,-39.603164,-38.551722,-20.292324
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",-11.798577,-14.023431,-16.607849,-15.631989,-6.600965,-8.867211,-7.884842,-8.436169,...,1.799797,-24.217593,0.756046,-5.333520,28.285063,60.879330,-6.013127,-16.954351,-1.419197,-0.582746

# Z Scores

In [20]:
df_z = df_wide.copy()

# Identify numeric skill columns
skill_cols = df_wide.select_dtypes(include="number").columns


for col in skill_cols:
    df_z[col] = (
        (df_wide[col] - df_wide[col].mean()) /
        df_wide[col].std()
    )

In [21]:
meta_cols = ["O*NET-SOC Code", "Title"]

level_cols = [
    col for col in df_z.columns
    if "Level" in col
]

import_cols = [
    col for col in df_z.columns
    if "Importance" in col
]

# df_z["z_level_mean"] = df_z[level_cols].mean(axis=1)
# df_z["z_level_median"] = df_z[level_cols].median(axis=1)
# df_z["z_level_max"] = df_z[level_cols].max(axis=1)
# df_z["z_level_min"] = df_z[level_cols].min(axis=1)
# df_z["z_level_min+max"] = df_z["z_level_min"] + df_z["z_level_max"]

# df_z["z_import_mean"] = df_z[import_cols].mean(axis=1)
# df_z["z_import_median"] = df_z[import_cols].median(axis=1)
# df_z["z_import_max"] = df_z[import_cols].max(axis=1)
# df_z["z_import_min"] = df_z[import_cols].min(axis=1)
# df_z["z_import_min+max"] = df_z["z_import_min"] + df_z["z_import_max"]

In [22]:
df_z

Skill_Scale,O*NET-SOC Code,Title,Active Learning Importance,Active Learning Level,Active Listening Importance,Active Listening Level,Complex Problem Solving Importance,Complex Problem Solving Level,Coordination Importance,Coordination Level,...,Systems Evaluation Importance,Systems Evaluation Level,Technology Design Importance,Technology Design Level,Time Management Importance,Time Management Level,Troubleshooting Importance,Troubleshooting Level,Writing Importance,Writing Level
0,11-1011.00,Chief Executives,1.194878,1.668012,0.874293,1.860218,2.318552,2.538488,2.901621,3.433018,...,2.831705,2.743987,0.077156,-0.151136,2.742732,3.451499,-0.709481,-0.920634,1.452521,1.254571
1,11-1011.03,Chief Sustainability Officers,1.194878,0.873388,0.874293,0.691886,1.564212,1.416685,1.610266,1.453938,...,2.176566,1.582712,0.401343,0.179590,0.860430,1.693150,-1.363590,-1.357384,1.452521,1.101942
2,11-1021.00,General and Operations Managers,0.949149,0.706773,0.874293,0.878819,0.809873,1.062431,1.946018,1.691427,...,0.830876,0.711755,-0.546282,-0.509423,1.589063,1.693150,-0.382427,-0.483884,0.482155,0.667537
3,11-2011.00,Advertising and Promotions Managers,0.249767,1.180984,1.134927,0.878819,0.571661,1.062431,0.964588,1.928917,...,0.830876,1.292393,0.077156,-0.330279,1.224746,1.693150,-1.363590,-1.357384,0.873432,0.667537
4,11-2021.00,Marketing Managers,1.440607,1.180984,0.613660,0.878819,0.809873,1.062431,0.964588,1.196657,...,1.503721,1.292393,0.077156,-0.151136,1.224746,1.430408,-1.363590,-1.357384,0.090878,0.667537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,-0.449615,-1.049092,-1.037019,-0.865890,-0.420891,-0.236499,-0.326768,-0.525143,...,-1.152246,-0.600486,0.401343,0.179590,-0.293240,-0.590683,1.409831,1.367936,-0.300399,-0.506530
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",-0.449615,-0.408265,-1.037019,-0.865890,-0.659103,-0.413626,-0.636693,-0.287653,...,-0.939769,-0.600486,0.401343,-0.151136,-0.293240,-0.327941,1.252845,1.158296,-0.488212,-0.659159
891,53-7073.00,Wellhead Pumpers,-1.394726,-1.382321,-1.558287,-1.255334,-0.420891,-0.413626,-2.263801,-1.514683,...,-1.152246,-1.459830,-0.546282,-0.674786,-1.052232,-0.590683,1.409831,1.263116,-0.895140,-1.398821
892,53-7081.00,Refuse and Recyclable Material Collectors,-1.640454,-2.023148,-1.558287,-1.644778,-1.651655,-1.535430,-1.308198,-1.277193,...,-2.250046,-2.191433,-1.793157,-1.363799,-1.811225,-1.338487,0.598736,0.389616,-1.082953,-1.539709
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",-0.695344,-0.574880,-1.297653,-0.865890,-0.420891,-0.413626,-0.636693,-0.525143,...,-0.939769,-0.600486,0.077156,-0.330279,0.071077,-0.327941,0.755723,0.826366,-0.300399,-0.659159

In [ ]:
df_z.to_csv('transformed data/4-Skills Z-Scores.csv', index=False)

In [35]:
# Define columns to prefix
cols_to_prefix = df_z.drop(columns=['O*NET-SOC Code', 'Title']).columns
# Apply prefix to these columns
df_z_pref = df_z.rename(columns={c: f'pre_{c}' for c in cols_to_prefix})
df_z_pref

Skill_Scale,O*NET-SOC Code,Title,pre_Active Learning Importance,pre_Active Learning Level,pre_Active Listening Importance,pre_Active Listening Level,pre_Complex Problem Solving Importance,pre_Complex Problem Solving Level,pre_Coordination Importance,pre_Coordination Level,...,pre_Systems Evaluation Importance,pre_Systems Evaluation Level,pre_Technology Design Importance,pre_Technology Design Level,pre_Time Management Importance,pre_Time Management Level,pre_Troubleshooting Importance,pre_Troubleshooting Level,pre_Writing Importance,pre_Writing Level
0,11-1011.00,Chief Executives,1.194878,1.668012,0.874293,1.860218,2.318552,2.538488,2.901621,3.433018,...,2.831705,2.743987,0.077156,-0.151136,2.742732,3.451499,-0.709481,-0.920634,1.452521,1.254571
1,11-1011.03,Chief Sustainability Officers,1.194878,0.873388,0.874293,0.691886,1.564212,1.416685,1.610266,1.453938,...,2.176566,1.582712,0.401343,0.179590,0.860430,1.693150,-1.363590,-1.357384,1.452521,1.101942
2,11-1021.00,General and Operations Managers,0.949149,0.706773,0.874293,0.878819,0.809873,1.062431,1.946018,1.691427,...,0.830876,0.711755,-0.546282,-0.509423,1.589063,1.693150,-0.382427,-0.483884,0.482155,0.667537
3,11-2011.00,Advertising and Promotions Managers,0.249767,1.180984,1.134927,0.878819,0.571661,1.062431,0.964588,1.928917,...,0.830876,1.292393,0.077156,-0.330279,1.224746,1.693150,-1.363590,-1.357384,0.873432,0.667537
4,11-2021.00,Marketing Managers,1.440607,1.180984,0.613660,0.878819,0.809873,1.062431,0.964588,1.196657,...,1.503721,1.292393,0.077156,-0.151136,1.224746,1.430408,-1.363590,-1.357384,0.090878,0.667537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,-0.449615,-1.049092,-1.037019,-0.865890,-0.420891,-0.236499,-0.326768,-0.525143,...,-1.152246,-0.600486,0.401343,0.179590,-0.293240,-0.590683,1.409831,1.367936,-0.300399,-0.506530
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",-0.449615,-0.408265,-1.037019,-0.865890,-0.659103,-0.413626,-0.636693,-0.287653,...,-0.939769,-0.600486,0.401343,-0.151136,-0.293240,-0.327941,1.252845,1.158296,-0.488212,-0.659159
891,53-7073.00,Wellhead Pumpers,-1.394726,-1.382321,-1.558287,-1.255334,-0.420891,-0.413626,-2.263801,-1.514683,...,-1.152246,-1.459830,-0.546282,-0.674786,-1.052232,-0.590683,1.409831,1.263116,-0.895140,-1.398821
892,53-7081.00,Refuse and Recyclable Material Collectors,-1.640454,-2.023148,-1.558287,-1.644778,-1.651655,-1.535430,-1.308198,-1.277193,...,-2.250046,-2.191433,-1.793157,-1.363799,-1.811225,-1.338487,0.598736,0.389616,-1.082953,-1.539709
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",-0.695344,-0.574880,-1.297653,-0.865890,-0.420891,-0.413626,-0.636693,-0.525143,...,-0.939769,-0.600486,0.077156,-0.330279,0.071077,-0.327941,0.755723,0.826366,-0.300399,-0.659159

# Z Score aggregates

In [30]:
df_z_aggs = df_z.copy()



df_z_aggs["z_level_mean"] = df_z_aggs[level_cols].mean(axis=1)
df_z_aggs["z_level_median"] = df_z_aggs[level_cols].median(axis=1)
df_z_aggs["z_level_max"] = df_z_aggs[level_cols].max(axis=1)
df_z_aggs["z_level_min"] = df_z_aggs[level_cols].min(axis=1)
df_z_aggs["z_level_min+max"] = df_z_aggs["z_level_min"] + df_z_aggs["z_level_max"]

df_z_aggs["z_import_mean"] = df_z_aggs[import_cols].mean(axis=1)
df_z_aggs["z_import_median"] = df_z_aggs[import_cols].median(axis=1)
df_z_aggs["z_import_max"] = df_z_aggs[import_cols].max(axis=1)
df_z_aggs["z_import_min"] = df_z_aggs[import_cols].min(axis=1)
df_z_aggs["z_import_min+max"] = df_z_aggs["z_import_min"] + df_z_aggs["z_import_max"]

# Drop level_cols and import_cols as defined earlier
df_z_aggs = df_z_aggs.drop(columns=level_cols)
df_z_aggs = df_z_aggs.drop(columns=import_cols)

In [31]:
df_z_aggs

Skill_Scale,O*NET-SOC Code,Title,z_level_mean,z_level_median,z_level_max,z_level_min,z_level_min+max,z_import_mean,z_import_median,z_import_max,z_import_min,z_import_min+max
0,11-1011.00,Chief Executives,1.466968,1.668012,4.291302,-1.043132,3.248170,1.306122,1.194878,4.833021,-0.875839,3.957182
1,11-1011.03,Chief Sustainability Officers,0.682580,0.873388,2.070254,-1.357384,0.712870,0.719463,0.928922,2.257247,-1.363590,0.893657
2,11-1021.00,General and Operations Managers,0.566494,0.580562,2.237148,-1.043478,1.193670,0.623458,0.769709,2.618555,-1.052495,1.566060
3,11-2011.00,Advertising and Promotions Managers,0.525828,0.771054,2.500783,-1.637725,0.863057,0.364346,0.571661,1.767883,-1.369178,0.398705
4,11-2021.00,Marketing Managers,0.672231,0.878819,2.643585,-1.428144,1.215441,0.538591,0.692424,2.174034,-1.369178,0.804856
...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,-0.236714,-0.590683,1.678398,-1.521662,0.156736,-0.171555,-0.449615,1.973828,-1.624028,0.349800
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",-0.152006,-0.327941,1.490643,-1.287637,0.203006,-0.069080,-0.293240,1.809881,-1.175959,0.633922
891,53-7073.00,Wellhead Pumpers,-0.623570,-0.898263,2.203584,-2.565963,-0.362379,-0.564822,-0.928926,1.973828,-2.263801,-0.289973
892,53-7081.00,Refuse and Recyclable Material Collectors,-1.243686,-1.475708,0.914536,-3.190460,-2.275924,-1.176899,-1.432529,1.246921,-2.647056,-1.400136
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",-0.261772,-0.477179,1.266325,-1.521662,-0.255338,-0.255040,-0.440718,1.788212,-1.624028,0.164184

In [32]:
df_z_aggs.to_csv('transformed data/4-Skills Z-Score Aggregates.csv', index=False)

In [37]:
# Define columns to prefix
cols_to_prefix = df_z_aggs.drop(columns=['O*NET-SOC Code', 'Title']).columns
# Apply prefix to these columns
df_z_aggs_pref = df_z_aggs.rename(columns={c: f'SKILL_{c}' for c in cols_to_prefix})
df_z_aggs_pref

Skill_Scale,O*NET-SOC Code,Title,SKILL_z_level_mean,SKILL_z_level_median,SKILL_z_level_max,SKILL_z_level_min,SKILL_z_level_min+max,SKILL_z_import_mean,SKILL_z_import_median,SKILL_z_import_max,SKILL_z_import_min,SKILL_z_import_min+max
0,11-1011.00,Chief Executives,1.466968,1.668012,4.291302,-1.043132,3.248170,1.306122,1.194878,4.833021,-0.875839,3.957182
1,11-1011.03,Chief Sustainability Officers,0.682580,0.873388,2.070254,-1.357384,0.712870,0.719463,0.928922,2.257247,-1.363590,0.893657
2,11-1021.00,General and Operations Managers,0.566494,0.580562,2.237148,-1.043478,1.193670,0.623458,0.769709,2.618555,-1.052495,1.566060
3,11-2011.00,Advertising and Promotions Managers,0.525828,0.771054,2.500783,-1.637725,0.863057,0.364346,0.571661,1.767883,-1.369178,0.398705
4,11-2021.00,Marketing Managers,0.672231,0.878819,2.643585,-1.428144,1.215441,0.538591,0.692424,2.174034,-1.369178,0.804856
...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,-0.236714,-0.590683,1.678398,-1.521662,0.156736,-0.171555,-0.449615,1.973828,-1.624028,0.349800
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",-0.152006,-0.327941,1.490643,-1.287637,0.203006,-0.069080,-0.293240,1.809881,-1.175959,0.633922
891,53-7073.00,Wellhead Pumpers,-0.623570,-0.898263,2.203584,-2.565963,-0.362379,-0.564822,-0.928926,1.973828,-2.263801,-0.289973
892,53-7081.00,Refuse and Recyclable Material Collectors,-1.243686,-1.475708,0.914536,-3.190460,-2.275924,-1.176899,-1.432529,1.246921,-2.647056,-1.400136
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",-0.261772,-0.477179,1.266325,-1.521662,-0.255338,-0.255040,-0.440718,1.788212,-1.624028,0.164184

In [39]:
df_z_aggs_pref.to_csv('transformed data/4-Skills Z-Score Aggregates.csv', index=False)

# SKIPPING THIS - Remove irrelevant skills

In [26]:
df_relevant = df_skills.copy()

# Rename column, relabel data, change column data type
df_relevant.rename(columns={'Not Relevant': 'Relevant'}, inplace=True)
df_relevant['Relevant'] = df_relevant['Relevant'].replace('Y', '0')
df_relevant['Relevant'] = df_relevant['Relevant'].replace('N', '1')
df_relevant['Relevant'] = df_relevant['Relevant'].fillna(1)
df_relevant['Relevant'] = df_relevant['Relevant'].astype('int')

# 
df_relevant['Recommend Suppress'] = df_relevant['Recommend Suppress'].replace('Y', '1')
df_relevant['Recommend Suppress'] = df_relevant['Recommend Suppress'].replace('N', '0')
df_relevant['Recommend Suppress'] = df_relevant['Recommend Suppress'].astype('int')

In [27]:
df_relevant

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,IM,Importance,4.12,8,0.1250,3.8800,4.3700,0,1,08/2023,Analyst
1,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,LV,Level,4.62,8,0.1830,4.2664,4.9836,0,1,08/2023,Analyst
2,11-1011.00,Chief Executives,2.A.1.b,Active Listening,IM,Importance,4.00,8,0.0000,4.0000,4.0000,0,1,08/2023,Analyst
3,11-1011.00,Chief Executives,2.A.1.b,Active Listening,LV,Level,4.75,8,0.1637,4.4292,5.0708,0,1,08/2023,Analyst
4,11-1011.00,Chief Executives,2.A.1.c,Writing,IM,Importance,4.12,8,0.1250,3.8800,4.3700,0,1,08/2023,Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62575,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.b,Management of Financial Resources,LV,Level,1.12,8,0.1250,0.8800,1.3700,0,1,08/2019,Analyst
62576,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,IM,Importance,2.00,8,0.0000,2.0000,2.0000,0,1,08/2019,Analyst
62577,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,LV,Level,1.88,8,0.1250,1.6300,2.1200,0,1,08/2019,Analyst
62578,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,IM,Importance,2.88,8,0.1250,2.6300,3.1200,0,1,08/2019,Analyst
62579,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,LV,Level,2.75,8,0.1637,2.4292,3.0708,0,1,08/2019,Analyst

In [28]:
df_irrev = df_relevant[df_relevant['Recommend Suppress'] == 1]
df_irrev = df_irrev[df_irrev['Relevant'] == 0]
df_irrev

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Relevant,Date,Domain Source
965,11-3031.03,Investment Fund Managers,2.B.3.m,Quality Control Analysis,LV,Level,0.75,8,0.5261,0.0,1.7812,1,0,07/2014,Analyst
1239,11-3051.03,Biofuels Production Managers,2.B.3.j,Equipment Maintenance,LV,Level,0.75,8,0.5261,0.0,1.7812,1,0,07/2016,Analyst
5933,13-1199.07,Security Management Specialists,2.B.3.l,Repairing,LV,Level,0.75,8,0.5261,0.0,1.7812,1,0,08/2025,Analyst
7669,15-1243.01,Data Warehousing Specialists,2.B.3.c,Equipment Selection,LV,Level,0.88,8,0.5806,0.0,2.0129,1,0,08/2018,Analyst
8379,15-1299.05,Information Security Engineers,2.B.3.j,Equipment Maintenance,LV,Level,0.75,8,0.5261,0.0,1.7812,1,0,08/2025,Analyst
24329,27-2041.00,Music Directors and Composers,2.B.3.c,Equipment Selection,LV,Level,1.00,8,0.7559,0.0,2.4816,1,0,08/2022,Analyst
38695,41-3031.00,"Securities, Commodities, and Financial Service...",2.B.3.m,Quality Control Analysis,LV,Level,0.88,8,0.5806,0.0,2.0129,1,0,08/2022,Analyst
47711,47-5032.00,"Explosives Workers, Ordnance Handling Experts,...",2.B.3.d,Installation,LV,Level,0.88,8,0.5806,0.0,2.0129,1,0,06/2010,Analyst

In [30]:
df_rev_sup = df_relevant[df_relevant['Recommend Suppress'] == 1]
df_rev_sup = df_rev_sup[df_rev_sup['Relevant'] == 1]
df_rev_sup

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Relevant,Date,Domain Source
665,11-3013.01,Security Managers,2.B.3.a,Operations Analysis,LV,Level,2.00,8,0.6547,0.7169,3.2831,1,1,08/2025,Analyst
805,11-3031.00,Financial Managers,2.B.3.a,Operations Analysis,LV,Level,1.12,8,0.5154,0.1148,2.1352,1,1,08/2022,Analyst
813,11-3031.00,Financial Managers,2.B.3.e,Programming,LV,Level,1.62,8,0.5957,0.4573,2.7927,1,1,08/2022,Analyst
829,11-3031.00,Financial Managers,2.B.4.g,Systems Analysis,LV,Level,3.25,8,0.5261,2.2188,4.2812,1,1,08/2022,Analyst
831,11-3031.00,Financial Managers,2.B.4.h,Systems Evaluation,LV,Level,3.25,8,0.5590,2.1543,4.3457,1,1,08/2022,Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57585,51-9071.00,Jewelers and Precious Stone and Metal Workers,2.B.3.g,Operations Monitoring,LV,Level,1.75,8,0.5261,0.7188,2.7812,1,1,08/2025,Analyst
58353,51-9162.00,Computer Numerically Controlled Tool Programmers,2.B.3.e,Programming,LV,Level,3.62,8,0.5324,2.5814,4.6686,1,1,08/2025,Analyst
58709,51-9195.00,"Molders, Shapers, and Casters, Except Metal an...",2.B.3.j,Equipment Maintenance,LV,Level,1.88,8,0.5154,0.8648,2.8852,1,1,08/2024,Analyst
60459,53-4022.00,"Railroad Brake, Signal, and Switch Operators a...",2.B.3.j,Equipment Maintenance,LV,Level,1.38,8,0.5650,0.2676,2.4824,1,1,08/2024,Analyst
61705,53-7041.00,Hoist and Winch Operators,2.B.3.a,Operations Analysis,LV,Level,1.12,8,0.5806,0.0000,2.2629,1,1,06/2010,Analyst

In [29]:
df_relevant.shape

(62580, 15)

In [31]:
df_relevant_only = df_relevant[df_relevant['Recommend Suppress'] == 0]
df_relevant_only = df_relevant_only[df_relevant_only['Relevant'] == 1]
df_relevant_only

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,IM,Importance,4.12,8,0.1250,3.8800,4.3700,0,1,08/2023,Analyst
1,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,LV,Level,4.62,8,0.1830,4.2664,4.9836,0,1,08/2023,Analyst
2,11-1011.00,Chief Executives,2.A.1.b,Active Listening,IM,Importance,4.00,8,0.0000,4.0000,4.0000,0,1,08/2023,Analyst
3,11-1011.00,Chief Executives,2.A.1.b,Active Listening,LV,Level,4.75,8,0.1637,4.4292,5.0708,0,1,08/2023,Analyst
4,11-1011.00,Chief Executives,2.A.1.c,Writing,IM,Importance,4.12,8,0.1250,3.8800,4.3700,0,1,08/2023,Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62575,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.b,Management of Financial Resources,LV,Level,1.12,8,0.1250,0.8800,1.3700,0,1,08/2019,Analyst
62576,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,IM,Importance,2.00,8,0.0000,2.0000,2.0000,0,1,08/2019,Analyst
62577,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,LV,Level,1.88,8,0.1250,1.6300,2.1200,0,1,08/2019,Analyst
62578,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,IM,Importance,2.88,8,0.1250,2.6300,3.1200,0,1,08/2019,Analyst
62579,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,LV,Level,2.75,8,0.1637,2.4292,3.0708,0,1,08/2019,Analyst

In [32]:
# Create combined column label
df_relevant_only["Skill_Scale"] = df_relevant_only["Element Name"] + " " + df_relevant_only["Scale Name"]

In [33]:
df_wide_rel = df_relevant_only.pivot_table(
    index=["O*NET-SOC Code", "Title"],
    columns="Skill_Scale",
    values="Data Value"
).reset_index()

In [34]:
df_wide_rel

Skill_Scale,O*NET-SOC Code,Title,Active Learning Importance,Active Learning Level,Active Listening Importance,Active Listening Level,Complex Problem Solving Importance,Complex Problem Solving Level,Coordination Importance,Coordination Level,...,Systems Evaluation Importance,Systems Evaluation Level,Technology Design Importance,Technology Design Level,Time Management Importance,Time Management Level,Troubleshooting Importance,Troubleshooting Level,Writing Importance,Writing Level
0,11-1011.00,Chief Executives,3.75,4.50,4.00,4.75,4.38,4.88,4.25,4.88,...,4.25,5.00,1.75,0.88,4.00,4.75,1.50,0.50,4.12,4.38
1,11-1011.03,Chief Sustainability Officers,3.75,3.88,4.00,4.00,4.00,4.12,3.75,3.88,...,3.88,4.00,1.88,1.12,3.38,3.88,1.00,NaN,4.12,4.25
2,11-1021.00,General and Operations Managers,3.62,3.75,4.00,4.12,3.62,3.88,3.88,4.00,...,3.12,3.25,1.50,0.62,3.62,3.88,1.75,1.00,3.50,3.88
3,11-2011.00,Advertising and Promotions Managers,3.25,4.12,4.12,4.12,3.50,3.88,3.50,4.12,...,3.12,3.75,1.75,0.75,3.50,3.88,1.00,NaN,3.75,3.88
4,11-2021.00,Marketing Managers,3.88,4.12,3.88,4.12,3.62,3.88,3.50,3.75,...,3.50,3.75,1.75,0.88,3.50,3.75,1.00,NaN,3.25,3.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,2.88,2.38,3.12,3.00,3.00,3.00,3.00,2.88,...,2.00,2.12,1.88,1.12,3.00,2.75,3.12,3.12,3.00,2.88
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",2.88,2.88,3.12,3.00,2.88,2.88,2.88,3.00,...,2.12,2.12,1.88,0.88,3.00,2.88,3.00,2.88,2.88,2.75
891,53-7073.00,Wellhead Pumpers,2.38,2.12,2.88,2.75,3.00,2.88,2.25,2.38,...,2.00,1.38,1.50,0.50,2.75,2.75,3.12,3.00,2.62,2.12
892,53-7081.00,Refuse and Recyclable Material Collectors,2.25,1.62,2.88,2.50,2.38,2.12,2.62,2.50,...,1.38,0.75,1.00,NaN,2.50,2.38,2.50,2.00,2.50,2.00
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.75,2.75,3.00,3.00,3.00,2.88,2.88,2.88,...,2.12,2.12,1.75,0.75,3.12,2.88,2.62,2.50,3.00,2.75

In [35]:
df_wide_rel.isnull().sum()

Skill_Scale
O*NET-SOC Code                   0
Title                            0
Active Learning Importance       0
Active Learning Level            0
Active Listening Importance      0
                              ...
Time Management Level            0
Troubleshooting Importance       0
Troubleshooting Level          188
Writing Importance               0
Writing Level                    0
Length: 72, dtype: int64

In [36]:
df_wide_rel.to_csv('transformed data/4-Skills Pivoted Relevant Only.csv', index=False)

# Supress should be separate thing?

# Pivot 2

In [15]:
df = df_skills.copy()

df["Skill_Scale"] = df["Element Name"] + " " + df["Scale Name"]

In [18]:
df_wide = df.pivot_table(
    index=["O*NET-SOC Code", "Title"],
    columns="Skill_Scale",
    values=["Data Value", "Recommend Suppress", "Not Relevant"],
    aggfunc="first"  # safer than pivot
)

In [19]:
df_wide.columns = [
    f"{skill} ({metric})"
    for metric, skill in df_wide.columns
]

df_wide = df_wide.reset_index()
df_wide

,O*NET-SOC Code,Title,Active Learning Importance (Data Value),Active Learning Level (Data Value),Active Listening Importance (Data Value),Active Listening Level (Data Value),Complex Problem Solving Importance (Data Value),Complex Problem Solving Level (Data Value),Coordination Importance (Data Value),Coordination Level (Data Value),...,Systems Evaluation Importance (Recommend Suppress),Systems Evaluation Level (Recommend Suppress),Technology Design Importance (Recommend Suppress),Technology Design Level (Recommend Suppress),Time Management Importance (Recommend Suppress),Time Management Level (Recommend Suppress),Troubleshooting Importance (Recommend Suppress),Troubleshooting Level (Recommend Suppress),Writing Importance (Recommend Suppress),Writing Level (Recommend Suppress)
0,11-1011.00,Chief Executives,3.75,4.50,4.00,4.75,4.38,4.88,4.25,4.88,...,N,N,N,N,N,N,N,N,N,N
1,11-1011.03,Chief Sustainability Officers,3.75,3.88,4.00,4.00,4.00,4.12,3.75,3.88,...,N,N,N,N,N,N,N,N,N,N
2,11-1021.00,General and Operations Managers,3.62,3.75,4.00,4.12,3.62,3.88,3.88,4.00,...,N,N,N,N,N,N,N,N,N,N
3,11-2011.00,Advertising and Promotions Managers,3.25,4.12,4.12,4.12,3.50,3.88,3.50,4.12,...,N,N,N,N,N,N,N,N,N,N
4,11-2021.00,Marketing Managers,3.88,4.12,3.88,4.12,3.62,3.88,3.50,3.75,...,N,N,N,N,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,2.88,2.38,3.12,3.00,3.00,3.00,3.00,2.88,...,N,N,N,N,N,N,N,N,N,N
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",2.88,2.88,3.12,3.00,2.88,2.88,2.88,3.00,...,N,N,N,N,N,N,N,N,N,N
891,53-7073.00,Wellhead Pumpers,2.38,2.12,2.88,2.75,3.00,2.88,2.25,2.38,...,N,N,N,N,N,N,N,N,N,N
892,53-7081.00,Refuse and Recyclable Material Collectors,2.25,1.62,2.88,2.50,2.38,2.12,2.62,2.50,...,N,N,N,N,N,N,N,N,N,N
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.75,2.75,3.00,3.00,3.00,2.88,2.88,2.88,...,N,N,N,N,N,N,N,N,N,N