At time of writing, I have absolutely no idea what I'm looking at. EDA is going to be fun.

In [ ]:
O*NET-SOC Code

Element ID

In [5]:
import pandas as pd

In [8]:
df1 = pd.read_csv('ONET data/Abilities to Work Activities.csv')
df1

,Abilities Element ID,Abilities Element Name,Work Activities Element ID,Work Activities Element Name
0,1.A.1.a.1,Oral Comprehension,4.A.1.a.1,Getting Information
1,1.A.1.a.1,Oral Comprehension,4.A.1.a.2,"Monitoring Processes, Materials, or Surroundings"
2,1.A.1.a.1,Oral Comprehension,4.A.1.b.1,"Identifying Objects, Actions, and Events"
3,1.A.1.a.1,Oral Comprehension,4.A.2.a.1,"Judging the Qualities of Objects, Services, or..."
4,1.A.1.a.1,Oral Comprehension,4.A.2.a.2,Processing Information
...,...,...,...,...
376,1.A.4.b.5,Speech Clarity,4.A.4.b.3,Training and Teaching Others
377,1.A.4.b.5,Speech Clarity,4.A.4.b.4,"Guiding, Directing, and Motivating Subordinates"
378,1.A.4.b.5,Speech Clarity,4.A.4.b.5,Coaching and Developing Others
379,1.A.4.b.5,Speech Clarity,4.A.4.b.6,Providing Consultation and Advice to Others
380,1.A.4.b.5,Speech Clarity,4.A.4.c.2,Staffing Organizational Units

In [15]:
df1['Abilities Element ID'].nunique()

50

In [10]:
df1['Work Activities Element Name'].nunique()

41

In [13]:
df1['Abilities Element Name'].nunique()

50

In [9]:
df2 = pd.read_csv('ONET data/Abilities to Work Context.csv')
df2

,Abilities Element ID,Abilities Element Name,Work Context Element ID,Work Context Element Name
0,1.A.1.a.1,Oral Comprehension,4.C.1.a.2.c,Public Speaking
1,1.A.1.a.1,Oral Comprehension,4.C.1.a.2.f,Telephone Conversations
2,1.A.1.a.1,Oral Comprehension,4.C.1.a.2.l,Face-to-Face Discussions with Individuals and ...
3,1.A.1.a.1,Oral Comprehension,4.C.1.a.4,Contact With Others
4,1.A.1.a.1,Oral Comprehension,4.C.1.b.1.e,Work With or Contribute to a Work Group or Team
...,...,...,...,...
134,1.A.4.b.5,Speech Clarity,4.C.1.c.1,Health and Safety of Other Workers
135,1.A.4.b.5,Speech Clarity,4.C.1.c.2,Work Outcomes and Results of Other Workers
136,1.A.4.b.5,Speech Clarity,4.C.1.d.1,Conflict Situations
137,1.A.4.b.5,Speech Clarity,4.C.1.d.2,"Dealing With Unpleasant, Angry, or Discourteou..."
138,1.A.4.b.5,Speech Clarity,4.C.1.d.3,Dealing with Violent or Physically Aggressive ...

In [12]:
df2['Work Context Element Name'].nunique()

36

In [16]:
df2['Abilities Element ID'].nunique()

33

Essential Files

File Contains
Occupation Data.txt Basic occupation information (title, description, code)
Task Statements.txt Specific tasks performed in each occupation
Skills.txt Skills required for each occupation with importance levels
Abilities.txt Abilities required with importance and level ratings
Work Activities.txt Generalized work activities with importance/level
Knowledge.txt Knowledge areas required
Work Context.txt Environmental and situational context
Tools and Technology.txt Software, equipment, and tools used

In [30]:
df_occupation_data = pd.read_csv('ONET data/Occupation Data.csv')
df_occupation_data

,O*NET-SOC Code,Title,Description
0,11-1011.00,Chief Executives,Determine and formulate policies and provide o...
1,11-1011.03,Chief Sustainability Officers,"Communicate and coordinate with management, sh..."
2,11-1021.00,General and Operations Managers,"Plan, direct, or coordinate the operations of ..."
3,11-1031.00,Legislators,"Develop, introduce, or enact laws and statutes..."
4,11-2011.00,Advertising and Promotions Managers,"Plan, direct, or coordinate advertising polici..."
...,...,...,...
1011,55-3014.00,Artillery and Missile Crew Members,"Target, fire, and maintain weapons used to des..."
1012,55-3015.00,Command and Control Center Specialists,"Operate and monitor communications, detection,..."
1013,55-3016.00,Infantry,Operate weapons and equipment in ground combat...
1014,55-3018.00,Special Forces,"Implement unconventional operations by air, la..."
1015,55-3019.00,Military Enlisted Tactical Operations and Air/...,All military enlisted tactical operations and ...

In [32]:
df_task_statements = pd.read_csv('ONET data/Task Statements.csv')
df_task_statements

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source
0,11-1011.00,Chief Executives,8823,Direct or coordinate an organization's financi...,Core,95.0,08/2023,Incumbent
1,11-1011.00,Chief Executives,8824,"Confer with board members, organization offici...",Core,95.0,08/2023,Incumbent
2,11-1011.00,Chief Executives,8827,"Prepare budgets for approval, including those ...",Core,95.0,08/2023,Incumbent
3,11-1011.00,Chief Executives,8826,"Direct, plan, or implement policies, objective...",Core,94.0,08/2023,Incumbent
4,11-1011.00,Chief Executives,8834,Prepare or present reports concerning activiti...,Core,95.0,08/2023,Incumbent
...,...,...,...,...,...,...,...,...
18791,53-7121.00,"Tank Car, Truck, and Ship Loaders",12807,Unload cars containing liquids by connecting h...,Supplemental,85.0,08/2019,Incumbent
18792,53-7121.00,"Tank Car, Truck, and Ship Loaders",12804,"Clean interiors of tank cars or tank trucks, u...",Supplemental,85.0,08/2019,Incumbent
18793,53-7121.00,"Tank Car, Truck, and Ship Loaders",12803,Lower gauge rods into tanks or read meters to ...,Supplemental,85.0,08/2019,Incumbent
18794,53-7121.00,"Tank Car, Truck, and Ship Loaders",12805,Operate conveyors and equipment to transfer gr...,Supplemental,85.0,08/2019,Incumbent
18795,53-7121.00,"Tank Car, Truck, and Ship Loaders",12810,"Perform general warehouse activities, such as ...",Supplemental,85.0,08/2019,Incumbent

In [33]:
df_skills = pd.read_csv('ONET data/Skills.csv')
df_skills

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,LV,Level,4.62,8,0.1830,4.2664,4.9836,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,2.A.1.b,Active Listening,IM,Importance,4.00,8,0.0000,4.0000,4.0000,N,NaN,08/2023,Analyst
3,11-1011.00,Chief Executives,2.A.1.b,Active Listening,LV,Level,4.75,8,0.1637,4.4292,5.0708,N,N,08/2023,Analyst
4,11-1011.00,Chief Executives,2.A.1.c,Writing,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62575,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.b,Management of Financial Resources,LV,Level,1.12,8,0.1250,0.8800,1.3700,N,N,08/2019,Analyst
62576,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,IM,Importance,2.00,8,0.0000,2.0000,2.0000,N,NaN,08/2019,Analyst
62577,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,LV,Level,1.88,8,0.1250,1.6300,2.1200,N,N,08/2019,Analyst
62578,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,IM,Importance,2.88,8,0.1250,2.6300,3.1200,N,NaN,08/2019,Analyst
62579,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,LV,Level,2.75,8,0.1637,2.4292,3.0708,N,N,08/2019,Analyst

In [35]:
df_abilities = pd.read_csv('ONET data/Abilities.csv')
df_abilities

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,1.A.1.a.1,Oral Comprehension,IM,Importance,4.62,8,0.1830,4.2664,4.9836,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,1.A.1.a.1,Oral Comprehension,LV,Level,4.88,8,0.1250,4.6300,5.1200,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,1.A.1.a.2,Written Comprehension,IM,Importance,4.25,8,0.1637,3.9292,4.5708,N,NaN,08/2023,Analyst
3,11-1011.00,Chief Executives,1.A.1.a.2,Written Comprehension,LV,Level,4.88,8,0.1250,4.6300,5.1200,N,N,08/2023,Analyst
4,11-1011.00,Chief Executives,1.A.1.a.3,Oral Expression,IM,Importance,4.50,8,0.1890,4.1296,4.8704,N,NaN,08/2023,Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92971,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.3,Sound Localization,LV,Level,2.00,8,0.0000,2.0000,2.0000,N,N,08/2019,Analyst
92972,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.4,Speech Recognition,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2019,Analyst
92973,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.4,Speech Recognition,LV,Level,2.75,8,0.1637,2.4292,3.0708,N,N,08/2019,Analyst
92974,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.5,Speech Clarity,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2019,Analyst
92975,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.5,Speech Clarity,LV,Level,2.88,8,0.1250,2.6300,3.1200,N,N,08/2019,Analyst

In [36]:
df_work_activities = pd.read_csv('ONET data/Work Activities.csv')
df_work_activities

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,4.A.1.a.1,Getting Information,IM,Importance,4.56,29.0,0.1559,4.2369,4.8756,N,NaN,08/2023,Incumbent
1,11-1011.00,Chief Executives,4.A.1.a.1,Getting Information,LV,Level,4.89,30.0,0.1727,4.5393,5.2458,N,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,4.A.1.a.2,"Monitoring Processes, Materials, or Surroundings",IM,Importance,4.25,30.0,0.2125,3.8130,4.6823,N,NaN,08/2023,Incumbent
3,11-1011.00,Chief Executives,4.A.1.a.2,"Monitoring Processes, Materials, or Surroundings",LV,Level,5.21,30.0,0.3872,4.4133,5.9971,N,N,08/2023,Incumbent
4,11-1011.00,Chief Executives,4.A.1.b.1,"Identifying Objects, Actions, and Events",IM,Importance,4.23,29.0,0.1544,3.9180,4.5507,N,NaN,08/2023,Incumbent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73303,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.1,Performing Administrative Activities,LV,Level,2.27,27.0,0.3184,1.6108,2.9197,N,N,08/2019,Incumbent
73304,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.2,Staffing Organizational Units,IM,Importance,1.93,27.0,0.2132,1.4962,2.3726,N,NaN,08/2019,Incumbent
73305,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.2,Staffing Organizational Units,LV,Level,1.60,27.0,0.2965,0.9936,2.2125,N,N,08/2019,Incumbent
73306,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.3,Monitoring and Controlling Resources,IM,Importance,2.56,27.0,0.2582,2.0266,3.0881,N,NaN,08/2019,Incumbent
73307,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.3,Monitoring and Controlling Resources,LV,Level,2.64,27.0,0.3350,1.9556,3.3329,N,N,08/2019,Incumbent

In [37]:
df_knowledge = pd.read_csv('ONET data/Knowledge.csv')
df_knowledge

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.C.1.a,Administration and Management,IM,Importance,4.78,28.0,0.1102,4.5564,5.0000,N,NaN,08/2023,Incumbent
1,11-1011.00,Chief Executives,2.C.1.a,Administration and Management,LV,Level,6.50,28.0,0.2130,6.0666,6.9409,N,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,2.C.1.b,Administrative,IM,Importance,2.42,28.0,0.4651,1.4662,3.3749,N,NaN,08/2023,Incumbent
3,11-1011.00,Chief Executives,2.C.1.b,Administrative,LV,Level,2.69,28.0,0.8678,0.9078,4.4690,N,N,08/2023,Incumbent
4,11-1011.00,Chief Executives,2.C.1.c,Economics and Accounting,IM,Importance,4.04,28.0,0.3480,3.3246,4.7526,N,NaN,08/2023,Incumbent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58999,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.9.a,Telecommunications,LV,Level,0.93,26.0,0.2603,0.3972,1.4693,N,N,08/2019,Incumbent
59000,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.9.b,Communications and Media,IM,Importance,1.67,26.0,0.2296,1.2006,2.1464,N,NaN,08/2019,Incumbent
59001,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.9.b,Communications and Media,LV,Level,1.23,26.0,0.4098,0.3845,2.0724,N,N,08/2019,Incumbent
59002,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.10,Transportation,IM,Importance,3.53,27.0,0.3248,2.8658,4.2009,N,NaN,08/2019,Incumbent
59003,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.10,Transportation,LV,Level,2.72,27.0,0.3687,1.9641,3.4800,N,N,08/2019,Incumbent

In [38]:
df_work_context = pd.read_csv('ONET data/Work Context.csv')
df_work_context

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Category,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CX,Context,NaN,3.07,37.0,0.2851,2.4923,3.6486,N,NaN,08/2023,Incumbent
1,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CXP,Context (Categories 1-5),1.0,0.13,37.0,0.1370,0.0160,1.0770,N,NaN,08/2023,Incumbent
2,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CXP,Context (Categories 1-5),2.0,39.49,37.0,11.0101,20.4073,62.4299,N,NaN,08/2023,Incumbent
3,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CXP,Context (Categories 1-5),3.0,33.07,37.0,7.1359,20.4456,48.7245,N,NaN,08/2023,Incumbent
4,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CXP,Context (Categories 1-5),4.0,7.79,37.0,4.3613,2.4093,22.4457,N,NaN,08/2023,Incumbent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297671,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.4,Work Schedules,CTP,Context (Categories 1-3),3.0,0.89,32.0,0.9750,0.0947,7.8674,N,NaN,08/2019,Incumbent
297672,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.8,Duration of Typical Work Week,CT,Context,NaN,2.82,32.0,0.0983,2.6238,3.0000,N,NaN,08/2019,Incumbent
297673,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.8,Duration of Typical Work Week,CTP,Context (Categories 1-3),1.0,0.00,32.0,0.0000,NaN,NaN,N,NaN,08/2019,Incumbent
297674,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.8,Duration of Typical Work Week,CTP,Context (Categories 1-3),2.0,17.56,32.0,9.8350,5.0617,45.9881,N,NaN,08/2019,Incumbent
297675,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.8,Duration of Typical Work Week,CTP,Context (Categories 1-3),3.0,82.44,32.0,9.8350,54.0119,94.9383,N,NaN,08/2019,Incumbent

In [41]:
df_tools = pd.read_csv('ONET data/Tools Used.csv')
df_tools

,O*NET-SOC Code,Title,Example,Commodity Code,Commodity Title
0,11-1011.00,Chief Executives,10-key calculators,44101809,Desktop calculator
1,11-1011.00,Chief Executives,Desktop computers,43211507,Desktop computer
2,11-1011.00,Chief Executives,Laptop computers,43211503,Notebook computer
3,11-1011.00,Chief Executives,Personal computers,43211508,Personal computer
4,11-1011.00,Chief Executives,Personal digital assistants PDA,43211504,Personal digital assistant PDAs or organizer
...,...,...,...,...,...
41657,53-7121.00,"Tank Car, Truck, and Ship Loaders",Stock pickers,24101605,Loading equipment
41658,53-7121.00,"Tank Car, Truck, and Ship Loaders",Tablet computers,43211509,Tablet computer
41659,53-7121.00,"Tank Car, Truck, and Ship Loaders",Walk behind pallet jacks,24101505,Pallet trucks
41660,53-7121.00,"Tank Car, Truck, and Ship Loaders",Warehouse forklifts,24101603,Forklifts
41661,53-7121.00,"Tank Car, Truck, and Ship Loaders",Wheeled front end loaders,22101501,Front end loaders

In [42]:
df_technology = pd.read_csv('ONET data/Technology Skills.csv')
df_technology

,O*NET-SOC Code,Title,Example,Commodity Code,Commodity Title,Hot Technology,In Demand
0,11-1011.00,Chief Executives,Adobe Acrobat,43232202,Document management software,Y,N
1,11-1011.00,Chief Executives,AdSense Tracker,43232306,Data base user interface and query software,N,N
2,11-1011.00,Chief Executives,Atlassian JIRA,43232201,Content workflow software,Y,N
3,11-1011.00,Chief Executives,Blackbaud The Raiser's Edge,43232303,Customer relationship management CRM software,N,N
4,11-1011.00,Chief Executives,ComputerEase construction accounting software,43231601,Accounting software,N,N
...,...,...,...,...,...,...,...
32768,53-7121.00,"Tank Car, Truck, and Ship Loaders",Linux,43233004,Operating system software,Y,N
32769,53-7121.00,"Tank Car, Truck, and Ship Loaders",Microsoft Excel,43232110,Spreadsheet software,Y,N
32770,53-7121.00,"Tank Car, Truck, and Ship Loaders",Microsoft Office software,43231513,Office suite software,Y,N
32771,53-7121.00,"Tank Car, Truck, and Ship Loaders",SAP software,43231602,Enterprise resource planning ERP software,Y,N
32772,53-7121.00,"Tank Car, Truck, and Ship Loaders",Warehouse management system WMS,43231506,Materials requirements planning logistics and ...,N,N