In [1]:
import pandas as pd

In [25]:
jobs_agg_tech_skills = pd.read_csv('transformed data/1-1-Jobs Agg Tech Skills.csv')
jobs_agg_tech_skills

,O*NET-SOC Code,Job Title,TOTAL_TECH_SKILLS,TOTAL_TECH_TYPES,TECH_SKILLS_LIST,TECH_TYPES_LIST,PCT_HOT_TECH,NUM_HOT_TECH,PCT_IN_DEMAND_TECH,NUM_IN_DEMAND_TECH
0,15-1252.00,Software Developers,429,67,"""3M Post-it App""; ""A programming language APL""...","""Access software""; ""Administration software""; ...",34.498834,148,7.692308,33
1,15-1253.00,Software Quality Assurance Analysts and Testers,428,68,"""3M Post-it App""; ""A programming language APL""...","""Access software""; ""Accounting software""; ""Adm...",28.971963,124,5.140187,22
2,15-1299.09,Information Technology Project Managers,334,62,"""24SevenOffice Project""; ""3M Post-it App""; ""AE...","""Access software""; ""Accounting software""; ""Ana...",36.227545,121,2.694611,9
3,15-1243.00,Database Architects,324,59,"""3M Post-it App""; ""ADO.NET""; ""AJAX""; ""ASG Tech...","""Access software""; ""Administration software""; ...",34.567901,112,4.012346,13
4,15-1211.00,Computer Systems Analysts,313,68,"""3M Post-it App""; ""ADP Workforce Now""; ""AJAX"";...","""Access software""; ""Accounting software""; ""Adm...",38.019169,119,3.514377,11
...,...,...,...,...,...,...,...,...,...,...
918,35-9021.00,Dishwashers,2,2,"""Facebook""; ""Microsoft Windows""","""Operating system software""; ""Web page creatio...",100.000000,2,0.000000,0
919,53-7041.00,Hoist and Winch Operators,2,2,"""Microsoft Excel""; ""Microsoft Word""","""Spreadsheet software""; ""Word processing softw...",100.000000,2,0.000000,0
920,53-4041.00,Subway and Streetcar Operators,2,2,"""Microsoft Office software""; ""Word processing ...","""Office suite software""; ""Word processing soft...",50.000000,1,0.000000,0
921,51-4023.00,"Rolling Machine Setters, Operators, and Tender...",2,2,"""Email software""; ""Web browser software""","""Electronic mail software""; ""Internet browser ...",0.000000,0,0.000000,0
922,51-3093.00,Food Cooking Machine Operators and Tenders,1,1,"""Database software""","""Data base user interface and query software""",0.000000,0,0.000000,0

# Starting Over

In [26]:
skills = jobs_agg_tech_skills.copy()

# Count how many unique jobs use each skill
jobs_per_skill = (
    skills.groupby("Tech Skill Title")["Job Title"]
          .nunique()
          .reset_index(name="JOBS_PER_SKILL")
)

skills = skills.merge(jobs_per_skill, on="Tech Skill Title", how="left")

KeyError: 'Tech Skill Title'

# Jobs and Tech

In [3]:
jobs_agg_tech = pd.read_csv('transformed data/1-1-Jobs Agg Tech Skills.csv')
jobs_agg_tech

,O*NET-SOC Code,Job Title,TOTAL_TECH_SKILLS,TOTAL_TECH_TYPES,TECH_SKILLS_LIST,TECH_TYPES_LIST,PCT_HOT_TECH,NUM_HOT_TECH,PCT_IN_DEMAND_TECH,NUM_IN_DEMAND_TECH
0,15-1252.00,Software Developers,429,67,"""3M Post-it App""; ""A programming language APL""...","""Access software""; ""Administration software""; ...",34.498834,148,7.692308,33
1,15-1253.00,Software Quality Assurance Analysts and Testers,428,68,"""3M Post-it App""; ""A programming language APL""...","""Access software""; ""Accounting software""; ""Adm...",28.971963,124,5.140187,22
2,15-1299.09,Information Technology Project Managers,334,62,"""24SevenOffice Project""; ""3M Post-it App""; ""AE...","""Access software""; ""Accounting software""; ""Ana...",36.227545,121,2.694611,9
3,15-1243.00,Database Architects,324,59,"""3M Post-it App""; ""ADO.NET""; ""AJAX""; ""ASG Tech...","""Access software""; ""Administration software""; ...",34.567901,112,4.012346,13
4,15-1211.00,Computer Systems Analysts,313,68,"""3M Post-it App""; ""ADP Workforce Now""; ""AJAX"";...","""Access software""; ""Accounting software""; ""Adm...",38.019169,119,3.514377,11
...,...,...,...,...,...,...,...,...,...,...
918,35-9021.00,Dishwashers,2,2,"""Facebook""; ""Microsoft Windows""","""Operating system software""; ""Web page creatio...",100.000000,2,0.000000,0
919,53-7041.00,Hoist and Winch Operators,2,2,"""Microsoft Excel""; ""Microsoft Word""","""Spreadsheet software""; ""Word processing softw...",100.000000,2,0.000000,0
920,53-4041.00,Subway and Streetcar Operators,2,2,"""Microsoft Office software""; ""Word processing ...","""Office suite software""; ""Word processing soft...",50.000000,1,0.000000,0
921,51-4023.00,"Rolling Machine Setters, Operators, and Tender...",2,2,"""Email software""; ""Web browser software""","""Electronic mail software""; ""Internet browser ...",0.000000,0,0.000000,0
922,51-3093.00,Food Cooking Machine Operators and Tenders,1,1,"""Database software""","""Data base user interface and query software""",0.000000,0,0.000000,0

# Jobs and Tech

In [5]:
tech_agg_jobs = pd.read_csv('transformed data/1-1-Tech Skills Agg Jobs.csv')
tech_agg_jobs['TECH_SKILL_UNIQUENESS_RANK'] = tech_agg_jobs['TOTAL_JOBS_PER_TECH_SKILL'].rank(ascending=True)
tech_agg_jobs['UNIQUENESS_INV'] = 1 / tech_agg_jobs['TOTAL_JOBS_PER_TECH_SKILL']
tech_agg_jobs

,Tech Skill Title,Tech Type Title,Tech Type Code,Hot Technology,In Demand,TOTAL_JOBS_PER_TECH_SKILL,TOTAL_JOBS_PER_TECH_TYPE,JOB_TITLE_LIST,TECH_SKILL_UNIQUENESS_RANK,UNIQUENESS_INV
0,Adobe Acrobat,Document management software,43232202,1,0,165,293,"""Accountants and Auditors""; ""Administrative La...",8770.0,0.006061
1,AdSense Tracker,Data base user interface and query software,43232306,0,0,2,632,"""Chief Executives""; ""Marketing Managers""",6839.5,0.500000
2,Atlassian JIRA,Content workflow software,43232201,1,0,53,46,"""Administrative Services Managers""; ""Aerospace...",8706.5,0.018868
3,Blackbaud The Raiser's Edge,Customer relationship management CRM software,43232303,0,0,44,155,"""Accountants and Auditors""; ""Administrative Se...",8677.5,0.022727
4,ComputerEase construction accounting software,Accounting software,43231601,0,0,3,178,"""Bookkeeping, Accounting, and Auditing Clerks""...",7715.0,0.333333
...,...,...,...,...,...,...,...,...,...,...
8780,AMCS Platform,Analytical or scientific software,43232605,0,0,1,372,"""Refuse and Recyclable Material Collectors""",3073.0,1.000000
8781,Dossier software,Data base user interface and query software,43232306,0,0,1,632,"""Refuse and Recyclable Material Collectors""",3073.0,1.000000
8782,Mileage logging software,Data base user interface and query software,43232306,0,0,1,632,"""Refuse and Recyclable Material Collectors""",3073.0,1.000000
8783,Routeware software,Map creation software,43233506,0,0,1,87,"""Refuse and Recyclable Material Collectors""",3073.0,1.000000
8784,CompuWeigh GMS,Data base user interface and query software,43232306,0,0,1,632,"""Tank Car, Truck, and Ship Loaders""",3073.0,1.000000

In [6]:
# import numpy as np


# df = tech_agg_jobs.copy()

# df["UNIQUENESS_WITHIN_TYPE_01"] = 1 - (
#     df["TOTAL_JOBS_PER_TECH_SKILL"] /
#     df["TOTAL_JOBS_PER_TECH_TYPE"]
# )

# df

In [7]:
tech_agg_jobs.columns

Index(['Tech Skill Title', 'Tech Type Title', 'Tech Type Code',
       'Hot Technology', 'In Demand', 'TOTAL_JOBS_PER_TECH_SKILL',
       'TOTAL_JOBS_PER_TECH_TYPE', 'JOB_TITLE_LIST',
       'TECH_SKILL_UNIQUENESS_RANK', 'UNIQUENESS_INV'],
      dtype='object')

# Doing everything again?

# Average uniqueness

In [10]:
import pandas as pd
import numpy as np

df = tech_agg_jobs.copy()

# --- Skill uniqueness within type (0–1) ---
# 1 - (jobs mentioning this skill) / (jobs mentioning this type)
# +1 smoothing is optional but helps when counts are tiny
df["UNIQUENESS_WITHIN_TYPE_01"] = 1 - (
    (df["TOTAL_JOBS_PER_TECH_SKILL"] + 1) /
    (df["TOTAL_JOBS_PER_TECH_TYPE"] + 1)
)

# --- Parse + explode job title list ---
df["JOB_TITLE_LIST_PARSED"] = (
    df["JOB_TITLE_LIST"]
      .fillna("")
      .astype(str)
      .str.replace('"', '', regex=False)
      .str.split(r"\s*;\s*", regex=True)
)

job_skill = df.explode("JOB_TITLE_LIST_PARSED").rename(
    columns={"JOB_TITLE_LIST_PARSED": "Job Title"}
)

job_skill["Job Title"] = job_skill["Job Title"].str.strip()
job_skill = job_skill[job_skill["Job Title"].ne("")]

# OPTIONAL (recommended): if duplicates exist, prevent double-counting
# job_skill = job_skill.drop_duplicates(subset=["Job Title", "Tech Skill Title"])

# --- Aggregate to job level ---
job_uniqueness = (
    job_skill.groupby("Job Title", as_index=False)
    .agg(
        AVG_TECH_SKILL_UNIQUENESS_BY_JOB=("UNIQUENESS_INV", "mean"),
        AVG_TECH_SKILL_UNIQUENESS_BY_SKILL_TYPE=("UNIQUENESS_WITHIN_TYPE_01", "mean"),
        NUM_TECH_SKILLS=("Tech Skill Title", "nunique"),
        NUM_TECH_TYPES=("Tech Type Title", "nunique"),
    )
    .sort_values("AVG_TECH_SKILL_UNIQUENESS_BY_JOB", ascending=False)
)

job_uniqueness

,Job Title,AVG_TECH_SKILL_UNIQUENESS_BY_JOB,AVG_TECH_SKILL_UNIQUENESS_BY_SKILL_TYPE,NUM_TECH_SKILLS,NUM_TECH_TYPES
582,Musical Instrument Repairers and Tuners,1.000000,0.994638,10,1
761,"Roof Bolters, Mining",1.000000,0.990188,2,2
123,Cement Masons and Concrete Finishers,0.933333,0.992094,10,4
580,Music Directors and Composers,0.886508,0.863068,86,9
151,"Coil Winders, Tapers, and Finishers",0.833333,0.989845,3,3
...,...,...,...,...,...
212,"Cutters and Trimmers, Hand",0.001332,0.051175,3,3
428,"Helpers--Pipelayers, Plumbers, Pipefitters, an...",0.001221,0.009462,3,3
436,Hoist and Winch Operators,0.001220,0.013582,2,2
408,"Grinding and Polishing Workers, Hand",0.001220,0.013582,2,2
141,"Cleaning, Washing, and Metal Pickling Equipmen...",0.001220,0.013582,2,2

In [12]:
job_uniqueness.to_csv('transformed data/2-Skill Uniqueness by Job.csv', index=False)

In [14]:
job_uniqueness.columns

Index(['Job Title', 'AVG_TECH_SKILL_UNIQUENESS_BY_JOB',
       'AVG_TECH_SKILL_UNIQUENESS_BY_SKILL_TYPE', 'NUM_TECH_SKILLS',
       'NUM_TECH_TYPES'],
      dtype='object')

# Jobs and Tools

In [13]:
jobs_agg_tools = pd.read_csv('transformed data/1-2-Jobs Agg Tools.csv')
jobs_agg_tools

,O*NET-SOC Code,Job Title,Tool Name,Tool Type Code,Tool Type Title,TOTAL_TOOLS_BY_JOB,TOTAL_TOOL_TYPES_BY_JOB,TOOLS_LIST,TOOL_TYPES_LIST
0,11-1011.00,Chief Executives,10-key calculators,44101809,Desktop calculator,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
1,11-1011.00,Chief Executives,Desktop computers,43211507,Desktop computer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
2,11-1011.00,Chief Executives,Laptop computers,43211503,Notebook computer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
3,11-1011.00,Chief Executives,Personal computers,43211508,Personal computer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
4,11-1011.00,Chief Executives,Personal digital assistants PDA,43211504,Personal digital assistant PDAs or organizer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
...,...,...,...,...,...,...,...,...,...
41657,53-7121.00,"Tank Car, Truck, and Ship Loaders",Stock pickers,24101605,Loading equipment,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."
41658,53-7121.00,"Tank Car, Truck, and Ship Loaders",Tablet computers,43211509,Tablet computer,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."
41659,53-7121.00,"Tank Car, Truck, and Ship Loaders",Walk behind pallet jacks,24101505,Pallet trucks,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."
41660,53-7121.00,"Tank Car, Truck, and Ship Loaders",Warehouse forklifts,24101603,Forklifts,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."
41661,53-7121.00,"Tank Car, Truck, and Ship Loaders",Wheeled front end loaders,22101501,Front end loaders,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."

In [15]:
jobs_agg_tools.columns

Index(['O*NET-SOC Code', 'Job Title', 'Tool Name', 'Tool Type Code',
       'Tool Type Title', 'TOTAL_TOOLS_BY_JOB', 'TOTAL_TOOL_TYPES_BY_JOB',
       'TOOLS_LIST', 'TOOL_TYPES_LIST'],
      dtype='object')

In [18]:
tools = jobs_agg_tools.copy()

# Jobs per tool
jobs_per_tool = (
    tools.groupby("Tool Name")["Job Title"]
         .nunique()
         .reset_index(name="JOBS_PER_TOOL")
)

# Jobs per tool type
jobs_per_tool_type = (
    tools.groupby("Tool Type Title")["Job Title"]
         .nunique()
         .reset_index(name="JOBS_PER_TOOL_TYPE")
)

# Merge back
tools = tools.merge(jobs_per_tool, on="Tool Name", how="left")
tools = tools.merge(jobs_per_tool_type, on="Tool Type Title", how="left")

In [19]:
tools

,O*NET-SOC Code,Job Title,Tool Name,Tool Type Code,Tool Type Title,TOTAL_TOOLS_BY_JOB,TOTAL_TOOL_TYPES_BY_JOB,TOOLS_LIST,TOOL_TYPES_LIST,JOBS_PER_TOOL,JOBS_PER_TOOL_TYPE
0,11-1011.00,Chief Executives,10-key calculators,44101809,Desktop calculator,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig...",64,72
1,11-1011.00,Chief Executives,Desktop computers,43211507,Desktop computer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig...",570,572
2,11-1011.00,Chief Executives,Laptop computers,43211503,Notebook computer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig...",425,555
3,11-1011.00,Chief Executives,Personal computers,43211508,Personal computer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig...",656,658
4,11-1011.00,Chief Executives,Personal digital assistants PDA,43211504,Personal digital assistant PDAs or organizer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig...",86,90
...,...,...,...,...,...,...,...,...,...,...,...
41657,53-7121.00,"Tank Car, Truck, and Ship Loaders",Stock pickers,24101605,Loading equipment,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ...",1,14
41658,53-7121.00,"Tank Car, Truck, and Ship Loaders",Tablet computers,43211509,Tablet computer,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ...",227,233
41659,53-7121.00,"Tank Car, Truck, and Ship Loaders",Walk behind pallet jacks,24101505,Pallet trucks,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ...",1,40
41660,53-7121.00,"Tank Car, Truck, and Ship Loaders",Warehouse forklifts,24101603,Forklifts,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ...",7,130
41661,53-7121.00,"Tank Car, Truck, and Ship Loaders",Wheeled front end loaders,22101501,Front end loaders,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ...",6,24

In [16]:
import pandas as pd
import numpy as np

tools = jobs_agg_tools.copy()

# --- 1) Global tool uniqueness (inverse frequency across jobs) ---
# If TOTAL_TOOLS_BY_JOB actually means "jobs per tool", rename mentally.
# This metric needs: TOTAL_JOBS_PER_TOOL (how many jobs use this tool).
# I'm assuming your column TOTAL_TOOLS_BY_JOB is that value (despite the name).
tools["TOOL_UNIQUENESS_INV"] = 1 / tools["TOTAL_TOOLS_BY_JOB"]

# --- 2) Tool uniqueness within tool type (0–1) ---
# Needs: jobs-per-tool-type baseline vs jobs-per-tool.
# I'm assuming TOTAL_TOOL_TYPES_BY_JOB is "jobs per tool type" (despite the name).
tools["TOOL_UNIQUENESS_WITHIN_TYPE_01"] = 1 - (
    (tools["TOTAL_TOOLS_BY_JOB"] + 1) /
    (tools["TOTAL_TOOL_TYPES_BY_JOB"] + 1)
)

# OPTIONAL (recommended): prevent double counting if duplicates exist
# tools = tools.drop_duplicates(subset=["Job Title", "Tool Name"])

# --- 3) Aggregate to job level ---
job_tool_uniqueness = (
    tools.groupby("Job Title", as_index=False)
    .agg(
        AVG_TOOL_UNIQUENESS_BY_JOB=("TOOL_UNIQUENESS_INV", "mean"),
        AVG_TOOL_UNIQUENESS_BY_TOOL_TYPE=("TOOL_UNIQUENESS_WITHIN_TYPE_01", "mean"),
        NUM_TOOLS=("Tool Name", "nunique"),
        NUM_TOOL_TYPES=("Tool Type Title", "nunique"),
    )
    .sort_values("AVG_TOOL_UNIQUENESS_BY_JOB", ascending=False)
)

job_tool_uniqueness

,Job Title,AVG_TOOL_UNIQUENESS_BY_JOB,AVG_TOOL_UNIQUENESS_BY_TOOL_TYPE,NUM_TOOLS,NUM_TOOL_TYPES
808,Statisticians,0.333333,0.000000,3,3
829,Tax Preparers,0.333333,0.000000,3,3
281,Epidemiologists,0.333333,0.000000,3,3
538,Mental Health and Substance Abuse Social Workers,0.333333,0.000000,3,3
577,New Accounts Clerks,0.333333,0.000000,3,3
...,...,...,...,...,...
408,"Heating, Air Conditioning, and Refrigeration M...",0.003861,-0.460674,259,177
193,Craft Artists,0.003788,-0.558824,264,169
662,"Plumbers, Pipefitters, and Steamfitters",0.003597,-0.847682,278,150
62,Automotive Service Technicians and Mechanics,0.003484,-0.664740,287,172
338,Fishing and Hunting Workers,0.003030,-1.018293,330,163

In [17]:
jobs_agg_tools.groupby("Tool Name")["TOTAL_TOOLS_BY_JOB"].nunique().value_counts().head()

TOTAL_TOOLS_BY_JOB
1    12692
2     2678
3      950
4      555
5      284
Name: count, dtype: int64

# Jobs and Tasks