In [1]:
import pandas as pd

df_occupation_data = pd.read_csv('ONET data/Occupation Data.csv')
df_task_statements = pd.read_csv('ONET data/Task Statements.csv')
df_skills = pd.read_csv('ONET data/Skills.csv')
df_abilities = pd.read_csv('ONET data/Abilities.csv')
df_work_activities = pd.read_csv('ONET data/Work Activities.csv')
df_knowledge = pd.read_csv('ONET data/Knowledge.csv')
df_work_context = pd.read_csv('ONET data/Work Context.csv')
df_tools_used = pd.read_csv('ONET data/Tools Used.csv')
df_technology_skills = pd.read_csv('ONET data/Technology Skills.csv')

dfs = {
    "occupation_data": df_occupation_data,
    "task_statements": df_task_statements,
    "skills": df_skills,
    "abilities": df_abilities,
    "work_activities": df_work_activities,
    "knowledge": df_knowledge,
    "work_context": df_work_context,
    "tools_used": df_tools_used,
    "technology_skills": df_technology_skills
}

# Tools Aggregates

In [2]:
df_tools_used

,O*NET-SOC Code,Title,Example,Commodity Code,Commodity Title
0,11-1011.00,Chief Executives,10-key calculators,44101809,Desktop calculator
1,11-1011.00,Chief Executives,Desktop computers,43211507,Desktop computer
2,11-1011.00,Chief Executives,Laptop computers,43211503,Notebook computer
3,11-1011.00,Chief Executives,Personal computers,43211508,Personal computer
4,11-1011.00,Chief Executives,Personal digital assistants PDA,43211504,Personal digital assistant PDAs or organizer
...,...,...,...,...,...
41657,53-7121.00,"Tank Car, Truck, and Ship Loaders",Stock pickers,24101605,Loading equipment
41658,53-7121.00,"Tank Car, Truck, and Ship Loaders",Tablet computers,43211509,Tablet computer
41659,53-7121.00,"Tank Car, Truck, and Ship Loaders",Walk behind pallet jacks,24101505,Pallet trucks
41660,53-7121.00,"Tank Car, Truck, and Ship Loaders",Warehouse forklifts,24101603,Forklifts
41661,53-7121.00,"Tank Car, Truck, and Ship Loaders",Wheeled front end loaders,22101501,Front end loaders

In [3]:
df_tools_used['Commodity Code'].nunique()

4127

In [4]:
df_tools_used['Commodity Title'].nunique()

4126

In [5]:
df_tools_used.columns

Index(['O*NET-SOC Code', 'Title', 'Example', 'Commodity Code',
       'Commodity Title'],
      dtype='object')

In [6]:
code_title_counts = (
    df_tools_used
    .groupby('Commodity Code')['Commodity Title']
    .nunique()
    .reset_index(name='num_unique_titles')
)

code_title_counts['num_unique_titles'].value_counts()

num_unique_titles
1    4127
Name: count, dtype: int64

In [7]:
title_code_counts = (
    df_tools_used
    .groupby('Commodity Title')['Commodity Code']
    .nunique()
    .reset_index(name='num_unique_codes')
)

#title_code_counts.sort_values('num_unique_codes', ascending=False).head()
title_code_counts[title_code_counts['num_unique_codes'] > 1]

                    Commodity Title  num_unique_codes
1471  Freeze dryers or lyophilizers                 2

In [8]:
df_tools_used[df_tools_used['Commodity Title'] == 'Freeze dryers or lyophilizers']

,O*NET-SOC Code,Title,Example,Commodity Code,Commodity Title
2019,17-2031.00,Bioengineers and Biomedical Engineers,Freeze dryers,41104701,Freeze dryers or lyophilizers
2166,17-2041.00,Chemical Engineers,Lyophilizers,23151807,Freeze dryers or lyophilizers
2414,17-2081.00,Environmental Engineers,Freeze dryers,41104701,Freeze dryers or lyophilizers
3998,17-3025.00,Environmental Engineering Technologists and Te...,Freeze dryers,41104701,Freeze dryers or lyophilizers
4838,19-1011.00,Animal Scientists,Freeze dryers,41104701,Freeze dryers or lyophilizers
4930,19-1012.00,Food Scientists and Technologists,Freeze drying equipment,41104701,Freeze dryers or lyophilizers
5122,19-1021.00,Biochemists and Biophysicists,Flexi-dry lyophilizers,41104701,Freeze dryers or lyophilizers
5126,19-1021.00,Biochemists and Biophysicists,Freeze dryers,41104701,Freeze dryers or lyophilizers
5234,19-1021.00,Biochemists and Biophysicists,Vacuum freezers,41104701,Freeze dryers or lyophilizers
5295,19-1022.00,Microbiologists,Freeze dryers,41104701,Freeze dryers or lyophilizers
5595,19-1029.04,Biologists,Benchtop lyophilizers,23151807,Freeze dryers or lyophilizers
6139,19-2031.00,Chemists,Benchtop lyophilizers,23151807,Freeze dryers or lyophilizers
6176,19-2031.00,Chemists,Freeze dryers,41104701,Freeze dryers or lyophilizers
6326,19-2032.00,Materials Scientists,Freeze dryers,41104701,Freeze dryers or lyophilizers
7012,19-3091.00,Anthropologists and Archeologists,Vacuum freeze-drying chambers,41104701,Freeze dryers or lyophilizers
7515,19-4031.00,Chemical Technicians,Lyophilizers,23151807,Freeze dryers or lyophilizers

In [9]:
df_tools_used[df_tools_used['Commodity Code'] == 23151807]

,O*NET-SOC Code,Title,Example,Commodity Code,Commodity Title
2166,17-2041.00,Chemical Engineers,Lyophilizers,23151807,Freeze dryers or lyophilizers
5595,19-1029.04,Biologists,Benchtop lyophilizers,23151807,Freeze dryers or lyophilizers
6139,19-2031.00,Chemists,Benchtop lyophilizers,23151807,Freeze dryers or lyophilizers
7515,19-4031.00,Chemical Technicians,Lyophilizers,23151807,Freeze dryers or lyophilizers

In [10]:
df_tools_used['Commodity Code'] = df_tools_used['Commodity Code'].replace(23151807, 41104701)

In [11]:
df_tools_used[df_tools_used['Commodity Title'] == 'Freeze dryers or lyophilizers']

,O*NET-SOC Code,Title,Example,Commodity Code,Commodity Title
2019,17-2031.00,Bioengineers and Biomedical Engineers,Freeze dryers,41104701,Freeze dryers or lyophilizers
2166,17-2041.00,Chemical Engineers,Lyophilizers,41104701,Freeze dryers or lyophilizers
2414,17-2081.00,Environmental Engineers,Freeze dryers,41104701,Freeze dryers or lyophilizers
3998,17-3025.00,Environmental Engineering Technologists and Te...,Freeze dryers,41104701,Freeze dryers or lyophilizers
4838,19-1011.00,Animal Scientists,Freeze dryers,41104701,Freeze dryers or lyophilizers
4930,19-1012.00,Food Scientists and Technologists,Freeze drying equipment,41104701,Freeze dryers or lyophilizers
5122,19-1021.00,Biochemists and Biophysicists,Flexi-dry lyophilizers,41104701,Freeze dryers or lyophilizers
5126,19-1021.00,Biochemists and Biophysicists,Freeze dryers,41104701,Freeze dryers or lyophilizers
5234,19-1021.00,Biochemists and Biophysicists,Vacuum freezers,41104701,Freeze dryers or lyophilizers
5295,19-1022.00,Microbiologists,Freeze dryers,41104701,Freeze dryers or lyophilizers
5595,19-1029.04,Biologists,Benchtop lyophilizers,41104701,Freeze dryers or lyophilizers
6139,19-2031.00,Chemists,Benchtop lyophilizers,41104701,Freeze dryers or lyophilizers
6176,19-2031.00,Chemists,Freeze dryers,41104701,Freeze dryers or lyophilizers
6326,19-2032.00,Materials Scientists,Freeze dryers,41104701,Freeze dryers or lyophilizers
7012,19-3091.00,Anthropologists and Archeologists,Vacuum freeze-drying chambers,41104701,Freeze dryers or lyophilizers
7515,19-4031.00,Chemical Technicians,Lyophilizers,41104701,Freeze dryers or lyophilizers

In [12]:
title_code_counts = (
    df_tools_used
    .groupby('Commodity Title')['Commodity Code']
    .nunique()
    .reset_index(name='num_unique_codes')
)

#title_code_counts.sort_values('num_unique_codes', ascending=False).head()
title_code_counts[title_code_counts['num_unique_codes'] > 1]

Empty DataFrame
Columns: [Commodity Title, num_unique_codes]
Index: []

# Mismatch Fixed. Now we can move on to...

# Aggregates

In [13]:
# Reset DF definition
df_tools_used = pd.read_csv('ONET data/Tools Used.csv')
df_tools_used['Commodity Code'] = df_tools_used['Commodity Code'].replace(23151807, 41104701)

In [14]:
df_tools_used

,O*NET-SOC Code,Title,Example,Commodity Code,Commodity Title
0,11-1011.00,Chief Executives,10-key calculators,44101809,Desktop calculator
1,11-1011.00,Chief Executives,Desktop computers,43211507,Desktop computer
2,11-1011.00,Chief Executives,Laptop computers,43211503,Notebook computer
3,11-1011.00,Chief Executives,Personal computers,43211508,Personal computer
4,11-1011.00,Chief Executives,Personal digital assistants PDA,43211504,Personal digital assistant PDAs or organizer
...,...,...,...,...,...
41657,53-7121.00,"Tank Car, Truck, and Ship Loaders",Stock pickers,24101605,Loading equipment
41658,53-7121.00,"Tank Car, Truck, and Ship Loaders",Tablet computers,43211509,Tablet computer
41659,53-7121.00,"Tank Car, Truck, and Ship Loaders",Walk behind pallet jacks,24101505,Pallet trucks
41660,53-7121.00,"Tank Car, Truck, and Ship Loaders",Warehouse forklifts,24101603,Forklifts
41661,53-7121.00,"Tank Car, Truck, and Ship Loaders",Wheeled front end loaders,22101501,Front end loaders

In [21]:
# Find count of unique tools by title
total_tools_by_title = (
    df_tools_used
    .groupby(['O*NET-SOC Code', 'Title'])['Example']
    .nunique()
    .reset_index(name='TOTAL_TOOLS_BY_JOB')
    .sort_values('TOTAL_TOOLS_BY_JOB', ascending=False)
)

# Find count of unique tool types by title
total_tool_types_by_title = (
    df_tools_used
    .groupby(['Title'])['Commodity Title']
    .nunique()
    .reset_index(name='TOTAL_TOOL_TYPES_BY_JOB')
    .sort_values('TOTAL_TOOL_TYPES_BY_JOB', ascending=False)
)

# Create column list of all tools by title
tools_by_title = (
    df_tools_used
    .groupby('Title')['Example']
    .apply(lambda x: '; '.join(
        f'"{e}"' for e in sorted(x.unique())
    ))
    .reset_index(name='TOOLS_LIST')
)

# Create column list of all tool types by title
tool_types_by_title = (
    df_tools_used
    .groupby('Title')['Commodity Title']
    .apply(lambda x: '; '.join(
        f'"{e}"' for e in sorted(x.unique())
    ))
    .reset_index(name='TOOL_TYPES_LIST')
)

In [24]:
tool_types_by_title

,Title,TOOL_TYPES_LIST
0,Accountants and Auditors,"""Desktop calculator""; ""Desktop computer""; ""Las..."
1,Actors,"""Camera tripods""; ""Digital camcorders or video..."
2,Actuaries,"""Desktop calculator""; ""Desktop computer""; ""Not..."
3,Acupuncturists,"""Acupuncture magnet pellets or seeds""; ""Acupun..."
4,Acute Care Nurses,"""ASTM rated surgical masks/ tie back mask""; ""A..."
...,...,...
897,Wind Turbine Service Technicians,"""Acoustic ear muffs or defenders""; ""Adjustable..."
898,"Woodworking Machine Setters, Operators, and Te...","""Acoustic ear muffs or defenders""; ""Adjustable..."
899,Word Processors and Typists,"""Desktop calculator""; ""Franking or postage mac..."
900,Writers and Authors,"""Desktop computer""; ""Flash memory storage card..."
901,Zoologists and Wildlife Biologists,"""Adjustable widemouth pliers""; ""Air compressor..."

In [28]:
# Merge
titles_tools_and_types = df_tools_used.merge(
    total_tools_by_title,
    on=['Title', 'O*NET-SOC Code'],
    how='left'
)

# Merge
titles_tools_and_types = titles_tools_and_types.merge(
    total_tool_types_by_title,
    on=['Title'],
    how='left'
)

# Merge
titles_tools_and_types = titles_tools_and_types.merge(
    tools_by_title,
    on=['Title'],
    how='left'
)

# Merge
titles_tools_and_types = titles_tools_and_types.merge(
    tool_types_by_title,
    on=['Title'],
    how='left'
)

In [29]:
titles_tools_and_types

,O*NET-SOC Code,Title,Example,Commodity Code,Commodity Title,TOTAL_TOOLS_BY_JOB,TOTAL_TOOL_TYPES_BY_JOB,TOOLS_LIST,TOOL_TYPES_LIST
0,11-1011.00,Chief Executives,10-key calculators,44101809,Desktop calculator,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
1,11-1011.00,Chief Executives,Desktop computers,43211507,Desktop computer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
2,11-1011.00,Chief Executives,Laptop computers,43211503,Notebook computer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
3,11-1011.00,Chief Executives,Personal computers,43211508,Personal computer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
4,11-1011.00,Chief Executives,Personal digital assistants PDA,43211504,Personal digital assistant PDAs or organizer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
...,...,...,...,...,...,...,...,...,...
41657,53-7121.00,"Tank Car, Truck, and Ship Loaders",Stock pickers,24101605,Loading equipment,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."
41658,53-7121.00,"Tank Car, Truck, and Ship Loaders",Tablet computers,43211509,Tablet computer,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."
41659,53-7121.00,"Tank Car, Truck, and Ship Loaders",Walk behind pallet jacks,24101505,Pallet trucks,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."
41660,53-7121.00,"Tank Car, Truck, and Ship Loaders",Warehouse forklifts,24101603,Forklifts,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."
41661,53-7121.00,"Tank Car, Truck, and Ship Loaders",Wheeled front end loaders,22101501,Front end loaders,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."

In [33]:
titles_tools_and_types.rename(columns={'Title': 'Job Title'}, inplace=True)
titles_tools_and_types.rename(columns={'Example': 'Tool Name'}, inplace=True)
titles_tools_and_types.rename(columns={'Commodity Code': 'Tool Type Code'}, inplace=True)
titles_tools_and_types.rename(columns={'Commodity Title': 'Tool Type Title'}, inplace=True)

In [34]:
titles_tools_and_types

,O*NET-SOC Code,Job Title,Tool Name,Tool Type Code,Tool Type Title,TOTAL_TOOLS_BY_JOB,TOTAL_TOOL_TYPES_BY_JOB,TOOLS_LIST,TOOL_TYPES_LIST
0,11-1011.00,Chief Executives,10-key calculators,44101809,Desktop calculator,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
1,11-1011.00,Chief Executives,Desktop computers,43211507,Desktop computer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
2,11-1011.00,Chief Executives,Laptop computers,43211503,Notebook computer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
3,11-1011.00,Chief Executives,Personal computers,43211508,Personal computer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
4,11-1011.00,Chief Executives,Personal digital assistants PDA,43211504,Personal digital assistant PDAs or organizer,7,7,"""10-key calculators""; ""Desktop computers""; ""La...","""Desktop calculator""; ""Desktop computer""; ""Hig..."
...,...,...,...,...,...,...,...,...,...
41657,53-7121.00,"Tank Car, Truck, and Ship Loaders",Stock pickers,24101605,Loading equipment,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."
41658,53-7121.00,"Tank Car, Truck, and Ship Loaders",Tablet computers,43211509,Tablet computer,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."
41659,53-7121.00,"Tank Car, Truck, and Ship Loaders",Walk behind pallet jacks,24101505,Pallet trucks,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."
41660,53-7121.00,"Tank Car, Truck, and Ship Loaders",Warehouse forklifts,24101603,Forklifts,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."
41661,53-7121.00,"Tank Car, Truck, and Ship Loaders",Wheeled front end loaders,22101501,Front end loaders,17,15,"""Computer laser printers""; ""Conveyor belt syst...","""Belt conveyors""; ""Floor or platform scales""; ..."

In [35]:
titles_tools_and_types.to_csv('transformed data/2-Jobs Agg Tools.csv', index=False)

# Next - Need to aggregate Tools by Jobs - The reverse of what was done above

In [37]:
# Reset DF definition
df_tools_used = pd.read_csv('ONET data/Tools Used.csv')
df_tools_used['Commodity Code'] = df_tools_used['Commodity Code'].replace(23151807, 41104701)

In [ ]:
# Find count of unique tools by title
total_tools_by_title = (
    df_tools_used
    .groupby(['O*NET-SOC Code', 'Title'])['Example']
    .nunique()
    .reset_index(name='TOTAL_TOOLS_BY_JOB')
    .sort_values('TOTAL_TOOLS_BY_JOB', ascending=False)
)

# Find count of unique tool types by title
total_tool_types_by_title = (
    df_tools_used
    .groupby(['Title'])['Commodity Title']
    .nunique()
    .reset_index(name='TOTAL_TOOL_TYPES_BY_JOB')
    .sort_values('TOTAL_TOOL_TYPES_BY_JOB', ascending=False)
)

# Create column list of all tools by title
tools_by_title = (
    df_tools_used
    .groupby('Title')['Example']
    .apply(lambda x: '; '.join(
        f'"{e}"' for e in sorted(x.unique())
    ))
    .reset_index(name='TOOLS_LIST')
)

# Create column list of all tool types by title
tool_types_by_title = (
    df_tools_used
    .groupby('Title')['Commodity Title']
    .apply(lambda x: '; '.join(
        f'"{e}"' for e in sorted(x.unique())
    ))
    .reset_index(name='TOOL_TYPES_LIST')
)

In [45]:
# Find count of unique titles by tool
total_titles_by_tool = (
    df_tools_used
    .groupby(['Example'])['Title']
    .nunique()
    .reset_index(name='TOTAL_JOBS_BY_TOOL')
    .sort_values('TOTAL_JOBS_BY_TOOL', ascending=False)
)

# Find count of unique tools by title
total_titles_by_tool_type = (
    df_tools_used
    .groupby(['Commodity Title'])['Title']
    .nunique()
    .reset_index(name='TOTAL_JOBS_BY_TOOL_TYPE')
    .sort_values('TOTAL_JOBS_BY_TOOL_TYPE', ascending=False)
)

# Create column list of all job titles by tool
tools_by_title = (
    df_tools_used
    .groupby('Example')['Title']
    .apply(lambda x: '; '.join(
        f'"{e}"' for e in sorted(x.unique())
    ))
    .reset_index(name='JOBS_LIST')
)

# Create column list of all job titles by tool type
tool_types_by_title = (
    df_tools_used
    .groupby('Commodity Title')['Title']
    .apply(lambda x: '; '.join(
        f'"{e}"' for e in sorted(x.unique())
    ))
    .reset_index(name='TOOL_TYPES_LIST')
)

In [50]:
# Merge
tools_agg_jobs = total_titles_by_tool.merge(
    tools_by_title,
    on=['Example'],
    how='left'
)

tools_agg_jobs

,Example,TOTAL_JOBS_BY_TOOL,JOBS_LIST
0,Personal computers,656,"""Accountants and Auditors""; ""Actors""; ""Actuari..."
1,Desktop computers,570,"""Accountants and Auditors""; ""Actuaries""; ""Acut..."
2,Laptop computers,425,"""Accountants and Auditors""; ""Actors""; ""Acute C..."
3,Tablet computers,227,"""Accountants and Auditors""; ""Actors""; ""Acute C..."
4,Laser facsimile machines,166,"""Accountants and Auditors""; ""Administrative La..."
...,...,...,...
18100,Half-round hand files,1,"""Craft Artists"""
18101,Half-round needle files,1,"""Craft Artists"""
18102,Half-round pliers,1,"""Craft Artists"""
18103,Halide meters,1,"""Environmental Science and Protection Technici..."
18104,simplifyMD Dermatology,1,"""Dermatologists"""

In [63]:
#tools_agg_jobs.rename(columns={'Example': 'Tool Name'}, inplace=True)
tools_agg_jobs.to_csv('transformed data/2-Tools Agg Jobs.csv', index=False)

In [58]:
# Merge
tool_types_agg_jobs = total_titles_by_tool_type.merge(
    tool_types_by_title,
    on=['Commodity Title'],
    how='left'
)

tool_types_agg_jobs

,Commodity Title,TOTAL_JOBS_BY_TOOL_TYPE,TOOL_TYPES_LIST
0,Personal computer,658,"""Accountants and Auditors""; ""Actors""; ""Actuari..."
1,Desktop computer,572,"""Accountants and Auditors""; ""Actuaries""; ""Acut..."
2,Notebook computer,555,"""Accountants and Auditors""; ""Actors""; ""Actuari..."
3,Tablet computer,233,"""Accountants and Auditors""; ""Actors""; ""Acute C..."
4,Scanners,225,"""Accountants and Auditors""; ""Administrative Se..."
...,...,...,...
4121,Leather riveting machines,1,"""Shoe and Leather Workers and Repairers"""
4122,Leather nailing machines,1,"""Shoe Machine Operators and Tenders"""
4123,Leather cutting machines,1,"""Shoe and Leather Workers and Repairers"""
4124,Lawn scarifiers,1,"""Farmers, Ranchers, and Other Agricultural Man..."
4125,pH test strips or papers,1,"""Firefighters"""

In [64]:
tool_types_agg_jobs.rename(columns={'Commodity Title': 'Tool Type'}, inplace=True)
tool_types_agg_jobs.to_csv('transformed data/2-Tool Types Agg Jobs.csv', index=False)

In [ ]:
# Merge
titles_tools_and_types = df_tools_used.merge(
    total_tools_by_title,
    on=['Title', 'O*NET-SOC Code'],
    how='left'
)

# Merge
titles_tools_and_types = titles_tools_and_types.merge(
    total_tool_types_by_title,
    on=['Commodity Title', 'O*NET-SOC Code'],
    how='left'
)

# Merge
titles_tools_and_types = titles_tools_and_types.merge(
    tools_by_title,
    on=['Title'],
    how='left'
)

# Merge
titles_tools_and_types = titles_tools_and_types.merge(
    tool_types_by_title,
    on=['Title'],
    how='left'
)

In [ ]:
titles_tools_and_types.rename(columns={'Title': 'Job Title'}, inplace=True)
titles_tools_and_types.rename(columns={'Example': 'Tool Name'}, inplace=True)
titles_tools_and_types.rename(columns={'Commodity Code': 'Tool Type Code'}, inplace=True)
titles_tools_and_types.rename(columns={'Commodity Title': 'Tool Type Title'}, inplace=True)