In [4]:
import pandas as pd

Essential Files

File Contains

Occupation Data.txt Basic occupation information (title, description, code)
Task Statements.txt Specific tasks performed in each occupation
Skills.txt Skills required for each occupation with importance levels
Abilities.txt Abilities required with importance and level ratings
Work Activities.txt Generalized work activities with importance/level
Knowledge.txt Knowledge areas required
Work Context.txt Environmental and situational context
Tools and Technology.txt Software, equipment, and tools used

Other ones that look important:

Interests

Knowledge

# Occupation Data

In [5]:
df_occupation_data = pd.read_csv('ONET data/Occupation Data.csv')
df_occupation_data

,O*NET-SOC Code,Title,Description
0,11-1011.00,Chief Executives,Determine and formulate policies and provide o...
1,11-1011.03,Chief Sustainability Officers,"Communicate and coordinate with management, sh..."
2,11-1021.00,General and Operations Managers,"Plan, direct, or coordinate the operations of ..."
3,11-1031.00,Legislators,"Develop, introduce, or enact laws and statutes..."
4,11-2011.00,Advertising and Promotions Managers,"Plan, direct, or coordinate advertising polici..."
...,...,...,...
1011,55-3014.00,Artillery and Missile Crew Members,"Target, fire, and maintain weapons used to des..."
1012,55-3015.00,Command and Control Center Specialists,"Operate and monitor communications, detection,..."
1013,55-3016.00,Infantry,Operate weapons and equipment in ground combat...
1014,55-3018.00,Special Forces,"Implement unconventional operations by air, la..."
1015,55-3019.00,Military Enlisted Tactical Operations and Air/...,All military enlisted tactical operations and ...

In [14]:
df_occupation_data['Title'].nunique()

1016

# Task Statements

In [6]:
df_task_statements = pd.read_csv('ONET data/Task Statements.csv')
df_task_statements

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source
0,11-1011.00,Chief Executives,8823,Direct or coordinate an organization's financi...,Core,95.0,08/2023,Incumbent
1,11-1011.00,Chief Executives,8824,"Confer with board members, organization offici...",Core,95.0,08/2023,Incumbent
2,11-1011.00,Chief Executives,8827,"Prepare budgets for approval, including those ...",Core,95.0,08/2023,Incumbent
3,11-1011.00,Chief Executives,8826,"Direct, plan, or implement policies, objective...",Core,94.0,08/2023,Incumbent
4,11-1011.00,Chief Executives,8834,Prepare or present reports concerning activiti...,Core,95.0,08/2023,Incumbent
...,...,...,...,...,...,...,...,...
18791,53-7121.00,"Tank Car, Truck, and Ship Loaders",12807,Unload cars containing liquids by connecting h...,Supplemental,85.0,08/2019,Incumbent
18792,53-7121.00,"Tank Car, Truck, and Ship Loaders",12804,"Clean interiors of tank cars or tank trucks, u...",Supplemental,85.0,08/2019,Incumbent
18793,53-7121.00,"Tank Car, Truck, and Ship Loaders",12803,Lower gauge rods into tanks or read meters to ...,Supplemental,85.0,08/2019,Incumbent
18794,53-7121.00,"Tank Car, Truck, and Ship Loaders",12805,Operate conveyors and equipment to transfer gr...,Supplemental,85.0,08/2019,Incumbent
18795,53-7121.00,"Tank Car, Truck, and Ship Loaders",12810,"Perform general warehouse activities, such as ...",Supplemental,85.0,08/2019,Incumbent

In [17]:
df_task_statements.columns

Index(['O*NET-SOC Code', 'Title', 'Task ID', 'Task', 'Task Type',
       'Incumbents Responding', 'Date', 'Domain Source'],
      dtype='object')

In [15]:
df_task_statements['Title'].nunique()

923

In [16]:
df_task_statements['Task'].nunique()

17537

In [19]:
df_task_statements['Task ID'].nunique()

18796

# Skills

In [7]:
df_skills = pd.read_csv('ONET data/Skills.csv')
df_skills

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,LV,Level,4.62,8,0.1830,4.2664,4.9836,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,2.A.1.b,Active Listening,IM,Importance,4.00,8,0.0000,4.0000,4.0000,N,NaN,08/2023,Analyst
3,11-1011.00,Chief Executives,2.A.1.b,Active Listening,LV,Level,4.75,8,0.1637,4.4292,5.0708,N,N,08/2023,Analyst
4,11-1011.00,Chief Executives,2.A.1.c,Writing,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62575,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.b,Management of Financial Resources,LV,Level,1.12,8,0.1250,0.8800,1.3700,N,N,08/2019,Analyst
62576,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,IM,Importance,2.00,8,0.0000,2.0000,2.0000,N,NaN,08/2019,Analyst
62577,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,LV,Level,1.88,8,0.1250,1.6300,2.1200,N,N,08/2019,Analyst
62578,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,IM,Importance,2.88,8,0.1250,2.6300,3.1200,N,NaN,08/2019,Analyst
62579,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,LV,Level,2.75,8,0.1637,2.4292,3.0708,N,N,08/2019,Analyst

# Abilities

In [8]:
df_abilities = pd.read_csv('ONET data/Abilities.csv')
df_abilities

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,1.A.1.a.1,Oral Comprehension,IM,Importance,4.62,8,0.1830,4.2664,4.9836,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,1.A.1.a.1,Oral Comprehension,LV,Level,4.88,8,0.1250,4.6300,5.1200,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,1.A.1.a.2,Written Comprehension,IM,Importance,4.25,8,0.1637,3.9292,4.5708,N,NaN,08/2023,Analyst
3,11-1011.00,Chief Executives,1.A.1.a.2,Written Comprehension,LV,Level,4.88,8,0.1250,4.6300,5.1200,N,N,08/2023,Analyst
4,11-1011.00,Chief Executives,1.A.1.a.3,Oral Expression,IM,Importance,4.50,8,0.1890,4.1296,4.8704,N,NaN,08/2023,Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92971,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.3,Sound Localization,LV,Level,2.00,8,0.0000,2.0000,2.0000,N,N,08/2019,Analyst
92972,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.4,Speech Recognition,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2019,Analyst
92973,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.4,Speech Recognition,LV,Level,2.75,8,0.1637,2.4292,3.0708,N,N,08/2019,Analyst
92974,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.5,Speech Clarity,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2019,Analyst
92975,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.5,Speech Clarity,LV,Level,2.88,8,0.1250,2.6300,3.1200,N,N,08/2019,Analyst

# Work Activities

In [9]:
df_work_activities = pd.read_csv('ONET data/Work Activities.csv')
df_work_activities

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,4.A.1.a.1,Getting Information,IM,Importance,4.56,29.0,0.1559,4.2369,4.8756,N,NaN,08/2023,Incumbent
1,11-1011.00,Chief Executives,4.A.1.a.1,Getting Information,LV,Level,4.89,30.0,0.1727,4.5393,5.2458,N,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,4.A.1.a.2,"Monitoring Processes, Materials, or Surroundings",IM,Importance,4.25,30.0,0.2125,3.8130,4.6823,N,NaN,08/2023,Incumbent
3,11-1011.00,Chief Executives,4.A.1.a.2,"Monitoring Processes, Materials, or Surroundings",LV,Level,5.21,30.0,0.3872,4.4133,5.9971,N,N,08/2023,Incumbent
4,11-1011.00,Chief Executives,4.A.1.b.1,"Identifying Objects, Actions, and Events",IM,Importance,4.23,29.0,0.1544,3.9180,4.5507,N,NaN,08/2023,Incumbent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73303,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.1,Performing Administrative Activities,LV,Level,2.27,27.0,0.3184,1.6108,2.9197,N,N,08/2019,Incumbent
73304,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.2,Staffing Organizational Units,IM,Importance,1.93,27.0,0.2132,1.4962,2.3726,N,NaN,08/2019,Incumbent
73305,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.2,Staffing Organizational Units,LV,Level,1.60,27.0,0.2965,0.9936,2.2125,N,N,08/2019,Incumbent
73306,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.3,Monitoring and Controlling Resources,IM,Importance,2.56,27.0,0.2582,2.0266,3.0881,N,NaN,08/2019,Incumbent
73307,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.3,Monitoring and Controlling Resources,LV,Level,2.64,27.0,0.3350,1.9556,3.3329,N,N,08/2019,Incumbent

# Knowledge

In [10]:
df_knowledge = pd.read_csv('ONET data/Knowledge.csv')
df_knowledge

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.C.1.a,Administration and Management,IM,Importance,4.78,28.0,0.1102,4.5564,5.0000,N,NaN,08/2023,Incumbent
1,11-1011.00,Chief Executives,2.C.1.a,Administration and Management,LV,Level,6.50,28.0,0.2130,6.0666,6.9409,N,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,2.C.1.b,Administrative,IM,Importance,2.42,28.0,0.4651,1.4662,3.3749,N,NaN,08/2023,Incumbent
3,11-1011.00,Chief Executives,2.C.1.b,Administrative,LV,Level,2.69,28.0,0.8678,0.9078,4.4690,N,N,08/2023,Incumbent
4,11-1011.00,Chief Executives,2.C.1.c,Economics and Accounting,IM,Importance,4.04,28.0,0.3480,3.3246,4.7526,N,NaN,08/2023,Incumbent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58999,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.9.a,Telecommunications,LV,Level,0.93,26.0,0.2603,0.3972,1.4693,N,N,08/2019,Incumbent
59000,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.9.b,Communications and Media,IM,Importance,1.67,26.0,0.2296,1.2006,2.1464,N,NaN,08/2019,Incumbent
59001,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.9.b,Communications and Media,LV,Level,1.23,26.0,0.4098,0.3845,2.0724,N,N,08/2019,Incumbent
59002,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.10,Transportation,IM,Importance,3.53,27.0,0.3248,2.8658,4.2009,N,NaN,08/2019,Incumbent
59003,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.10,Transportation,LV,Level,2.72,27.0,0.3687,1.9641,3.4800,N,N,08/2019,Incumbent

# Work Context

In [11]:
df_work_context = pd.read_csv('ONET data/Work Context.csv')
df_work_context

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Category,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CX,Context,NaN,3.07,37.0,0.2851,2.4923,3.6486,N,NaN,08/2023,Incumbent
1,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CXP,Context (Categories 1-5),1.0,0.13,37.0,0.1370,0.0160,1.0770,N,NaN,08/2023,Incumbent
2,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CXP,Context (Categories 1-5),2.0,39.49,37.0,11.0101,20.4073,62.4299,N,NaN,08/2023,Incumbent
3,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CXP,Context (Categories 1-5),3.0,33.07,37.0,7.1359,20.4456,48.7245,N,NaN,08/2023,Incumbent
4,11-1011.00,Chief Executives,4.C.1.a.2.c,Public Speaking,CXP,Context (Categories 1-5),4.0,7.79,37.0,4.3613,2.4093,22.4457,N,NaN,08/2023,Incumbent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297671,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.4,Work Schedules,CTP,Context (Categories 1-3),3.0,0.89,32.0,0.9750,0.0947,7.8674,N,NaN,08/2019,Incumbent
297672,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.8,Duration of Typical Work Week,CT,Context,NaN,2.82,32.0,0.0983,2.6238,3.0000,N,NaN,08/2019,Incumbent
297673,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.8,Duration of Typical Work Week,CTP,Context (Categories 1-3),1.0,0.00,32.0,0.0000,NaN,NaN,N,NaN,08/2019,Incumbent
297674,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.8,Duration of Typical Work Week,CTP,Context (Categories 1-3),2.0,17.56,32.0,9.8350,5.0617,45.9881,N,NaN,08/2019,Incumbent
297675,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.C.3.d.8,Duration of Typical Work Week,CTP,Context (Categories 1-3),3.0,82.44,32.0,9.8350,54.0119,94.9383,N,NaN,08/2019,Incumbent

# Tools

In [12]:
df_tools_used = pd.read_csv('ONET data/Tools Used.csv')
df_tools_used

,O*NET-SOC Code,Title,Example,Commodity Code,Commodity Title
0,11-1011.00,Chief Executives,10-key calculators,44101809,Desktop calculator
1,11-1011.00,Chief Executives,Desktop computers,43211507,Desktop computer
2,11-1011.00,Chief Executives,Laptop computers,43211503,Notebook computer
3,11-1011.00,Chief Executives,Personal computers,43211508,Personal computer
4,11-1011.00,Chief Executives,Personal digital assistants PDA,43211504,Personal digital assistant PDAs or organizer
...,...,...,...,...,...
41657,53-7121.00,"Tank Car, Truck, and Ship Loaders",Stock pickers,24101605,Loading equipment
41658,53-7121.00,"Tank Car, Truck, and Ship Loaders",Tablet computers,43211509,Tablet computer
41659,53-7121.00,"Tank Car, Truck, and Ship Loaders",Walk behind pallet jacks,24101505,Pallet trucks
41660,53-7121.00,"Tank Car, Truck, and Ship Loaders",Warehouse forklifts,24101603,Forklifts
41661,53-7121.00,"Tank Car, Truck, and Ship Loaders",Wheeled front end loaders,22101501,Front end loaders

# Technology

In [13]:
df_technology_skills = pd.read_csv('ONET data/Technology Skills.csv')
df_technology_skills

,O*NET-SOC Code,Title,Example,Commodity Code,Commodity Title,Hot Technology,In Demand
0,11-1011.00,Chief Executives,Adobe Acrobat,43232202,Document management software,Y,N
1,11-1011.00,Chief Executives,AdSense Tracker,43232306,Data base user interface and query software,N,N
2,11-1011.00,Chief Executives,Atlassian JIRA,43232201,Content workflow software,Y,N
3,11-1011.00,Chief Executives,Blackbaud The Raiser's Edge,43232303,Customer relationship management CRM software,N,N
4,11-1011.00,Chief Executives,ComputerEase construction accounting software,43231601,Accounting software,N,N
...,...,...,...,...,...,...,...
32768,53-7121.00,"Tank Car, Truck, and Ship Loaders",Linux,43233004,Operating system software,Y,N
32769,53-7121.00,"Tank Car, Truck, and Ship Loaders",Microsoft Excel,43232110,Spreadsheet software,Y,N
32770,53-7121.00,"Tank Car, Truck, and Ship Loaders",Microsoft Office software,43231513,Office suite software,Y,N
32771,53-7121.00,"Tank Car, Truck, and Ship Loaders",SAP software,43231602,Enterprise resource planning ERP software,Y,N
32772,53-7121.00,"Tank Car, Truck, and Ship Loaders",Warehouse management system WMS,43231506,Materials requirements planning logistics and ...,N,N

In [35]:
df_technology_skills['O*NET-SOC Code'].nunique()

923

In [36]:
df_technology_skills['Title'].nunique()

923

In [22]:
df_technology_skills['Example'].nunique()

8785

In [23]:
df_technology_skills['Commodity Code'].nunique()

137

In [24]:
df_technology_skills['Commodity Title'].nunique()

137

# Everything below has been moved to other notebook.

In [43]:
total_skills_by_title = (
    df_technology_skills
    .groupby(['O*NET-SOC Code', 'Title'])['Example']
    .nunique()
    .reset_index(name='TOTAL_EXAMPLES')
    .sort_values('TOTAL_EXAMPLES', ascending=False)
)

total_skills_by_title

,O*NET-SOC Code,Title,TOTAL_EXAMPLES
117,15-1252.00,Software Developers,429
118,15-1253.00,Software Quality Assurance Analysts and Testers,428
130,15-1299.09,Information Technology Project Managers,334
113,15-1243.00,Database Architects,324
104,15-1211.00,Computer Systems Analysts,313
...,...,...,...
527,35-9021.00,Dishwashers,2
910,53-7041.00,Hoist and Winch Operators,2
893,53-4041.00,Subway and Streetcar Operators,2
783,51-4023.00,"Rolling Machine Setters, Operators, and Tender...",2
780,51-3093.00,Food Cooking Machine Operators and Tenders,1

In [45]:
total_commods_by_title = (
    df_technology_skills
    .groupby(['O*NET-SOC Code', 'Title'])['Commodity Code']
    .nunique()
    .reset_index(name='TOTAL_COMMODITIES')
    .sort_values('TOTAL_COMMODITIES', ascending=False)
)

total_commods_by_title

,O*NET-SOC Code,Title,TOTAL_COMMODITIES
109,15-1232.00,Computer User Support Specialists,75
129,15-1299.08,Computer Systems Engineers/Architects,69
118,15-1253.00,Software Quality Assurance Analysts and Testers,68
104,15-1211.00,Computer Systems Analysts,68
115,15-1244.00,Network and Computer Systems Administrators,68
...,...,...,...
893,53-4041.00,Subway and Streetcar Operators,2
910,53-7041.00,Hoist and Winch Operators,2
413,29-1214.00,Emergency Medicine Physicians,1
752,49-9063.00,Musical Instrument Repairers and Tuners,1
780,51-3093.00,Food Cooking Machine Operators and Tenders,1

In [49]:
soc_commodity_breakdown = (
    df_technology_skills
    .groupby([
        'O*NET-SOC Code', 'Title'
    ])
    .agg(
        num_examples=('Example', 'nunique'),
        example_list=('Example',
                      lambda x: '; '.join(
                          f'"{e}"' for e in sorted(x.unique())
                      ))
    )
    .reset_index()
)

soc_commodity_breakdown

,O*NET-SOC Code,Title,num_examples,example_list
0,11-1011.00,Chief Executives,49,"""AdSense Tracker""; ""Adobe Acrobat""; ""Atlassian..."
1,11-1011.03,Chief Sustainability Officers,21,"""Adobe Acrobat""; ""Adobe Photoshop""; ""Email sof..."
2,11-1021.00,General and Operations Managers,146,"""ADP Workforce Now""; ""AMG Teleran SalesInSync""..."
3,11-1031.00,Legislators,32,"""Adobe Acrobat""; ""Adobe FrameMaker""; ""Antenna ..."
4,11-2011.00,Advertising and Promotions Managers,73,"""Actuate BIRT""; ""AdRelevance""; ""Adobe Acrobat""..."
...,...,...,...,...
918,53-7071.00,Gas Compressor and Gas Pumping Station Operators,6,"""Computerized maintenance management system CM..."
919,53-7072.00,"Pump Operators, Except Wellhead Pumpers",7,"""Computerized maintenance management system CM..."
920,53-7073.00,Wellhead Pumpers,8,"""Microsoft Excel""; ""Microsoft Office software""..."
921,53-7081.00,Refuse and Recyclable Material Collectors,10,"""AMCS Platform""; ""Computerized maintenance man..."
922,53-7121.00,"Tank Car, Truck, and Ship Loaders",7,"""CompuWeigh GMS""; ""Distributed control system ..."

# Next, I should look at how many JOB TITLES each EXAMPLE is associated with. Then, each job can be assigned a score for the uniqueness of the skills required.

# Everything below here is old.

In [46]:
grouped_by_code_and_commod = (
    df_technology_skills
    .groupby(['Commodity Code', 'O*NET-SOC Code', 'Title'])['Example']
    .nunique()
    .reset_index(name='num_examples')
    .sort_values('num_examples', ascending=False)
)

grouped_by_code_and_commod

,Commodity Code,O*NET-SOC Code,Title,num_examples
9475,43232605,19-2043.00,Hydrologists,92
9474,43232605,19-2042.00,"Geoscientists, Except Hydrologists and Geograp...",84
2332,43231604,13-2051.00,Financial and Investment Analysts,81
9965,43232610,29-1222.00,"Physicians, Pathologists",81
2335,43231604,13-2054.00,Financial Risk Specialists,77
...,...,...,...,...
4994,43232110,17-2011.00,Aerospace Engineers,1
4995,43232110,17-2021.00,Agricultural Engineers,1
4996,43232110,17-2031.00,Bioengineers and Biomedical Engineers,1
4999,43232110,17-2051.01,Transportation Engineers,1
12907,43233701,43-6014.00,"Secretaries and Administrative Assistants, Exc...",1

In [30]:
soc_commodity_breakdown = (
    df_technology_skills
    .groupby([
        'O*NET-SOC Code',
        'Title',
        'Commodity Code',
        'Commodity Title'
    ])
    .agg(
        num_examples=('Example', 'nunique'),
        example_list=('Example',
                      lambda x: '; '.join(
                          f'"{e}"' for e in sorted(x.unique())
                      ))
    )
    .reset_index()
)

In [31]:
soc_commodity_breakdown

,O*NET-SOC Code,Title,Commodity Code,Commodity Title,num_examples,example_list
0,11-1011.00,Chief Executives,43231505,Human resources software,4,"""Halogen e360""; ""Halogen ePraisal""; ""Human res..."
1,11-1011.00,Chief Executives,43231507,Project management software,3,"""HCSS HeavyBid""; ""HCSS HeavyJob""; ""Microsoft P..."
2,11-1011.00,Chief Executives,43231513,Office suite software,1,"""Microsoft Office software"""
3,11-1011.00,Chief Executives,43231601,Accounting software,4,"""ComputerEase construction accounting software..."
4,11-1011.00,Chief Executives,43231602,Enterprise resource planning ERP software,7,"""Enterprise resource planning ERP software""; ""..."
...,...,...,...,...,...,...
12903,53-7121.00,"Tank Car, Truck, and Ship Loaders",43231513,Office suite software,1,"""Microsoft Office software"""
12904,53-7121.00,"Tank Car, Truck, and Ship Loaders",43231602,Enterprise resource planning ERP software,1,"""SAP software"""
12905,53-7121.00,"Tank Car, Truck, and Ship Loaders",43232110,Spreadsheet software,1,"""Microsoft Excel"""
12906,53-7121.00,"Tank Car, Truck, and Ship Loaders",43232306,Data base user interface and query software,1,"""CompuWeigh GMS"""
12907,53-7121.00,"Tank Car, Truck, and Ship Loaders",43233004,Operating system software,1,"""Linux"""

In [32]:
soc_commodity_breakdown['num_examples'].value_counts()

num_examples
1     7816
2     2307
3      912
4      486
5      349
      ...
39       1
54       1
57       1
68       1
62       1
Name: count, Length: 65, dtype: int64

In [33]:
soc_commodity_breakdown.nlargest(10, 'num_examples')

,O*NET-SOC Code,Title,Commodity Code,Commodity Title,num_examples,example_list
5212,19-2043.00,Hydrologists,43232605,Analytical or scientific software,92,"""Argus ONE Open Numerical Environments""; ""Bent..."
5195,19-2042.00,"Geoscientists, Except Hydrologists and Geograp...",43232605,Analytical or scientific software,84,"""Alara CRystalView""; ""Aquifer test software""; ..."
2044,13-2051.00,Financial and Investment Analysts,43231604,Financial analysis software,81,"""Advanced Portfolio Technologies Report Builde..."
8006,29-1222.00,"Physicians, Pathologists",43232610,Medical software,81,"""Anatomic pathology software""; ""Antek HealthWa..."
2103,13-2054.00,Financial Risk Specialists,43231604,Financial analysis software,77,"""Advanced Portfolio Technologies Report Builde..."
7366,27-2041.00,Music Directors and Composers,43232005,Music or sound editing software,77,"""Anvil Studio""; ""Apple MainStage""; ""Arobas Mus..."
7083,27-1014.00,Special Effects Artists and Animators,43232102,Graphics or photo imaging software,69,"""ACD Systems Canvas""; ""Ability Photopaint""; ""A..."
1469,13-1071.00,Human Resources Specialists,43231505,Human resources software,68,"""ADP Workforce Now""; ""AST Staff Matrix""; ""Adob..."
3465,15-1299.09,Information Technology Project Managers,43231507,Project management software,67,"""24SevenOffice Project""; ""AEC Software FastTra..."
2953,15-1252.00,Software Developers,43232402,Development environment software,66,"""A programming language APL""; ""ABC Compiler""; ..."

In [34]:
soc_commodity_breakdown.nsmallest(10, 'num_examples')

,O*NET-SOC Code,Title,Commodity Code,Commodity Title,num_examples,example_list
2,11-1011.00,Chief Executives,43231513,Office suite software,1,"""Microsoft Office software"""
5,11-1011.00,Chief Executives,43231604,Financial analysis software,1,"""Microsoft FRx"""
8,11-1011.00,Chief Executives,43232104,Word processing software,1,"""Microsoft Word"""
10,11-1011.00,Chief Executives,43232110,Spreadsheet software,1,"""Microsoft Excel"""
11,11-1011.00,Chief Executives,43232112,Desktop publishing software,1,"""Microsoft Publisher"""
12,11-1011.00,Chief Executives,43232201,Content workflow software,1,"""Atlassian JIRA"""
15,11-1011.00,Chief Executives,43232304,Data base management system software,1,"""Relational database management software"""
16,11-1011.00,Chief Executives,43232305,Data base reporting software,1,"""Database reporting software"""
18,11-1011.00,Chief Executives,43232403,Enterprise application integration software,1,"""Extensible markup language XML"""
19,11-1011.00,Chief Executives,43232408,Web platform development software,1,"""PHP"""

In [38]:
commod_types_by_job = (
    soc_commodity_breakdown
        .groupby("Title")["Commodity Title"]
        .nunique()
        .reset_index(name="Number of Commodity Types per Job Title")
)

commod_types_by_job

,Title,Number of Commodity Types per Job Title
0,Accountants and Auditors,37
1,Actors,12
2,Actuaries,15
3,Acupuncturists,6
4,Acute Care Nurses,9
...,...,...
918,Wind Turbine Service Technicians,12
919,"Woodworking Machine Setters, Operators, and Te...",18
920,Word Processors and Typists,13
921,Writers and Authors,22
922,Zoologists and Wildlife Biologists,14