In [1]:
import pandas as pd
df_occupation_data = pd.read_csv('ONET data/Occupation Data.csv')
df_task_statements = pd.read_csv('ONET data/Task Statements.csv')
df_skills = pd.read_csv('ONET data/Skills.csv')
df_abilities = pd.read_csv('ONET data/Abilities.csv')
df_work_activities = pd.read_csv('ONET data/Work Activities.csv')
df_knowledge = pd.read_csv('ONET data/Knowledge.csv')
df_work_context = pd.read_csv('ONET data/Work Context.csv')
df_tools_used = pd.read_csv('ONET data/Tools Used.csv')
df_technology_skills = pd.read_csv('ONET data/Technology Skills.csv')

In [9]:
df_skills.columns

Index(['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID',
       'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound',
       'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date',
       'Domain Source'],
      dtype='object')

In [2]:
df_skills

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,LV,Level,4.62,8,0.1830,4.2664,4.9836,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,2.A.1.b,Active Listening,IM,Importance,4.00,8,0.0000,4.0000,4.0000,N,NaN,08/2023,Analyst
3,11-1011.00,Chief Executives,2.A.1.b,Active Listening,LV,Level,4.75,8,0.1637,4.4292,5.0708,N,N,08/2023,Analyst
4,11-1011.00,Chief Executives,2.A.1.c,Writing,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62575,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.b,Management of Financial Resources,LV,Level,1.12,8,0.1250,0.8800,1.3700,N,N,08/2019,Analyst
62576,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,IM,Importance,2.00,8,0.0000,2.0000,2.0000,N,NaN,08/2019,Analyst
62577,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,LV,Level,1.88,8,0.1250,1.6300,2.1200,N,N,08/2019,Analyst
62578,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,IM,Importance,2.88,8,0.1250,2.6300,3.1200,N,NaN,08/2019,Analyst
62579,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,LV,Level,2.75,8,0.1637,2.4292,3.0708,N,N,08/2019,Analyst

In [20]:
df_skills['Recommend Suppress'].value_counts()

Recommend Suppress
N    62433
Y      147
Name: count, dtype: int64

In [21]:
df_skills['Not Relevant'].value_counts()

Not Relevant
N    27907
Y     3383
Name: count, dtype: int64

In [ ]:
df_skills['Element ID'].nunique()

In [5]:
df_skills['Element ID'].nunique()

35

In [8]:
123

123

# Pivot

In [10]:
df = df_skills.copy()

# Create combined column label
df["Skill_Scale"] = df["Element Name"] + " " + df["Scale Name"]

In [11]:
df_wide = df.pivot_table(
    index=["O*NET-SOC Code", "Title"],
    columns="Skill_Scale",
    values="Data Value"
).reset_index()

In [12]:
df_wide

Skill_Scale,O*NET-SOC Code,Title,Active Learning Importance,Active Learning Level,Active Listening Importance,Active Listening Level,Complex Problem Solving Importance,Complex Problem Solving Level,Coordination Importance,Coordination Level,...,Systems Evaluation Importance,Systems Evaluation Level,Technology Design Importance,Technology Design Level,Time Management Importance,Time Management Level,Troubleshooting Importance,Troubleshooting Level,Writing Importance,Writing Level
0,11-1011.00,Chief Executives,3.75,4.50,4.00,4.75,4.38,4.88,4.25,4.88,...,4.25,5.00,1.75,0.88,4.00,4.75,1.50,0.50,4.12,4.38
1,11-1011.03,Chief Sustainability Officers,3.75,3.88,4.00,4.00,4.00,4.12,3.75,3.88,...,3.88,4.00,1.88,1.12,3.38,3.88,1.00,0.00,4.12,4.25
2,11-1021.00,General and Operations Managers,3.62,3.75,4.00,4.12,3.62,3.88,3.88,4.00,...,3.12,3.25,1.50,0.62,3.62,3.88,1.75,1.00,3.50,3.88
3,11-2011.00,Advertising and Promotions Managers,3.25,4.12,4.12,4.12,3.50,3.88,3.50,4.12,...,3.12,3.75,1.75,0.75,3.50,3.88,1.00,0.00,3.75,3.88
4,11-2021.00,Marketing Managers,3.88,4.12,3.88,4.12,3.62,3.88,3.50,3.75,...,3.50,3.75,1.75,0.88,3.50,3.75,1.00,0.00,3.25,3.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,2.88,2.38,3.12,3.00,3.00,3.00,3.00,2.88,...,2.00,2.12,1.88,1.12,3.00,2.75,3.12,3.12,3.00,2.88
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",2.88,2.88,3.12,3.00,2.88,2.88,2.88,3.00,...,2.12,2.12,1.88,0.88,3.00,2.88,3.00,2.88,2.88,2.75
891,53-7073.00,Wellhead Pumpers,2.38,2.12,2.88,2.75,3.00,2.88,2.25,2.38,...,2.00,1.38,1.50,0.50,2.75,2.75,3.12,3.00,2.62,2.12
892,53-7081.00,Refuse and Recyclable Material Collectors,2.25,1.62,2.88,2.50,2.38,2.12,2.62,2.50,...,1.38,0.75,1.00,0.00,2.50,2.38,2.50,2.00,2.50,2.00
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.75,2.75,3.00,3.00,3.00,2.88,2.88,2.88,...,2.12,2.12,1.75,0.75,3.12,2.88,2.62,2.50,3.00,2.75

In [13]:
df_wide.to_csv('transformed data/4-Skills Pivoted.csv', index=False)

# Remove irrelevant skills

In [26]:
df_relevant = df_skills.copy()

# Rename column, relabel data, change column data type
df_relevant.rename(columns={'Not Relevant': 'Relevant'}, inplace=True)
df_relevant['Relevant'] = df_relevant['Relevant'].replace('Y', '0')
df_relevant['Relevant'] = df_relevant['Relevant'].replace('N', '1')
df_relevant['Relevant'] = df_relevant['Relevant'].fillna(1)
df_relevant['Relevant'] = df_relevant['Relevant'].astype('int')

# 
df_relevant['Recommend Suppress'] = df_relevant['Recommend Suppress'].replace('Y', '1')
df_relevant['Recommend Suppress'] = df_relevant['Recommend Suppress'].replace('N', '0')
df_relevant['Recommend Suppress'] = df_relevant['Recommend Suppress'].astype('int')

In [27]:
df_relevant

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,IM,Importance,4.12,8,0.1250,3.8800,4.3700,0,1,08/2023,Analyst
1,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,LV,Level,4.62,8,0.1830,4.2664,4.9836,0,1,08/2023,Analyst
2,11-1011.00,Chief Executives,2.A.1.b,Active Listening,IM,Importance,4.00,8,0.0000,4.0000,4.0000,0,1,08/2023,Analyst
3,11-1011.00,Chief Executives,2.A.1.b,Active Listening,LV,Level,4.75,8,0.1637,4.4292,5.0708,0,1,08/2023,Analyst
4,11-1011.00,Chief Executives,2.A.1.c,Writing,IM,Importance,4.12,8,0.1250,3.8800,4.3700,0,1,08/2023,Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62575,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.b,Management of Financial Resources,LV,Level,1.12,8,0.1250,0.8800,1.3700,0,1,08/2019,Analyst
62576,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,IM,Importance,2.00,8,0.0000,2.0000,2.0000,0,1,08/2019,Analyst
62577,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,LV,Level,1.88,8,0.1250,1.6300,2.1200,0,1,08/2019,Analyst
62578,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,IM,Importance,2.88,8,0.1250,2.6300,3.1200,0,1,08/2019,Analyst
62579,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,LV,Level,2.75,8,0.1637,2.4292,3.0708,0,1,08/2019,Analyst

In [28]:
df_irrev = df_relevant[df_relevant['Recommend Suppress'] == 1]
df_irrev = df_irrev[df_irrev['Relevant'] == 0]
df_irrev

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Relevant,Date,Domain Source
965,11-3031.03,Investment Fund Managers,2.B.3.m,Quality Control Analysis,LV,Level,0.75,8,0.5261,0.0,1.7812,1,0,07/2014,Analyst
1239,11-3051.03,Biofuels Production Managers,2.B.3.j,Equipment Maintenance,LV,Level,0.75,8,0.5261,0.0,1.7812,1,0,07/2016,Analyst
5933,13-1199.07,Security Management Specialists,2.B.3.l,Repairing,LV,Level,0.75,8,0.5261,0.0,1.7812,1,0,08/2025,Analyst
7669,15-1243.01,Data Warehousing Specialists,2.B.3.c,Equipment Selection,LV,Level,0.88,8,0.5806,0.0,2.0129,1,0,08/2018,Analyst
8379,15-1299.05,Information Security Engineers,2.B.3.j,Equipment Maintenance,LV,Level,0.75,8,0.5261,0.0,1.7812,1,0,08/2025,Analyst
24329,27-2041.00,Music Directors and Composers,2.B.3.c,Equipment Selection,LV,Level,1.00,8,0.7559,0.0,2.4816,1,0,08/2022,Analyst
38695,41-3031.00,"Securities, Commodities, and Financial Service...",2.B.3.m,Quality Control Analysis,LV,Level,0.88,8,0.5806,0.0,2.0129,1,0,08/2022,Analyst
47711,47-5032.00,"Explosives Workers, Ordnance Handling Experts,...",2.B.3.d,Installation,LV,Level,0.88,8,0.5806,0.0,2.0129,1,0,06/2010,Analyst

In [30]:
df_rev_sup = df_relevant[df_relevant['Recommend Suppress'] == 1]
df_rev_sup = df_rev_sup[df_rev_sup['Relevant'] == 1]
df_rev_sup

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Relevant,Date,Domain Source
665,11-3013.01,Security Managers,2.B.3.a,Operations Analysis,LV,Level,2.00,8,0.6547,0.7169,3.2831,1,1,08/2025,Analyst
805,11-3031.00,Financial Managers,2.B.3.a,Operations Analysis,LV,Level,1.12,8,0.5154,0.1148,2.1352,1,1,08/2022,Analyst
813,11-3031.00,Financial Managers,2.B.3.e,Programming,LV,Level,1.62,8,0.5957,0.4573,2.7927,1,1,08/2022,Analyst
829,11-3031.00,Financial Managers,2.B.4.g,Systems Analysis,LV,Level,3.25,8,0.5261,2.2188,4.2812,1,1,08/2022,Analyst
831,11-3031.00,Financial Managers,2.B.4.h,Systems Evaluation,LV,Level,3.25,8,0.5590,2.1543,4.3457,1,1,08/2022,Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57585,51-9071.00,Jewelers and Precious Stone and Metal Workers,2.B.3.g,Operations Monitoring,LV,Level,1.75,8,0.5261,0.7188,2.7812,1,1,08/2025,Analyst
58353,51-9162.00,Computer Numerically Controlled Tool Programmers,2.B.3.e,Programming,LV,Level,3.62,8,0.5324,2.5814,4.6686,1,1,08/2025,Analyst
58709,51-9195.00,"Molders, Shapers, and Casters, Except Metal an...",2.B.3.j,Equipment Maintenance,LV,Level,1.88,8,0.5154,0.8648,2.8852,1,1,08/2024,Analyst
60459,53-4022.00,"Railroad Brake, Signal, and Switch Operators a...",2.B.3.j,Equipment Maintenance,LV,Level,1.38,8,0.5650,0.2676,2.4824,1,1,08/2024,Analyst
61705,53-7041.00,Hoist and Winch Operators,2.B.3.a,Operations Analysis,LV,Level,1.12,8,0.5806,0.0000,2.2629,1,1,06/2010,Analyst

In [29]:
df_relevant.shape

(62580, 15)

In [31]:
df_relevant_only = df_relevant[df_relevant['Recommend Suppress'] == 0]
df_relevant_only = df_relevant_only[df_relevant_only['Relevant'] == 1]
df_relevant_only

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,IM,Importance,4.12,8,0.1250,3.8800,4.3700,0,1,08/2023,Analyst
1,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,LV,Level,4.62,8,0.1830,4.2664,4.9836,0,1,08/2023,Analyst
2,11-1011.00,Chief Executives,2.A.1.b,Active Listening,IM,Importance,4.00,8,0.0000,4.0000,4.0000,0,1,08/2023,Analyst
3,11-1011.00,Chief Executives,2.A.1.b,Active Listening,LV,Level,4.75,8,0.1637,4.4292,5.0708,0,1,08/2023,Analyst
4,11-1011.00,Chief Executives,2.A.1.c,Writing,IM,Importance,4.12,8,0.1250,3.8800,4.3700,0,1,08/2023,Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62575,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.b,Management of Financial Resources,LV,Level,1.12,8,0.1250,0.8800,1.3700,0,1,08/2019,Analyst
62576,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,IM,Importance,2.00,8,0.0000,2.0000,2.0000,0,1,08/2019,Analyst
62577,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.c,Management of Material Resources,LV,Level,1.88,8,0.1250,1.6300,2.1200,0,1,08/2019,Analyst
62578,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,IM,Importance,2.88,8,0.1250,2.6300,3.1200,0,1,08/2019,Analyst
62579,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.B.5.d,Management of Personnel Resources,LV,Level,2.75,8,0.1637,2.4292,3.0708,0,1,08/2019,Analyst

In [32]:
# Create combined column label
df_relevant_only["Skill_Scale"] = df_relevant_only["Element Name"] + " " + df_relevant_only["Scale Name"]

In [33]:
df_wide_rel = df_relevant_only.pivot_table(
    index=["O*NET-SOC Code", "Title"],
    columns="Skill_Scale",
    values="Data Value"
).reset_index()

In [34]:
df_wide_rel

Skill_Scale,O*NET-SOC Code,Title,Active Learning Importance,Active Learning Level,Active Listening Importance,Active Listening Level,Complex Problem Solving Importance,Complex Problem Solving Level,Coordination Importance,Coordination Level,...,Systems Evaluation Importance,Systems Evaluation Level,Technology Design Importance,Technology Design Level,Time Management Importance,Time Management Level,Troubleshooting Importance,Troubleshooting Level,Writing Importance,Writing Level
0,11-1011.00,Chief Executives,3.75,4.50,4.00,4.75,4.38,4.88,4.25,4.88,...,4.25,5.00,1.75,0.88,4.00,4.75,1.50,0.50,4.12,4.38
1,11-1011.03,Chief Sustainability Officers,3.75,3.88,4.00,4.00,4.00,4.12,3.75,3.88,...,3.88,4.00,1.88,1.12,3.38,3.88,1.00,NaN,4.12,4.25
2,11-1021.00,General and Operations Managers,3.62,3.75,4.00,4.12,3.62,3.88,3.88,4.00,...,3.12,3.25,1.50,0.62,3.62,3.88,1.75,1.00,3.50,3.88
3,11-2011.00,Advertising and Promotions Managers,3.25,4.12,4.12,4.12,3.50,3.88,3.50,4.12,...,3.12,3.75,1.75,0.75,3.50,3.88,1.00,NaN,3.75,3.88
4,11-2021.00,Marketing Managers,3.88,4.12,3.88,4.12,3.62,3.88,3.50,3.75,...,3.50,3.75,1.75,0.88,3.50,3.75,1.00,NaN,3.25,3.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,2.88,2.38,3.12,3.00,3.00,3.00,3.00,2.88,...,2.00,2.12,1.88,1.12,3.00,2.75,3.12,3.12,3.00,2.88
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",2.88,2.88,3.12,3.00,2.88,2.88,2.88,3.00,...,2.12,2.12,1.88,0.88,3.00,2.88,3.00,2.88,2.88,2.75
891,53-7073.00,Wellhead Pumpers,2.38,2.12,2.88,2.75,3.00,2.88,2.25,2.38,...,2.00,1.38,1.50,0.50,2.75,2.75,3.12,3.00,2.62,2.12
892,53-7081.00,Refuse and Recyclable Material Collectors,2.25,1.62,2.88,2.50,2.38,2.12,2.62,2.50,...,1.38,0.75,1.00,NaN,2.50,2.38,2.50,2.00,2.50,2.00
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.75,2.75,3.00,3.00,3.00,2.88,2.88,2.88,...,2.12,2.12,1.75,0.75,3.12,2.88,2.62,2.50,3.00,2.75

In [35]:
df_wide_rel.isnull().sum()

Skill_Scale
O*NET-SOC Code                   0
Title                            0
Active Learning Importance       0
Active Learning Level            0
Active Listening Importance      0
                              ...
Time Management Level            0
Troubleshooting Importance       0
Troubleshooting Level          188
Writing Importance               0
Writing Level                    0
Length: 72, dtype: int64

In [36]:
df_wide_rel.to_csv('transformed data/4-Skills Pivoted Relevant Only.csv', index=False)

# Supress should be separate thing?

# Pivot 2

In [15]:
df = df_skills.copy()

df["Skill_Scale"] = df["Element Name"] + " " + df["Scale Name"]

In [18]:
df_wide = df.pivot_table(
    index=["O*NET-SOC Code", "Title"],
    columns="Skill_Scale",
    values=["Data Value", "Recommend Suppress", "Not Relevant"],
    aggfunc="first"  # safer than pivot
)

In [19]:
df_wide.columns = [
    f"{skill} ({metric})"
    for metric, skill in df_wide.columns
]

df_wide = df_wide.reset_index()
df_wide

,O*NET-SOC Code,Title,Active Learning Importance (Data Value),Active Learning Level (Data Value),Active Listening Importance (Data Value),Active Listening Level (Data Value),Complex Problem Solving Importance (Data Value),Complex Problem Solving Level (Data Value),Coordination Importance (Data Value),Coordination Level (Data Value),...,Systems Evaluation Importance (Recommend Suppress),Systems Evaluation Level (Recommend Suppress),Technology Design Importance (Recommend Suppress),Technology Design Level (Recommend Suppress),Time Management Importance (Recommend Suppress),Time Management Level (Recommend Suppress),Troubleshooting Importance (Recommend Suppress),Troubleshooting Level (Recommend Suppress),Writing Importance (Recommend Suppress),Writing Level (Recommend Suppress)
0,11-1011.00,Chief Executives,3.75,4.50,4.00,4.75,4.38,4.88,4.25,4.88,...,N,N,N,N,N,N,N,N,N,N
1,11-1011.03,Chief Sustainability Officers,3.75,3.88,4.00,4.00,4.00,4.12,3.75,3.88,...,N,N,N,N,N,N,N,N,N,N
2,11-1021.00,General and Operations Managers,3.62,3.75,4.00,4.12,3.62,3.88,3.88,4.00,...,N,N,N,N,N,N,N,N,N,N
3,11-2011.00,Advertising and Promotions Managers,3.25,4.12,4.12,4.12,3.50,3.88,3.50,4.12,...,N,N,N,N,N,N,N,N,N,N
4,11-2021.00,Marketing Managers,3.88,4.12,3.88,4.12,3.62,3.88,3.50,3.75,...,N,N,N,N,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,2.88,2.38,3.12,3.00,3.00,3.00,3.00,2.88,...,N,N,N,N,N,N,N,N,N,N
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",2.88,2.88,3.12,3.00,2.88,2.88,2.88,3.00,...,N,N,N,N,N,N,N,N,N,N
891,53-7073.00,Wellhead Pumpers,2.38,2.12,2.88,2.75,3.00,2.88,2.25,2.38,...,N,N,N,N,N,N,N,N,N,N
892,53-7081.00,Refuse and Recyclable Material Collectors,2.25,1.62,2.88,2.50,2.38,2.12,2.62,2.50,...,N,N,N,N,N,N,N,N,N,N
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.75,2.75,3.00,3.00,3.00,2.88,2.88,2.88,...,N,N,N,N,N,N,N,N,N,N