In [2]:
import pandas as pd
df_occupation_data = pd.read_csv('ONET data/Occupation Data.csv')
df_task_statements = pd.read_csv('ONET data/Task Statements.csv')
df_skills = pd.read_csv('ONET data/Skills.csv')
df_abilities = pd.read_csv('ONET data/Abilities.csv')
df_work_activities = pd.read_csv('ONET data/Work Activities.csv')
df_knowledge = pd.read_csv('ONET data/Knowledge.csv')
df_work_context = pd.read_csv('ONET data/Work Context.csv')
df_tools_used = pd.read_csv('ONET data/Tools Used.csv')
df_technology_skills = pd.read_csv('ONET data/Technology Skills.csv')

In [3]:
df_abilities

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,1.A.1.a.1,Oral Comprehension,IM,Importance,4.62,8,0.1830,4.2664,4.9836,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,1.A.1.a.1,Oral Comprehension,LV,Level,4.88,8,0.1250,4.6300,5.1200,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,1.A.1.a.2,Written Comprehension,IM,Importance,4.25,8,0.1637,3.9292,4.5708,N,NaN,08/2023,Analyst
3,11-1011.00,Chief Executives,1.A.1.a.2,Written Comprehension,LV,Level,4.88,8,0.1250,4.6300,5.1200,N,N,08/2023,Analyst
4,11-1011.00,Chief Executives,1.A.1.a.3,Oral Expression,IM,Importance,4.50,8,0.1890,4.1296,4.8704,N,NaN,08/2023,Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92971,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.3,Sound Localization,LV,Level,2.00,8,0.0000,2.0000,2.0000,N,N,08/2019,Analyst
92972,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.4,Speech Recognition,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2019,Analyst
92973,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.4,Speech Recognition,LV,Level,2.75,8,0.1637,2.4292,3.0708,N,N,08/2019,Analyst
92974,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.5,Speech Clarity,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2019,Analyst
92975,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.A.4.b.5,Speech Clarity,LV,Level,2.88,8,0.1250,2.6300,3.1200,N,N,08/2019,Analyst

In [5]:
df = df_abilities.copy()

# Create combined column label
df["Skill_Scale"] = df["Element Name"] + " " + df["Scale Name"]

In [6]:
df_wide = df.pivot_table(
    index=["O*NET-SOC Code", "Title"],
    columns="Skill_Scale",
    values="Data Value"
).reset_index()

In [7]:
df_wide

Skill_Scale,O*NET-SOC Code,Title,Arm-Hand Steadiness Importance,Arm-Hand Steadiness Level,Auditory Attention Importance,Auditory Attention Level,Category Flexibility Importance,Category Flexibility Level,Control Precision Importance,Control Precision Level,...,Visual Color Discrimination Importance,Visual Color Discrimination Level,Visualization Importance,Visualization Level,Wrist-Finger Speed Importance,Wrist-Finger Speed Level,Written Comprehension Importance,Written Comprehension Level,Written Expression Importance,Written Expression Level
0,11-1011.00,Chief Executives,1.38,0.50,2.12,2.00,3.50,4.00,1.75,0.75,...,2.00,2.00,3.00,3.38,1.38,0.50,4.25,4.88,4.12,4.75
1,11-1011.03,Chief Sustainability Officers,1.00,0.00,2.00,1.75,3.12,3.50,1.50,0.50,...,2.12,2.00,2.75,2.88,1.12,0.12,4.00,4.25,4.12,4.38
2,11-1021.00,General and Operations Managers,1.62,0.88,2.12,2.00,3.38,3.25,1.12,0.12,...,1.88,1.75,2.75,2.75,1.75,0.88,4.00,4.00,4.00,4.00
3,11-2011.00,Advertising and Promotions Managers,1.38,0.50,1.75,1.25,3.38,3.88,1.12,0.12,...,2.88,2.75,3.25,3.12,1.75,0.75,4.00,4.00,3.88,4.00
4,11-2021.00,Marketing Managers,1.12,0.12,1.88,1.62,3.25,3.62,1.00,0.00,...,2.88,2.88,3.00,3.00,1.62,0.75,4.00,4.12,3.88,4.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,3.88,3.12,3.00,3.00,3.00,3.00,3.50,3.12,...,2.88,2.38,2.75,2.75,2.00,2.00,3.12,2.88,3.00,2.88
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",3.12,3.12,3.00,3.50,3.00,3.12,3.38,3.25,...,3.00,3.25,3.00,3.25,2.62,2.12,3.12,3.00,3.25,2.88
891,53-7073.00,Wellhead Pumpers,3.00,2.88,2.25,2.62,2.88,3.00,3.25,4.00,...,2.00,1.62,2.75,3.12,2.12,1.62,2.88,2.75,2.62,2.38
892,53-7081.00,Refuse and Recyclable Material Collectors,3.25,2.25,2.75,2.25,2.75,2.38,2.88,2.88,...,2.88,2.75,2.50,2.25,1.62,1.00,2.50,2.25,2.50,2.00
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",3.38,3.12,3.00,3.00,2.88,2.88,3.88,4.00,...,2.75,2.88,3.00,3.00,2.12,2.00,3.00,3.00,3.00,2.75

# Z Scores

In [8]:
df_z = df_wide.copy()

# Identify numeric skill columns
skill_cols = df_wide.select_dtypes(include="number").columns


for col in skill_cols:
    df_z[col] = (
        (df_wide[col] - df_wide[col].mean()) /
        df_wide[col].std()
    )

In [9]:
meta_cols = ["O*NET-SOC Code", "Title"]

level_cols = [
    col for col in df_z.columns
    if "Level" in col
]

import_cols = [
    col for col in df_z.columns
    if "Importance" in col
]

In [10]:
df_z

Skill_Scale,O*NET-SOC Code,Title,Arm-Hand Steadiness Importance,Arm-Hand Steadiness Level,Auditory Attention Importance,Auditory Attention Level,Category Flexibility Importance,Category Flexibility Level,Control Precision Importance,Control Precision Level,...,Visual Color Discrimination Importance,Visual Color Discrimination Level,Visualization Importance,Visualization Level,Wrist-Finger Speed Importance,Wrist-Finger Speed Level,Written Comprehension Importance,Written Comprehension Level,Written Expression Importance,Written Expression Level
0,11-1011.00,Chief Executives,-1.309117,-1.417913,-0.610384,-0.351005,1.039936,1.489299,-0.738781,-1.076447,...,-1.134934,-0.633146,0.444475,0.772884,-1.112450,-1.097846,1.236142,1.482402,1.246800,1.445527
1,11-1011.03,Chief Sustainability Officers,-1.731674,-1.835224,-0.883532,-0.737513,-0.061986,0.507705,-1.019770,-1.273121,...,-0.885583,-0.633146,-0.049312,0.047408,-1.691559,-1.594708,0.804775,0.697888,1.246800,1.041509
2,11-1021.00,General and Operations Managers,-1.042238,-1.100757,-0.610384,-0.351005,0.691961,0.016909,-1.446874,-1.572066,...,-1.384285,-0.989016,-0.049312,-0.141216,-0.288334,-0.600983,0.804775,0.386574,1.059743,0.626571
3,11-2011.00,Advertising and Promotions Managers,-1.309117,-1.417913,-1.452592,-1.510529,0.691961,1.253716,-1.446874,-1.572066,...,0.693642,0.434464,0.938262,0.395636,-0.288334,-0.770962,0.804775,0.386574,0.872687,0.626571
4,11-2021.00,Marketing Managers,-1.598235,-1.735069,-1.156681,-0.938497,0.314988,0.743288,-1.581748,-1.666470,...,0.693642,0.619516,0.444475,0.221522,-0.577888,-0.770962,0.804775,0.536005,0.872687,0.757604
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,1.470866,0.768794,1.392707,1.195028,-0.409961,-0.473888,1.228142,0.788026,...,0.693642,-0.092224,-0.049312,-0.141216,0.268502,0.863455,-0.713638,-1.008117,-0.499062,-0.596403
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",0.625751,0.768794,1.392707,1.968044,-0.409961,-0.238305,1.093267,0.890297,...,0.942993,1.146204,0.444475,0.584260,1.649453,1.020359,-0.713638,-0.858686,-0.109360,-0.596403
891,53-7073.00,Wellhead Pumpers,0.492312,0.568485,-0.314472,0.607535,-0.757936,-0.473888,0.947153,1.480320,...,-1.134934,-1.174069,-0.049312,0.395636,0.535783,0.366592,-1.127751,-1.170000,-1.091408,-1.142373
892,53-7081.00,Refuse and Recyclable Material Collectors,0.770310,0.042674,0.823647,0.035503,-1.134909,-1.691063,0.531289,0.599219,...,0.693642,0.434464,-0.543099,-0.866693,-0.577888,-0.444079,-1.783429,-1.792630,-1.278464,-1.557311
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",0.914869,0.768794,1.392707,1.195028,-0.757936,-0.709470,1.655245,1.480320,...,0.423511,0.619516,0.444475,0.221522,0.535783,0.863455,-0.920694,-0.858686,-0.499062,-0.738355

In [11]:
df_z.to_csv('transformed data/5-Abilities Z-Scores.csv', index=False)

# Z Score aggregates

In [12]:
df_z_aggs = df_z.copy()



df_z_aggs["z_level_mean"] = df_z_aggs[level_cols].mean(axis=1)
df_z_aggs["z_level_median"] = df_z_aggs[level_cols].median(axis=1)
df_z_aggs["z_level_max"] = df_z_aggs[level_cols].max(axis=1)
df_z_aggs["z_level_min"] = df_z_aggs[level_cols].min(axis=1)
df_z_aggs["z_level_min+max"] = df_z_aggs["z_level_min"] + df_z_aggs["z_level_max"]

df_z_aggs["z_import_mean"] = df_z_aggs[import_cols].mean(axis=1)
df_z_aggs["z_import_median"] = df_z_aggs[import_cols].median(axis=1)
df_z_aggs["z_import_max"] = df_z_aggs[import_cols].max(axis=1)
df_z_aggs["z_import_min"] = df_z_aggs[import_cols].min(axis=1)
df_z_aggs["z_import_min+max"] = df_z_aggs["z_import_min"] + df_z_aggs["z_import_max"]

# Drop level_cols and import_cols as defined earlier
df_z_aggs = df_z_aggs.drop(columns=level_cols)
df_z_aggs = df_z_aggs.drop(columns=import_cols)

In [13]:
df_z_aggs

Skill_Scale,O*NET-SOC Code,Title,z_level_mean,z_level_median,z_level_max,z_level_min,z_level_min+max,z_import_mean,z_import_median,z_import_max,z_import_min,z_import_min+max
0,11-1011.00,Chief Executives,0.200177,-0.331558,2.357841,-1.778109,0.579732,0.053303,-0.274200,2.095306,-1.661826,0.433480
1,11-1011.03,Chief Sustainability Officers,-0.302820,-0.560380,1.687580,-1.917210,-0.229629,-0.378665,-0.826140,1.980469,-1.731674,0.248795
2,11-1021.00,General and Operations Managers,-0.345634,-0.424569,0.861243,-1.961317,-1.100074,-0.298140,-0.428903,1.059743,-1.599025,-0.539282
3,11-2011.00,Advertising and Promotions Managers,-0.279384,-0.768421,1.545223,-1.572066,-0.026844,-0.276138,-0.588800,1.742712,-1.452592,0.290120
4,11-2021.00,Marketing Managers,-0.237107,-0.620541,1.719250,-1.735069,-0.015819,-0.320981,-0.615790,1.552654,-1.655659,-0.103005
...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,0.276459,0.556223,1.743843,-1.315153,0.428690,0.378867,0.477653,1.847052,-1.437840,0.409211
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",0.469127,0.792002,2.036582,-1.151502,0.885080,0.537804,0.680569,2.387878,-1.238394,1.149484
891,53-7073.00,Wellhead Pumpers,0.065385,0.325945,1.877516,-1.674839,0.202677,0.011227,0.082461,1.808181,-2.003144,-0.194963
892,53-7081.00,Refuse and Recyclable Material Collectors,-0.335543,-0.121815,1.920157,-3.189658,-1.269501,-0.123253,0.224090,2.419066,-2.958089,-0.539023
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",0.535274,0.764024,2.276329,-1.132121,1.144208,0.692370,0.910153,2.588822,-1.372352,1.216470

In [14]:
df_z_aggs.to_csv('transformed data/5-Abilities Z-Score Aggregates.csv', index=False)

In [15]:
# Define columns to prefix
cols_to_prefix = df_z_aggs.drop(columns=['O*NET-SOC Code', 'Title']).columns
# Apply prefix to these columns
df_z_aggs_pref = df_z_aggs.rename(columns={c: f'SKILL_{c}' for c in cols_to_prefix})
df_z_aggs_pref

Skill_Scale,O*NET-SOC Code,Title,SKILL_z_level_mean,SKILL_z_level_median,SKILL_z_level_max,SKILL_z_level_min,SKILL_z_level_min+max,SKILL_z_import_mean,SKILL_z_import_median,SKILL_z_import_max,SKILL_z_import_min,SKILL_z_import_min+max
0,11-1011.00,Chief Executives,0.200177,-0.331558,2.357841,-1.778109,0.579732,0.053303,-0.274200,2.095306,-1.661826,0.433480
1,11-1011.03,Chief Sustainability Officers,-0.302820,-0.560380,1.687580,-1.917210,-0.229629,-0.378665,-0.826140,1.980469,-1.731674,0.248795
2,11-1021.00,General and Operations Managers,-0.345634,-0.424569,0.861243,-1.961317,-1.100074,-0.298140,-0.428903,1.059743,-1.599025,-0.539282
3,11-2011.00,Advertising and Promotions Managers,-0.279384,-0.768421,1.545223,-1.572066,-0.026844,-0.276138,-0.588800,1.742712,-1.452592,0.290120
4,11-2021.00,Marketing Managers,-0.237107,-0.620541,1.719250,-1.735069,-0.015819,-0.320981,-0.615790,1.552654,-1.655659,-0.103005
...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,0.276459,0.556223,1.743843,-1.315153,0.428690,0.378867,0.477653,1.847052,-1.437840,0.409211
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",0.469127,0.792002,2.036582,-1.151502,0.885080,0.537804,0.680569,2.387878,-1.238394,1.149484
891,53-7073.00,Wellhead Pumpers,0.065385,0.325945,1.877516,-1.674839,0.202677,0.011227,0.082461,1.808181,-2.003144,-0.194963
892,53-7081.00,Refuse and Recyclable Material Collectors,-0.335543,-0.121815,1.920157,-3.189658,-1.269501,-0.123253,0.224090,2.419066,-2.958089,-0.539023
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",0.535274,0.764024,2.276329,-1.132121,1.144208,0.692370,0.910153,2.588822,-1.372352,1.216470