In [1]:
import pandas as pd
df_technology_skills = pd.read_csv('ONET data/Technology Skills.csv')
df_tools_used = pd.read_csv('ONET data/Tools Used.csv')
df_task_statements = pd.read_csv('ONET data/Task Statements.csv')
df_skills = pd.read_csv('ONET data/Skills.csv')
df_abilities = pd.read_csv('ONET data/Abilities.csv')
df_occupation_data = pd.read_csv('ONET data/Occupation Data.csv')
df_work_activities = pd.read_csv('ONET data/Work Activities.csv')

df_knowledge = pd.read_csv('ONET data/Knowledge.csv')
df_work_context = pd.read_csv('ONET data/Work Context.csv')

In [3]:
df_knowledge = pd.read_csv('ONET data/Knowledge.csv')
df_knowledge

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.C.1.a,Administration and Management,IM,Importance,4.78,28.0,0.1102,4.5564,5.0000,N,NaN,08/2023,Incumbent
1,11-1011.00,Chief Executives,2.C.1.a,Administration and Management,LV,Level,6.50,28.0,0.2130,6.0666,6.9409,N,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,2.C.1.b,Administrative,IM,Importance,2.42,28.0,0.4651,1.4662,3.3749,N,NaN,08/2023,Incumbent
3,11-1011.00,Chief Executives,2.C.1.b,Administrative,LV,Level,2.69,28.0,0.8678,0.9078,4.4690,N,N,08/2023,Incumbent
4,11-1011.00,Chief Executives,2.C.1.c,Economics and Accounting,IM,Importance,4.04,28.0,0.3480,3.3246,4.7526,N,NaN,08/2023,Incumbent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58999,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.9.a,Telecommunications,LV,Level,0.93,26.0,0.2603,0.3972,1.4693,N,N,08/2019,Incumbent
59000,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.9.b,Communications and Media,IM,Importance,1.67,26.0,0.2296,1.2006,2.1464,N,NaN,08/2019,Incumbent
59001,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.9.b,Communications and Media,LV,Level,1.23,26.0,0.4098,0.3845,2.0724,N,N,08/2019,Incumbent
59002,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.10,Transportation,IM,Importance,3.53,27.0,0.3248,2.8658,4.2009,N,NaN,08/2019,Incumbent
59003,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.C.10,Transportation,LV,Level,2.72,27.0,0.3687,1.9641,3.4800,N,N,08/2019,Incumbent

In [4]:
df = df_work_activities.copy()

# Create combined column label
df["Skill_Scale"] = df["Element Name"] + " " + df["Scale Name"]

In [5]:
df_wide = df.pivot_table(
    index=["O*NET-SOC Code", "Title"],
    columns="Skill_Scale",
    values="Data Value"
).reset_index()

In [6]:
df_wide

Skill_Scale,O*NET-SOC Code,Title,Analyzing Data or Information Importance,Analyzing Data or Information Level,Assisting and Caring for Others Importance,Assisting and Caring for Others Level,Coaching and Developing Others Importance,Coaching and Developing Others Level,Communicating with People Outside the Organization Importance,Communicating with People Outside the Organization Level,...,Staffing Organizational Units Importance,Staffing Organizational Units Level,Thinking Creatively Importance,Thinking Creatively Level,Training and Teaching Others Importance,Training and Teaching Others Level,Updating and Using Relevant Knowledge Importance,Updating and Using Relevant Knowledge Level,Working with Computers Importance,Working with Computers Level
0,11-1011.00,Chief Executives,4.38,4.84,3.31,3.10,4.71,5.85,4.55,5.47,...,3.78,4.80,4.32,4.45,4.01,4.76,4.31,5.09,4.17,3.03
1,11-1011.03,Chief Sustainability Officers,4.22,4.81,2.74,2.67,3.93,4.78,4.48,6.11,...,3.26,4.26,4.33,4.85,3.63,4.22,4.30,5.59,4.15,3.22
2,11-1021.00,General and Operations Managers,4.04,4.27,3.02,3.03,3.91,4.53,3.57,4.42,...,3.70,4.33,3.70,3.95,3.41,3.79,3.80,4.17,4.46,4.15
3,11-2011.00,Advertising and Promotions Managers,3.26,4.06,2.37,2.00,2.62,3.28,4.37,5.70,...,2.29,2.31,4.05,4.73,2.74,2.83,3.78,4.49,4.61,3.94
4,11-2021.00,Marketing Managers,3.75,4.04,2.44,2.21,3.36,3.74,4.20,5.60,...,2.25,2.18,4.28,4.71,3.14,3.34,3.83,4.52,4.40,3.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,3.68,4.43,2.54,2.15,2.98,2.76,3.04,2.68,...,1.84,0.70,3.12,3.52,3.73,4.22,4.05,4.75,3.85,3.47
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",3.96,3.97,3.09,2.58,2.86,2.69,2.74,3.00,...,2.18,2.06,3.41,3.99,3.15,3.04,3.99,4.36,2.69,1.98
891,53-7073.00,Wellhead Pumpers,3.70,3.80,3.04,2.97,3.16,3.31,2.72,2.44,...,1.94,1.66,3.34,3.52,3.48,3.56,3.31,3.90,3.53,3.55
892,53-7081.00,Refuse and Recyclable Material Collectors,1.61,1.03,1.69,1.10,2.10,1.80,2.39,2.44,...,1.00,0.01,1.57,0.98,1.69,1.22,2.17,2.39,1.55,0.96
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",3.85,3.90,2.87,3.11,3.07,3.28,2.61,2.47,...,1.93,1.60,3.44,3.74,3.45,3.85,3.84,4.48,2.82,2.58

In [7]:
df_wide.to_csv('transformed data/8-Knowledge Pivoted.csv', index=False)

# Z-Score

In [8]:
df_z = df_wide.copy()

# Identify numeric skill columns
skill_cols = df_wide.select_dtypes(include="number").columns


for col in skill_cols:
    df_z[col] = (
        (df_wide[col] - df_wide[col].mean()) /
        df_wide[col].std()
    )

In [9]:
meta_cols = ["O*NET-SOC Code", "Title"]

level_cols = [
    col for col in df_z.columns
    if "Level" in col
]

import_cols = [
    col for col in df_z.columns
    if "Importance" in col
]

In [10]:
df_z

Skill_Scale,O*NET-SOC Code,Title,Analyzing Data or Information Importance,Analyzing Data or Information Level,Assisting and Caring for Others Importance,Assisting and Caring for Others Level,Coaching and Developing Others Importance,Coaching and Developing Others Level,Communicating with People Outside the Organization Importance,Communicating with People Outside the Organization Level,...,Staffing Organizational Units Importance,Staffing Organizational Units Level,Thinking Creatively Importance,Thinking Creatively Level,Training and Teaching Others Importance,Training and Teaching Others Level,Updating and Using Relevant Knowledge Importance,Updating and Using Relevant Knowledge Level,Working with Computers Importance,Working with Computers Level
0,11-1011.00,Chief Executives,1.313527,0.932833,0.432228,0.056366,2.807985,2.384939,1.722547,1.567861,...,2.663555,2.535036,1.433874,0.517490,1.102784,1.174136,0.959917,0.554709,0.588128,-0.135967
1,11-1011.03,Chief Sustainability Officers,1.092393,0.908732,-0.239403,-0.285459,1.471349,1.317265,1.630032,2.075186,...,1.804619,2.041441,1.449188,0.880998,0.467536,0.641400,0.941850,1.059854,0.566970,0.039797
2,11-1021.00,General and Operations Managers,0.843617,0.474904,0.090521,0.000720,1.437077,1.067808,0.427333,0.735531,...,2.531411,2.105426,0.484433,0.063106,0.099760,0.217184,0.038518,-0.374756,0.894919,0.900114
3,11-2011.00,Advertising and Promotions Managers,-0.234414,0.306194,-0.675374,-0.818070,-0.773513,-0.179475,1.484650,1.750181,...,0.202373,0.259016,1.020408,0.771946,-1.020283,-0.729902,0.002385,-0.051464,1.053604,0.705848
4,11-2021.00,Marketing Managers,0.442810,0.290126,-0.592893,-0.651132,0.494577,0.279525,1.259970,1.670912,...,0.136301,0.140187,1.372620,0.753770,-0.351601,-0.226763,0.092718,-0.021155,0.831445,-0.052710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,0.346064,0.603446,-0.475063,-0.698829,-0.156604,-0.698345,-0.273140,-0.643759,...,-0.540937,-1.212628,-0.403754,-0.327665,0.634706,0.641400,0.490184,0.211211,0.249600,0.271065
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",0.733049,0.233889,0.173002,-0.357004,-0.362240,-0.768192,-0.669635,-0.390097,...,0.020675,0.030499,0.040339,0.099456,-0.334884,-0.522727,0.381784,-0.182801,-0.977563,-1.107292
891,53-7073.00,Wellhead Pumpers,0.373706,0.097314,0.114087,-0.046976,0.151850,-0.149540,-0.696068,-0.834006,...,-0.375757,-0.335126,-0.066856,-0.327665,0.216780,-0.009722,-0.846748,-0.647534,-0.088927,0.345070
892,53-7081.00,Refuse and Recyclable Material Collectors,-2.514864,-2.128061,-1.476618,-1.533518,-1.664603,-1.656258,-1.132211,-0.834006,...,-1.928448,-1.843333,-2.777358,-2.635940,-2.775576,-2.318245,-2.906345,-2.173069,-2.183568,-2.050866
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",0.581019,0.177652,-0.086224,0.064316,-0.002377,-0.179475,-0.841449,-0.810225,...,-0.392275,-0.389970,0.086280,-0.127736,0.166628,0.276377,0.110785,-0.061567,-0.840036,-0.552249

In [11]:
df_z.to_csv('transformed data/8-Knowledge Z-Scores.csv', index=False)

# Z Score Aggregates

In [12]:
df_z_aggs = df_z.copy()



df_z_aggs["z_level_mean"] = df_z_aggs[level_cols].mean(axis=1)
df_z_aggs["z_level_median"] = df_z_aggs[level_cols].median(axis=1)
df_z_aggs["z_level_max"] = df_z_aggs[level_cols].max(axis=1)
df_z_aggs["z_level_min"] = df_z_aggs[level_cols].min(axis=1)
df_z_aggs["z_level_min+max"] = df_z_aggs["z_level_min"] + df_z_aggs["z_level_max"]

df_z_aggs["z_import_mean"] = df_z_aggs[import_cols].mean(axis=1)
df_z_aggs["z_import_median"] = df_z_aggs[import_cols].median(axis=1)
df_z_aggs["z_import_max"] = df_z_aggs[import_cols].max(axis=1)
df_z_aggs["z_import_min"] = df_z_aggs[import_cols].min(axis=1)
df_z_aggs["z_import_min+max"] = df_z_aggs["z_import_min"] + df_z_aggs["z_import_max"]

# Drop level_cols and import_cols as defined earlier
df_z_aggs = df_z_aggs.drop(columns=level_cols)
df_z_aggs = df_z_aggs.drop(columns=import_cols)

In [13]:
df_z_aggs

Skill_Scale,O*NET-SOC Code,Title,z_level_mean,z_level_median,z_level_max,z_level_min,z_level_min+max,z_import_mean,z_import_median,z_import_max,z_import_min,z_import_min+max
0,11-1011.00,Chief Executives,0.988502,1.140046,2.763422,-1.242559,1.520864,1.139321,1.313527,2.941787,-1.098882,1.842905
1,11-1011.03,Chief Sustainability Officers,0.883665,1.076926,2.536746,-1.414820,1.121927,0.735323,0.936798,2.510226,-1.485761,1.024465
2,11-1021.00,General and Operations Managers,0.341514,0.146153,2.105426,-0.645212,1.460214,0.645487,0.688521,2.531411,-0.901970,1.629440
3,11-2011.00,Advertising and Promotions Managers,-0.037600,0.064568,2.011429,-1.724594,0.286835,-0.222291,-0.234414,1.801329,-2.081067,-0.279738
4,11-2021.00,Marketing Managers,0.156773,0.140187,2.874450,-2.040511,0.833939,0.222028,0.284129,2.751553,-1.998114,0.753439
...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,0.078342,-0.071763,2.139083,-2.080968,0.058115,0.314672,0.346064,2.389627,-2.225223,0.164404
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",0.068202,0.043869,1.748447,-1.603540,0.144908,0.419375,0.423927,2.122103,-1.263639,0.858463
891,53-7073.00,Wellhead Pumpers,0.027663,-0.091627,1.632093,-0.894325,0.737768,0.179760,0.195015,1.779673,-1.803561,-0.023888
892,53-7081.00,Refuse and Recyclable Material Collectors,-1.408930,-1.656258,2.330700,-2.676042,-0.345342,-1.647987,-2.034453,1.857114,-3.122300,-1.265186
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",0.239535,0.064700,1.811810,-1.133299,0.678511,0.360132,0.279446,1.990462,-1.134196,0.856267

In [14]:
# Define columns to prefix
cols_to_prefix = df_z_aggs.drop(columns=['O*NET-SOC Code', 'Title']).columns
# Apply prefix to these columns
df_z_aggs_pref = df_z_aggs.rename(columns={c: f'KNOWLEDGE_{c}' for c in cols_to_prefix})
df_z_aggs_pref

Skill_Scale,O*NET-SOC Code,Title,KNOWLEDGE_z_level_mean,KNOWLEDGE_z_level_median,KNOWLEDGE_z_level_max,KNOWLEDGE_z_level_min,KNOWLEDGE_z_level_min+max,KNOWLEDGE_z_import_mean,KNOWLEDGE_z_import_median,KNOWLEDGE_z_import_max,KNOWLEDGE_z_import_min,KNOWLEDGE_z_import_min+max
0,11-1011.00,Chief Executives,0.988502,1.140046,2.763422,-1.242559,1.520864,1.139321,1.313527,2.941787,-1.098882,1.842905
1,11-1011.03,Chief Sustainability Officers,0.883665,1.076926,2.536746,-1.414820,1.121927,0.735323,0.936798,2.510226,-1.485761,1.024465
2,11-1021.00,General and Operations Managers,0.341514,0.146153,2.105426,-0.645212,1.460214,0.645487,0.688521,2.531411,-0.901970,1.629440
3,11-2011.00,Advertising and Promotions Managers,-0.037600,0.064568,2.011429,-1.724594,0.286835,-0.222291,-0.234414,1.801329,-2.081067,-0.279738
4,11-2021.00,Marketing Managers,0.156773,0.140187,2.874450,-2.040511,0.833939,0.222028,0.284129,2.751553,-1.998114,0.753439
...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,0.078342,-0.071763,2.139083,-2.080968,0.058115,0.314672,0.346064,2.389627,-2.225223,0.164404
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",0.068202,0.043869,1.748447,-1.603540,0.144908,0.419375,0.423927,2.122103,-1.263639,0.858463
891,53-7073.00,Wellhead Pumpers,0.027663,-0.091627,1.632093,-0.894325,0.737768,0.179760,0.195015,1.779673,-1.803561,-0.023888
892,53-7081.00,Refuse and Recyclable Material Collectors,-1.408930,-1.656258,2.330700,-2.676042,-0.345342,-1.647987,-2.034453,1.857114,-3.122300,-1.265186
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",0.239535,0.064700,1.811810,-1.133299,0.678511,0.360132,0.279446,1.990462,-1.134196,0.856267

In [15]:
df_z_aggs_pref.to_csv('transformed data/8-Knowledge Z-Score Aggregates.csv', index=False)