# Loading dataset and EDA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
recom_df = pd.read_csv('recom.csv')
recom_df

,Unnamed: 0,Main_ID,Transaction_ID,Date,Price,Code_Product,Amount,ItemKey
0,0,90fada91,264f7a69,2022-10-07 20:53:49.153,125.0,5002.0,1.0,5002.0
1,1,9006f9ac,45c7d853,2022-09-17 15:54:57.187,19.0,35012.0,1.0,NaN
2,2,32270891,61ad76dd,2022-11-28 13:51:55.667,141.0,5005.0,1.0,5005.0
3,3,97e03e47,41ee09f6,2022-09-12 16:20:22.110,4.5,35078.5,1.0,NaN
4,4,41949228,244fe6d8,2022-10-14 18:53:43.933,129.5,49291.5,5.0,NaN
...,...,...,...,...,...,...,...,...
49995,49995,bb127ffb,4e0eb5ab,2022-09-24 21:48:20.847,111.5,45004.0,4.0,45004.0
49996,49996,a8bc484a,c9946c16,2022-11-18 19:49:01.973,34.0,49292.0,1.0,NaN
49997,49997,c983862a,d1a35c5c,2022-11-24 20:02:43.023,178.0,5001.5,1.0,5001.5
49998,49998,8821da12,66f9b474,2022-11-06 13:07:01.423,26.0,49291.5,1.0,NaN
49999,49999,7f281f91,0ff8b41f,2022-10-10 16:06:20.473,52.0,45001.5,1.0,45001.5

'Unnamed: 0' is likely an ETL artifact. We can delete it.

In [3]:
recom_df.drop('Unnamed: 0', axis=1, inplace=True)

I suspect that Code_Product and ItemKey are redundant, but ItemKey has nulls so I will have to check.

In [4]:
recom_df['mismatch'] = np.where(
    recom_df['Code_Product'].notna() &
    recom_df['ItemKey'].notna() &
    (recom_df['Code_Product'] != recom_df['ItemKey']),
    1,
    0
)

In [5]:
recom_df['mismatch'].value_counts()

mismatch
0    50000
Name: count, dtype: int64

As I thought, ItemKey is identical to Code_Product when not null, so we can drop it. I'll also rename Code_Product to better match the naming of other columns.

In [6]:
recom_df.drop('mismatch', axis=1, inplace=True)
recom_df.drop('ItemKey', axis=1, inplace=True)
recom_df.rename(columns={'Code_Product': 'Product_ID'}, inplace=True)
recom_df.rename(columns={'Main_ID': 'Customer_ID'}, inplace=True)

Quick EDA.

In [7]:
recom_df['Customer_ID'].nunique()

28514

In [8]:
recom_df['Transaction_ID'].nunique()

48403

In [9]:
recom_df['Product_ID'].nunique()

333

In [10]:
recom_df['Amount'].value_counts()

Amount
1.0     41695
2.0      6369
3.0      1279
4.0       415
5.0       130
6.0        56
7.0        16
10.0       11
8.0         7
20.0        4
13.0        4
18.0        3
9.0         2
54.0        1
33.0        1
19.0        1
41.0        1
17.0        1
28.0        1
14.0        1
16.0        1
12.0        1
Name: count, dtype: int64

In [11]:
transac_by_user = recom_df.groupby('Customer_ID')['Transaction_ID'].value_counts().sort_values(ascending=False)
transac_by_user.value_counts()

count
1    46859
2     1491
3       53
Name: count, dtype: int64

In [12]:
recom_df

,Customer_ID,Transaction_ID,Date,Price,Product_ID,Amount
0,90fada91,264f7a69,2022-10-07 20:53:49.153,125.0,5002.0,1.0
1,9006f9ac,45c7d853,2022-09-17 15:54:57.187,19.0,35012.0,1.0
2,32270891,61ad76dd,2022-11-28 13:51:55.667,141.0,5005.0,1.0
3,97e03e47,41ee09f6,2022-09-12 16:20:22.110,4.5,35078.5,1.0
4,41949228,244fe6d8,2022-10-14 18:53:43.933,129.5,49291.5,5.0
...,...,...,...,...,...,...
49995,bb127ffb,4e0eb5ab,2022-09-24 21:48:20.847,111.5,45004.0,4.0
49996,a8bc484a,c9946c16,2022-11-18 19:49:01.973,34.0,49292.0,1.0
49997,c983862a,d1a35c5c,2022-11-24 20:02:43.023,178.0,5001.5,1.0
49998,8821da12,66f9b474,2022-11-06 13:07:01.423,26.0,49291.5,1.0
49999,7f281f91,0ff8b41f,2022-10-10 16:06:20.473,52.0,45001.5,1.0

# Aggregates and new dataframes

In [13]:
recom_df_with_aggs = recom_df.copy()

# unique products per transaction
recom_df_with_aggs['unique_products_per_transac'] = (recom_df.groupby('Transaction_ID')['Product_ID'].transform('nunique'))

# total items per transaction
recom_df_with_aggs['total_items_per_transac'] = (recom_df.groupby('Transaction_ID')['Product_ID'].transform('count'))

# total spent per transaction
recom_df_with_aggs['total_spent_per_transac'] = (recom_df.groupby('Transaction_ID')['Price'].transform('sum'))

# =====================
# =====================

# unique products per customer
recom_df_with_aggs['unique_products_per_customer'] = (recom_df.groupby('Customer_ID')['Product_ID'].transform('nunique'))

# total items per customer
recom_df_with_aggs['total_items_per_customer'] = (recom_df.groupby('Customer_ID')['Product_ID'].transform('count'))

# total spent per customer
recom_df_with_aggs['total_spent_per_customer'] = (recom_df.groupby('Customer_ID')['Price'].transform('sum'))

# total transactions per customer
recom_df_with_aggs['transac_per_customer'] = (recom_df.groupby('Customer_ID')['Transaction_ID'].transform('nunique'))

# =====================
# =====================

# unique customers per product
recom_df_with_aggs['unique_customers_per_product'] = (recom_df.groupby('Product_ID')['Customer_ID'].transform('nunique'))

# total quantity sold per product
recom_df_with_aggs['total_sold_per_product'] = (recom_df.groupby('Product_ID')['Amount'].transform('sum'))

# total revenue per product
recom_df_with_aggs['total_revenue_per_product'] = (
    recom_df
    .assign(revenue=recom_df['Price'] * recom_df['Amount'])
    .groupby('Product_ID')['revenue']
    .transform('sum')
)

# median price per product
recom_df_with_aggs['median_price_per_product'] = (
    recom_df_with_aggs
        .groupby('Product_ID')['Price']
        .transform('median')
)

# min price per product
recom_df_with_aggs['max_price_per_product'] = (
    recom_df_with_aggs
        .groupby('Product_ID')['Price']
        .transform('max')
)

# max price per product
recom_df_with_aggs['min_price_per_product'] = (
    recom_df_with_aggs
        .groupby('Product_ID')['Price']
        .transform('min')
)

# price vs median
recom_df_with_aggs['price_vs_median'] = recom_df_with_aggs['Price'] - recom_df_with_aggs['median_price_per_product']

# median spend per transaction per customer
recom_df_with_aggs['median_spend_per_transaction_per_customer'] = (
    recom_df_with_aggs
        .groupby('Customer_ID')['total_spent_per_transac']
        .transform('median')
)

recom_df_with_aggs['max_spend_per_transaction_per_customer'] = (
    recom_df_with_aggs
        .groupby('Customer_ID')['total_spent_per_transac']
        .transform('max')
)

recom_df_with_aggs['min_spend_per_transaction_per_customer'] = (
    recom_df_with_aggs
        .groupby('Customer_ID')['total_spent_per_transac']
        .transform('min')
)



# All products bought by customer
customer_products = (
    recom_df_with_aggs
        .groupby('Customer_ID')['Product_ID']
        .agg(lambda x: sorted(x.dropna().unique()))
)
recom_df_with_aggs['products_bought_by_customer'] = (
    recom_df_with_aggs['Customer_ID'].map(customer_products)
)


# For each product, a count of repeat customers
product_customer_counts = (
    recom_df_with_aggs
        .groupby(['Product_ID', 'Customer_ID'])
        .size()
)
repeat_customers_per_product = (
    product_customer_counts
        .gt(1)                      # True if repeat buyer
        .groupby('Product_ID')
        .sum()                      # count of True values
)
recom_df_with_aggs['repeat_customers_per_product'] = (
    recom_df_with_aggs['Product_ID'].map(repeat_customers_per_product)
)

# Pct repeat customers per product
recom_df_with_aggs['pct_repeat_customers_per_product'] = recom_df_with_aggs['repeat_customers_per_product'] / recom_df_with_aggs['unique_customers_per_product']


# Repeat products per customer
customer_product_counts = (
    recom_df_with_aggs
        .groupby(['Customer_ID', 'Product_ID'])
        .size()
)
repeat_products_per_customer = (
    customer_product_counts
        .loc[lambda s: s > 1]
        .reset_index(level='Product_ID')
        .groupby('Customer_ID')['Product_ID']
        .agg(list)
)
recom_df_with_aggs['repeat_products_per_customer'] = (
    recom_df_with_aggs['Customer_ID'].map(repeat_products_per_customer)
)

# Count of repeat products per customer
num_repeat_products_per_customer = (
    recom_df_with_aggs
        .groupby(['Customer_ID', 'Product_ID'])
        .size()
        .gt(1)
        .groupby('Customer_ID')
        .sum()
)
recom_df_with_aggs['num_repeat_products_per_customer'] = (
    recom_df_with_aggs['Customer_ID']
        .map(num_repeat_products_per_customer)
        .fillna(0)
        .astype(int)
)

# Pct of products repeated per customer
recom_df_with_aggs['pct_products_repeated_per_customer'] = recom_df_with_aggs['num_repeat_products_per_customer'] / recom_df_with_aggs['unique_products_per_customer']

# Count of repeat purchases per customer
repeat_purchases_per_customer = (
    recom_df_with_aggs
        .groupby(['Customer_ID', 'Product_ID'])
        .size()
        .sub(1)            # purchase_count - 1
        .clip(lower=0)     # no negatives
        .groupby('Customer_ID')
        .sum()
)
recom_df_with_aggs['num_repeat_purchases_per_customer'] = (
    recom_df_with_aggs['Customer_ID']
        .map(repeat_purchases_per_customer)
        .fillna(0)
        .astype(int)
)

In [14]:
recom_df_with_aggs

,Customer_ID,Transaction_ID,Date,Price,Product_ID,Amount,unique_products_per_transac,total_items_per_transac,total_spent_per_transac,unique_products_per_customer,...,median_spend_per_transaction_per_customer,max_spend_per_transaction_per_customer,min_spend_per_transaction_per_customer,products_bought_by_customer,repeat_customers_per_product,pct_repeat_customers_per_product,repeat_products_per_customer,num_repeat_products_per_customer,pct_products_repeated_per_customer,num_repeat_purchases_per_customer
0,90fada91,264f7a69,2022-10-07 20:53:49.153,125.0,5002.0,1.0,1,1,125.0,1,...,125.0,125.0,125.0,[5002.0],42,0.063636,NaN,0,0.000000,0
1,9006f9ac,45c7d853,2022-09-17 15:54:57.187,19.0,35012.0,1.0,1,1,19.0,4,...,21.5,28.5,19.0,"[30026.5, 35012.0, 45002.5, 49291.5]",0,0.000000,NaN,0,0.000000,0
2,32270891,61ad76dd,2022-11-28 13:51:55.667,141.0,5005.0,1.0,1,1,141.0,8,...,87.0,145.5,37.5,"[5000.5, 5002.0, 5005.0, 5009.0, 49291.5, 4929...",4,0.090909,[49292.0],1,0.125000,1
3,97e03e47,41ee09f6,2022-09-12 16:20:22.110,4.5,35078.5,1.0,1,1,4.5,1,...,4.5,4.5,4.5,[35078.5],10,0.075758,NaN,0,0.000000,0
4,41949228,244fe6d8,2022-10-14 18:53:43.933,129.5,49291.5,5.0,1,1,129.5,1,...,129.5,129.5,129.5,[49291.5],403,0.097650,NaN,0,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,bb127ffb,4e0eb5ab,2022-09-24 21:48:20.847,111.5,45004.0,4.0,1,1,111.5,3,...,84.0,275.0,26.0,"[10032.5, 45004.0, 49291.5]",269,0.098463,[49291.5],1,0.333333,1
49996,a8bc484a,c9946c16,2022-11-18 19:49:01.973,34.0,49292.0,1.0,1,1,34.0,1,...,34.0,34.0,34.0,[49292.0],441,0.103279,NaN,0,0.000000,0
49997,c983862a,d1a35c5c,2022-11-24 20:02:43.023,178.0,5001.5,1.0,1,1,178.0,12,...,206.5,509.0,92.5,"[5000.5, 5001.5, 5002.0, 5012.0, 5027.5, 15004...",16,0.034707,"[45004.0, 45004.5, 49291.5]",3,0.250000,4
49998,8821da12,66f9b474,2022-11-06 13:07:01.423,26.0,49291.5,1.0,1,1,26.0,1,...,26.0,26.0,26.0,[49291.5],403,0.097650,NaN,0,0.000000,0
49999,7f281f91,0ff8b41f,2022-10-10 16:06:20.473,52.0,45001.5,1.0,1,1,52.0,6,...,17.5,52.0,4.0,"[35077.0, 35096.5, 35106.0, 40001.5, 45001.5, ...",37,0.050340,[35077.0],1,0.166667,2

In [15]:
recom_df_with_aggs.columns

Index(['Customer_ID', 'Transaction_ID', 'Date', 'Price', 'Product_ID',
       'Amount', 'unique_products_per_transac', 'total_items_per_transac',
       'total_spent_per_transac', 'unique_products_per_customer',
       'total_items_per_customer', 'total_spent_per_customer',
       'transac_per_customer', 'unique_customers_per_product',
       'total_sold_per_product', 'total_revenue_per_product',
       'median_price_per_product', 'max_price_per_product',
       'min_price_per_product', 'price_vs_median',
       'median_spend_per_transaction_per_customer',
       'max_spend_per_transaction_per_customer',
       'min_spend_per_transaction_per_customer', 'products_bought_by_customer',
       'repeat_customers_per_product', 'pct_repeat_customers_per_product',
       'repeat_products_per_customer', 'num_repeat_products_per_customer',
       'pct_products_repeated_per_customer',
       'num_repeat_purchases_per_customer'],
      dtype='object')

# Breakout DFs

In [16]:
transactions_df = recom_df_with_aggs[['Transaction_ID', 'Customer_ID', 'Date', 'Price', 'Product_ID', 'Amount', 'unique_products_per_transac', 'total_items_per_transac', 'total_spent_per_transac', 'median_price_per_product', 'price_vs_median']] 
transactions_df = transactions_df.drop_duplicates(subset=['Transaction_ID'], keep='first')
transactions_df

,Transaction_ID,Customer_ID,Date,Price,Product_ID,Amount,unique_products_per_transac,total_items_per_transac,total_spent_per_transac,median_price_per_product,price_vs_median
0,264f7a69,90fada91,2022-10-07 20:53:49.153,125.0,5002.0,1.0,1,1,125.0,69.00,56.00
1,45c7d853,9006f9ac,2022-09-17 15:54:57.187,19.0,35012.0,1.0,1,1,19.0,15.25,3.75
2,61ad76dd,32270891,2022-11-28 13:51:55.667,141.0,5005.0,1.0,1,1,141.0,136.25,4.75
3,41ee09f6,97e03e47,2022-09-12 16:20:22.110,4.5,35078.5,1.0,1,1,4.5,7.00,-2.50
4,244fe6d8,41949228,2022-10-14 18:53:43.933,129.5,49291.5,5.0,1,1,129.5,35.00,94.50
...,...,...,...,...,...,...,...,...,...,...,...
49995,4e0eb5ab,bb127ffb,2022-09-24 21:48:20.847,111.5,45004.0,4.0,1,1,111.5,43.50,68.00
49996,c9946c16,a8bc484a,2022-11-18 19:49:01.973,34.0,49292.0,1.0,1,1,34.0,36.50,-2.50
49997,d1a35c5c,c983862a,2022-11-24 20:02:43.023,178.0,5001.5,1.0,1,1,178.0,55.00,123.00
49998,66f9b474,8821da12,2022-11-06 13:07:01.423,26.0,49291.5,1.0,1,1,26.0,35.00,-9.00
49999,0ff8b41f,7f281f91,2022-10-10 16:06:20.473,52.0,45001.5,1.0,1,1,52.0,55.50,-3.50

In [17]:
products_df = recom_df_with_aggs[['Product_ID', 'Customer_ID', 'median_price_per_product', 'max_price_per_product', 'min_price_per_product', 'unique_customers_per_product', 'total_sold_per_product', 'total_revenue_per_product', 'repeat_customers_per_product', 'pct_repeat_customers_per_product']]
products_df = products_df.drop_duplicates(subset=['Product_ID'], keep='first')
products_df

,Product_ID,Customer_ID,median_price_per_product,max_price_per_product,min_price_per_product,unique_customers_per_product,total_sold_per_product,total_revenue_per_product,repeat_customers_per_product,pct_repeat_customers_per_product
0,5002.0,90fada91,69.00,776.0,1.0,660,796.0,77445.5,42,0.063636
1,35012.0,9006f9ac,15.25,107.0,5.0,8,8.0,195.5,0,0.000000
2,5005.0,32270891,136.25,1574.5,61.0,44,68.0,22259.5,4,0.090909
3,35078.5,97e03e47,7.00,64.0,4.0,132,189.0,1908.0,10,0.075758
4,49291.5,41949228,35.00,1033.5,0.5,4127,5706.0,294453.5,403,0.097650
...,...,...,...,...,...,...,...,...,...,...
44489,60051.0,a1fedd5e,48.00,48.0,48.0,1,3.0,144.0,0,0.000000
45174,35072.0,9704c040,25.50,25.5,25.5,1,1.0,25.5,0,0.000000
45448,20034.0,df4ce5ac,344.50,344.5,344.5,1,1.0,344.5,0,0.000000
45861,48590.0,b4db2269,52.50,52.5,52.5,1,1.0,52.5,0,0.000000
48410,35008.0,74746892,10.00,10.0,10.0,1,2.0,20.0,0,0.000000

In [18]:
products_df.columns

Index(['Product_ID', 'Customer_ID', 'median_price_per_product',
       'max_price_per_product', 'min_price_per_product',
       'unique_customers_per_product', 'total_sold_per_product',
       'total_revenue_per_product', 'repeat_customers_per_product',
       'pct_repeat_customers_per_product'],
      dtype='object')

In [19]:
customers_df = recom_df_with_aggs[['Customer_ID', 'unique_products_per_customer', 'total_items_per_customer', 'transac_per_customer', 'total_spent_per_customer', 'min_spend_per_transaction_per_customer', 'max_spend_per_transaction_per_customer', 'products_bought_by_customer', 'repeat_products_per_customer', 'num_repeat_products_per_customer', 'pct_products_repeated_per_customer', 'num_repeat_purchases_per_customer']]
customers_df = customers_df.drop_duplicates(subset=['Customer_ID'], keep='first')
customers_df

,Customer_ID,unique_products_per_customer,total_items_per_customer,transac_per_customer,total_spent_per_customer,min_spend_per_transaction_per_customer,max_spend_per_transaction_per_customer,products_bought_by_customer,repeat_products_per_customer,num_repeat_products_per_customer,pct_products_repeated_per_customer,num_repeat_purchases_per_customer
0,90fada91,1,1,1,125.0,125.0,125.0,[5002.0],NaN,0,0.000,0
1,9006f9ac,4,4,4,90.5,19.0,28.5,"[30026.5, 35012.0, 45002.5, 49291.5]",NaN,0,0.000,0
2,32270891,8,9,9,825.0,37.5,145.5,"[5000.5, 5002.0, 5005.0, 5009.0, 49291.5, 4929...",[49292.0],1,0.125,1
3,97e03e47,1,1,1,4.5,4.5,4.5,[35078.5],NaN,0,0.000,0
4,41949228,1,1,1,129.5,129.5,129.5,[49291.5],NaN,0,0.000,0
...,...,...,...,...,...,...,...,...,...,...,...,...
49986,50fef10a,1,1,1,40.5,40.5,40.5,[45004.0],NaN,0,0.000,0
49987,db8a4949,1,1,1,18.5,18.5,18.5,[49291.5],NaN,0,0.000,0
49988,2316a392,1,1,1,50.5,50.5,50.5,[49291.5],NaN,0,0.000,0
49996,a8bc484a,1,1,1,34.0,34.0,34.0,[49292.0],NaN,0,0.000,0
49998,8821da12,1,1,1,26.0,26.0,26.0,[49291.5],NaN,0,0.000,0

In [20]:
customers_df.columns

Index(['Customer_ID', 'unique_products_per_customer',
       'total_items_per_customer', 'transac_per_customer',
       'total_spent_per_customer', 'min_spend_per_transaction_per_customer',
       'max_spend_per_transaction_per_customer', 'products_bought_by_customer',
       'repeat_products_per_customer', 'num_repeat_products_per_customer',
       'pct_products_repeated_per_customer',
       'num_repeat_purchases_per_customer'],
      dtype='object')

# Recommendation System

In [80]:
interactions = (
    transactions_df
      .groupby(['Customer_ID', 'Product_ID'])['Amount']
      .size()
      .reset_index(name='quantity_purchased')
)

from sklearn.metrics.pairwise import cosine_similarity

item_user = interactions.pivot_table(
    index='Product_ID',
    columns='Customer_ID',
    values='quantity_purchased',
    fill_value=0
)

item_similarity = cosine_similarity(item_user)

item_similarity_df = pd.DataFrame(
    item_similarity,
    index=item_user.index,
    columns=item_user.index
)

customer_products = (
    interactions
      .groupby('Customer_ID')['Product_ID']
      .apply(set)
)

def recommend_for_customer(customer_id, 
                           customer_products, 
                           item_similarity_df, 
                           n=10):

    purchased = customer_products.get(customer_id, set())

    if not purchased:
        return pd.Series(dtype=float)

    scores = pd.Series(0, index=item_similarity_df.index, dtype=float)

    for product in purchased:
        if product in item_similarity_df.index:
            scores += item_similarity_df[product]

    # Remove already purchased items
    scores = scores.drop(labels=purchased, errors='ignore')

    return scores.sort_values(ascending=False).head(n)

rand_cust = recom_df['Customer_ID'].sample().iloc[0]
recommend_for_customer(rand_cust, customer_products, item_similarity_df)

Product_ID
5000.5     0.554525
49291.5    0.420996
45004.0    0.398330
25003.0    0.366037
10013.0    0.330785
5009.0     0.302729
5001.0     0.281634
48513.0    0.279049
5012.0     0.276699
5011.5     0.260326
dtype: float64

# Everything after here may be mental illness

In [21]:
def compute_picky_repeater(row):
    if row['num_repeat_products_per_customer'] == 0:
        return 0
    depth = row['num_repeat_purchases_per_customer'] / row['num_repeat_products_per_customer']
    breadth_penalty = 1 - (row['num_repeat_products_per_customer'] / row['unique_products_per_customer'])
    return depth * breadth_penalty

customers_df['picky_repeater_score'] = customers_df.apply(compute_picky_repeater, axis=1)

#
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
customers_df['picky_repeater_score_norm'] = scaler.fit_transform(
    customers_df[['picky_repeater_score']]
)

In [22]:
customers_df

,Customer_ID,unique_products_per_customer,total_items_per_customer,transac_per_customer,total_spent_per_customer,min_spend_per_transaction_per_customer,max_spend_per_transaction_per_customer,products_bought_by_customer,repeat_products_per_customer,num_repeat_products_per_customer,pct_products_repeated_per_customer,num_repeat_purchases_per_customer,picky_repeater_score,picky_repeater_score_norm
0,90fada91,1,1,1,125.0,125.0,125.0,[5002.0],NaN,0,0.000,0,0.000,0.000000
1,9006f9ac,4,4,4,90.5,19.0,28.5,"[30026.5, 35012.0, 45002.5, 49291.5]",NaN,0,0.000,0,0.000,0.000000
2,32270891,8,9,9,825.0,37.5,145.5,"[5000.5, 5002.0, 5005.0, 5009.0, 49291.5, 4929...",[49292.0],1,0.125,1,0.875,0.164062
3,97e03e47,1,1,1,4.5,4.5,4.5,[35078.5],NaN,0,0.000,0,0.000,0.000000
4,41949228,1,1,1,129.5,129.5,129.5,[49291.5],NaN,0,0.000,0,0.000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49986,50fef10a,1,1,1,40.5,40.5,40.5,[45004.0],NaN,0,0.000,0,0.000,0.000000
49987,db8a4949,1,1,1,18.5,18.5,18.5,[49291.5],NaN,0,0.000,0,0.000,0.000000
49988,2316a392,1,1,1,50.5,50.5,50.5,[49291.5],NaN,0,0.000,0,0.000,0.000000
49996,a8bc484a,1,1,1,34.0,34.0,34.0,[49292.0],NaN,0,0.000,0,0.000,0.000000
49998,8821da12,1,1,1,26.0,26.0,26.0,[49291.5],NaN,0,0.000,0,0.000,0.000000

In [23]:
customers_df.nlargest(10, 'picky_repeater_score_norm')

,Customer_ID,unique_products_per_customer,total_items_per_customer,transac_per_customer,total_spent_per_customer,min_spend_per_transaction_per_customer,max_spend_per_transaction_per_customer,products_bought_by_customer,repeat_products_per_customer,num_repeat_products_per_customer,pct_products_repeated_per_customer,num_repeat_purchases_per_customer,picky_repeater_score,picky_repeater_score_norm
665,0b464fd3,3,11,11,199.0,2.0,93.5,"[5000.5, 49292.0, 165016.5]",[165016.5],1,0.333333,8,5.333333,1.000000
14323,7d901168,8,12,12,272.0,4.0,82.0,"[10024.0, 35042.5, 35078.0, 35104.0, 49129.0, ...",[60048.0],1,0.125000,4,3.500000,0.656250
3712,457f5eba,7,11,11,477.5,15.0,92.0,"[5000.5, 5011.5, 10013.0, 35005.0, 40003.0, 40...",[49291.5],1,0.142857,4,3.428571,0.642857
4078,b2a3c605,3,8,8,277.0,21.5,66.0,"[30029.5, 49291.5, 49292.0]",[49291.5],1,0.333333,5,3.333333,0.625000
796,ec714667,16,23,21,1504.0,7.0,292.5,"[5000.5, 5009.0, 5025.0, 10003.0, 10013.0, 100...","[5000.5, 49292.0]",2,0.125000,7,3.062500,0.574219
1471,d6c57103,4,8,8,305.0,21.5,129.5,"[5027.0, 45004.0, 48504.5, 49291.5]",[48504.5],1,0.250000,4,3.000000,0.562500
1587,7c830a67,16,27,24,3237.5,64.5,293.0,"[5000.5, 5009.0, 5012.0, 10003.0, 10004.0, 100...","[5000.5, 25003.0, 48513.0]",3,0.187500,11,2.979167,0.558594
2036,86f7899a,20,23,22,4525.0,68.5,443.0,"[5000.5, 5001.0, 5004.5, 5009.0, 5012.0, 5017....",[5000.5],1,0.050000,3,2.850000,0.534375
12081,f3140e3b,13,16,15,1905.0,81.5,228.0,"[5000.5, 5001.0, 5001.5, 5012.0, 10003.0, 1002...",[5000.5],1,0.076923,3,2.769231,0.519231
10815,83bb7b79,11,14,14,773.0,2.5,122.5,"[5000.5, 5012.0, 10001.0, 10003.0, 35005.5, 40...",[49291.5],1,0.090909,3,2.727273,0.511364

In [24]:
# Flag purchases above median
recom_df_with_aggs['premium_purchase'] = recom_df_with_aggs['price_vs_median'] > 0

# Frequency of premium purchases per customer
premium_freq = recom_df_with_aggs.groupby('Customer_ID')['premium_purchase'].mean()

# Average premium per customer (ignoring non-premium purchases)
avg_premium = recom_df_with_aggs[recom_df_with_aggs['premium_purchase']].groupby('Customer_ID')['price_vs_median'].mean()

# Combine into a single metric
willingness_to_pay_score = premium_freq * avg_premium

# Merge back into a customer-level dataframe
customers_df = customers_df.merge(
    willingness_to_pay_score.rename('willingness_to_pay_score'),
    left_on='Customer_ID',
    right_index=True,
    how='left'
)

In [25]:
#
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
customers_df['willingness_to_pay_score_norm'] = scaler.fit_transform(
    customers_df[['willingness_to_pay_score']]
)

In [26]:
customers_df

,Customer_ID,unique_products_per_customer,total_items_per_customer,transac_per_customer,total_spent_per_customer,min_spend_per_transaction_per_customer,max_spend_per_transaction_per_customer,products_bought_by_customer,repeat_products_per_customer,num_repeat_products_per_customer,pct_products_repeated_per_customer,num_repeat_purchases_per_customer,picky_repeater_score,picky_repeater_score_norm,willingness_to_pay_score,willingness_to_pay_score_norm
0,90fada91,1,1,1,125.0,125.0,125.0,[5002.0],NaN,0,0.000,0,0.000,0.000000,56.000000,0.032787
1,9006f9ac,4,4,4,90.5,19.0,28.5,"[30026.5, 35012.0, 45002.5, 49291.5]",NaN,0,0.000,0,0.000,0.000000,2.062500,0.001179
2,32270891,8,9,9,825.0,37.5,145.5,"[5000.5, 5002.0, 5005.0, 5009.0, 49291.5, 4929...",[49292.0],1,0.125,1,0.875,0.164062,28.583333,0.016721
3,97e03e47,1,1,1,4.5,4.5,4.5,[35078.5],NaN,0,0.000,0,0.000,0.000000,NaN,NaN
4,41949228,1,1,1,129.5,129.5,129.5,[49291.5],NaN,0,0.000,0,0.000,0.000000,94.500000,0.055349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49986,50fef10a,1,1,1,40.5,40.5,40.5,[45004.0],NaN,0,0.000,0,0.000,0.000000,NaN,NaN
49987,db8a4949,1,1,1,18.5,18.5,18.5,[49291.5],NaN,0,0.000,0,0.000,0.000000,NaN,NaN
49988,2316a392,1,1,1,50.5,50.5,50.5,[49291.5],NaN,0,0.000,0,0.000,0.000000,15.500000,0.009054
49996,a8bc484a,1,1,1,34.0,34.0,34.0,[49292.0],NaN,0,0.000,0,0.000,0.000000,NaN,NaN
49998,8821da12,1,1,1,26.0,26.0,26.0,[49291.5],NaN,0,0.000,0,0.000,0.000000,NaN,NaN

In [27]:
customers_df['prs * wps'] = customers_df['picky_repeater_score_norm'] + customers_df['willingness_to_pay_score_norm']
customers_df

,Customer_ID,unique_products_per_customer,total_items_per_customer,transac_per_customer,total_spent_per_customer,min_spend_per_transaction_per_customer,max_spend_per_transaction_per_customer,products_bought_by_customer,repeat_products_per_customer,num_repeat_products_per_customer,pct_products_repeated_per_customer,num_repeat_purchases_per_customer,picky_repeater_score,picky_repeater_score_norm,willingness_to_pay_score,willingness_to_pay_score_norm,prs * wps
0,90fada91,1,1,1,125.0,125.0,125.0,[5002.0],NaN,0,0.000,0,0.000,0.000000,56.000000,0.032787,0.032787
1,9006f9ac,4,4,4,90.5,19.0,28.5,"[30026.5, 35012.0, 45002.5, 49291.5]",NaN,0,0.000,0,0.000,0.000000,2.062500,0.001179,0.001179
2,32270891,8,9,9,825.0,37.5,145.5,"[5000.5, 5002.0, 5005.0, 5009.0, 49291.5, 4929...",[49292.0],1,0.125,1,0.875,0.164062,28.583333,0.016721,0.180783
3,97e03e47,1,1,1,4.5,4.5,4.5,[35078.5],NaN,0,0.000,0,0.000,0.000000,NaN,NaN,NaN
4,41949228,1,1,1,129.5,129.5,129.5,[49291.5],NaN,0,0.000,0,0.000,0.000000,94.500000,0.055349,0.055349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49986,50fef10a,1,1,1,40.5,40.5,40.5,[45004.0],NaN,0,0.000,0,0.000,0.000000,NaN,NaN,NaN
49987,db8a4949,1,1,1,18.5,18.5,18.5,[49291.5],NaN,0,0.000,0,0.000,0.000000,NaN,NaN,NaN
49988,2316a392,1,1,1,50.5,50.5,50.5,[49291.5],NaN,0,0.000,0,0.000,0.000000,15.500000,0.009054,0.009054
49996,a8bc484a,1,1,1,34.0,34.0,34.0,[49292.0],NaN,0,0.000,0,0.000,0.000000,NaN,NaN,NaN
49998,8821da12,1,1,1,26.0,26.0,26.0,[49291.5],NaN,0,0.000,0,0.000,0.000000,NaN,NaN,NaN

In [28]:
customers_df.nlargest(10, 'prs * wps')

,Customer_ID,unique_products_per_customer,total_items_per_customer,transac_per_customer,total_spent_per_customer,min_spend_per_transaction_per_customer,max_spend_per_transaction_per_customer,products_bought_by_customer,repeat_products_per_customer,num_repeat_products_per_customer,pct_products_repeated_per_customer,num_repeat_purchases_per_customer,picky_repeater_score,picky_repeater_score_norm,willingness_to_pay_score,willingness_to_pay_score_norm,prs * wps
665,0b464fd3,3,11,11,199.0,2.0,93.5,"[5000.5, 49292.0, 165016.5]",[165016.5],1,0.333333,8,5.333333,1.000000,5.727273,0.003327,1.003327
20049,0b5481de,1,1,1,1780.0,1780.0,1780.0,[48513.0],NaN,0,0.000000,0,0.000000,0.000000,1706.500000,1.000000,1.000000
10437,ba30b14a,3,3,2,4319.5,44.5,4275.0,"[5011.5, 10004.0, 10032.5]",NaN,0,0.000000,0,0.000000,0.000000,1370.833333,0.803295,0.803295
14323,7d901168,8,12,12,272.0,4.0,82.0,"[10024.0, 35042.5, 35078.0, 35104.0, 49129.0, ...",[60048.0],1,0.125000,4,3.500000,0.656250,6.645833,0.003865,0.660115
3712,457f5eba,7,11,11,477.5,15.0,92.0,"[5000.5, 5011.5, 10013.0, 35005.0, 40003.0, 40...",[49291.5],1,0.142857,4,3.428571,0.642857,14.500000,0.008468,0.651325
4078,b2a3c605,3,8,8,277.0,21.5,66.0,"[30029.5, 49291.5, 49292.0]",[49291.5],1,0.333333,5,3.333333,0.625000,5.437500,0.003157,0.628157
2036,86f7899a,20,23,22,4525.0,68.5,443.0,"[5000.5, 5001.0, 5004.5, 5009.0, 5012.0, 5017....",[5000.5],1,0.050000,3,2.850000,0.534375,117.391304,0.068763,0.603138
1587,7c830a67,16,27,24,3237.5,64.5,293.0,"[5000.5, 5009.0, 5012.0, 10003.0, 10004.0, 100...","[5000.5, 25003.0, 48513.0]",3,0.187500,11,2.979167,0.558594,49.370370,0.028902,0.587496
796,ec714667,16,23,21,1504.0,7.0,292.5,"[5000.5, 5009.0, 5025.0, 10003.0, 10013.0, 100...","[5000.5, 49292.0]",2,0.125000,7,3.062500,0.574219,19.250000,0.011251,0.585470
11504,2010446f,1,1,1,1033.5,1033.5,1033.5,[49291.5],NaN,0,0.000000,0,0.000000,0.000000,998.500000,0.585104,0.585104

# Next
Find products associated with frequently high willingness to pay a premium.

In [31]:
import pandas as pd
import ast


# Explode directly without ast.literal_eval
cust_prod_df = customers_df[['Customer_ID', 'willingness_to_pay_score_norm', 'products_bought_by_customer']].explode('products_bought_by_customer')

# Rename column for clarity
cust_prod_df = cust_prod_df.rename(columns={'products_bought_by_customer': 'Product_ID'})

# Optional: make Product_ID match type in products_df
cust_prod_df['Product_ID'] = cust_prod_df['Product_ID'].astype(products_df['Product_ID'].dtype)

product_wtp = cust_prod_df.groupby('Product_ID')['willingness_to_pay_score_norm'].agg(['mean', 'median', 'count']).reset_index()
product_wtp = product_wtp.rename(columns={'mean': 'avg_wtp_score', 'median': 'median_wtp_score', 'count': 'num_customers'})

# Merge back into products_df
products_df = products_df.merge(product_wtp, on='Product_ID', how='left')

In [32]:
product_wtp = cust_prod_df.groupby('Product_ID')['willingness_to_pay_score_norm'].agg(['mean', 'median', 'count']).reset_index()
product_wtp = product_wtp.rename(columns={'mean': 'avg_wtp_score', 'median': 'median_wtp_score', 'count': 'num_customers'})

# Merge back into products_df
products_df = products_df.merge(product_wtp, on='Product_ID', how='left')

In [33]:
products_df

,Product_ID,Customer_ID,median_price_per_product,max_price_per_product,min_price_per_product,unique_customers_per_product,total_sold_per_product,total_revenue_per_product,repeat_customers_per_product,pct_repeat_customers_per_product,avg_wtp_score_x,median_wtp_score_x,num_customers_x,avg_wtp_score_y,median_wtp_score_y,num_customers_y
0,5002.0,90fada91,69.00,776.0,1.0,660,796.0,77445.5,42,0.063636,0.026716,0.019114,439,0.026716,0.019114,439
1,35012.0,9006f9ac,15.25,107.0,5.0,8,8.0,195.5,0,0.000000,0.017487,0.002119,7,0.017487,0.002119,7
2,5005.0,32270891,136.25,1574.5,61.0,44,68.0,22259.5,4,0.090909,0.069178,0.025517,32,0.069178,0.025517,32
3,35078.5,97e03e47,7.00,64.0,4.0,132,189.0,1908.0,10,0.075758,0.006620,0.002364,94,0.006620,0.002364,94
4,49291.5,41949228,35.00,1033.5,0.5,4127,5706.0,294453.5,403,0.097650,0.014716,0.009371,2506,0.014716,0.009371,2506
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,60051.0,a1fedd5e,48.00,48.0,48.0,1,3.0,144.0,0,0.000000,NaN,NaN,0,NaN,NaN,0
329,35072.0,9704c040,25.50,25.5,25.5,1,1.0,25.5,0,0.000000,NaN,NaN,0,NaN,NaN,0
330,20034.0,df4ce5ac,344.50,344.5,344.5,1,1.0,344.5,0,0.000000,0.089142,0.089142,1,0.089142,0.089142,1
331,48590.0,b4db2269,52.50,52.5,52.5,1,1.0,52.5,0,0.000000,0.046212,0.046212,1,0.046212,0.046212,1
332,35008.0,74746892,10.00,10.0,10.0,1,2.0,20.0,0,0.000000,NaN,NaN,0,NaN,NaN,0

# Recommendation System

In [ ]:
I will use customer data to find similar profiles of customers.