This dataset is relatively clean to begin with. However, we will make small adjustments for clarity.

In [1]:
import pandas as pd

Rk -- Rank
IP -- Innings Pitched
From -- From Season
To -- To Season
W -- Wins
L -- Losses
W-L% -- Win-Loss Percentage
W / (W + L)
For players, leaders need one decision for every ten team games.
Dec -- Decisions
Wins plus Losses.
ERA -- 9 * ER / IP
For recent years, leaders need 1 IP
per team game played.
Bold indicates lowest ERA using current stats
Gold means awarded ERA title at end of year.
G -- Games Pitched
GS -- Games Started
CG -- Complete Games
SHO -- Shutouts
No runs allowed and a complete game.
SV -- Saves
H -- Hits Allowed
R -- Runs Allowed
ER -- Earned Runs Allowed
HR -- Home Runs Allowed
BB -- Bases on Balls/Walks
IBB -- Intentional Bases on Balls
First tracked in 1955.
SO -- Strikeouts
HBP -- Times Hit by a Pitch
BK -- Balks
WP -- Wild Pitches
BF -- Batters Faced
ERA+ -- ERA+
100*[lgERA/ERA]
Adjusted to the player’s ballpark(s).
FIP -- Fielding Independent Pitching
this stat measures a pitcher's effectiveness at preventing HR, BB, HBP and causing SO
(13*HR + 3*(BB+HBP) - 2*SO)/IP + Constantlg
The constant is set so that each season major-league average FIP is the same as the major-league avg ERA
WHIP -- (BB + H)/IP
For recent years, leaders need 1 IP
per team game played
H9 -- 9 x H / IP
For recent years, leaders need 1 IP
per team game played
HR9 -- 9 x HR / IP
For recent years, leaders need 1 IP
per team game played
BB9 -- 9 x BB / IP
For recent years, leaders need 1 IP
per team game played
SO9 -- 9 x SO / IP
For recent years, leaders need 1 IP
per team game played
SO/BB -- SO/W or SO/BB
For recent years, pitching leaders need 1 IP
per team game played.
Pos -- Positions Played
The positions either followed by the games played at that position
or in order of games or innings played.
For a single season, * indicates they played at least 2/3rds of the team games there.
Positions after / indicate less than ten games played at those positions.
For career, a + sign means more than 300 games at that position and
a - sign means less than 30 games.
'H' indicates games as a pinch-hitter or pinch-runner.

In [2]:
all_pitchers_df = pd.read_csv('Pitchers All min 1000 IP.txt')
all_pitchers_df

,Rk,Player,IP,From,To,Age,W,L,W-L%,Dec,...,FIP,WHIP,H9,HR9,BB9,SO9,SO/BB,Pos,Team,Player-additional
0,1,Cy Young,7356.0,1890,1911,23-44,511,315,0.619,826,...,2.84,1.130,8.7,0.2,1.5,3.4,2.30,1/3H,BOSBSNCLECLVSTL,youngcy01
1,2,Pud Galvin,6003.1,1875,1892,18-35,365,310,0.541,675,...,2.96,1.191,9.6,0.2,1.1,2.7,2.43,1O/6,BUFPBBPITSTL,galvipu01
2,3,Walter Johnson,5914.1,1907,1927,19-39,417,279,0.599,696,...,2.38,1.061,7.5,0.1,2.1,5.3,2.57,1H/8974,WSH,johnswa01
3,4,Phil Niekro,5404.0,1964,1987,25-48,318,274,0.537,592,...,3.62,1.268,8.4,0.8,3.0,5.6,1.85,1/H,ATLCLEMLNNYYTOR,niekrph01
4,5,Nolan Ryan,5386.0,1966,1993,19-46,324,292,0.526,616,...,2.97,1.247,6.6,0.5,4.7,9.5,2.04,1,CALHOUNYMTEX,ryanno01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,1211,Charlie Robertson,1005.0,1919,1928,23-32,49,80,0.380,129,...,3.89,1.518,10.3,0.3,3.4,2.8,0.82,1,BSNCHWSLB,roberch01
1211,1212,Sammy Ellis,1004.0,1962,1969,21-28,63,58,0.521,121,...,3.90,1.340,8.7,1.1,3.4,6.1,1.79,1/H,CALCHWCIN,ellissa01
1212,1213,Lil Stoner,1003.2,1922,1931,23-32,50,57,0.467,107,...,4.13,1.548,10.6,0.6,3.4,2.7,0.80,1/4,DETPHIPIT,stoneli01
1213,1214,Johnny Humphries,1002.0,1938,1946,23-31,52,63,0.452,115,...,3.80,1.394,9.2,0.4,3.4,2.8,0.85,1,CHWCLEPHI,humphjo02
1214,1215,Scott Karl,1002.0,1995,2000,23-28,54,56,0.491,110,...,4.87,1.530,10.5,1.1,3.3,4.6,1.39,1/H,ANACOLMIL,karlsc01

In [3]:
all_pitchers_df[['Debut Age', 'Retirement Age']] = all_pitchers_df['Age'].str.split('-', expand=True).astype(int)
all_pitchers_df

,Rk,Player,IP,From,To,Age,W,L,W-L%,Dec,...,H9,HR9,BB9,SO9,SO/BB,Pos,Team,Player-additional,Debut Age,Retirement Age
0,1,Cy Young,7356.0,1890,1911,23-44,511,315,0.619,826,...,8.7,0.2,1.5,3.4,2.30,1/3H,BOSBSNCLECLVSTL,youngcy01,23,44
1,2,Pud Galvin,6003.1,1875,1892,18-35,365,310,0.541,675,...,9.6,0.2,1.1,2.7,2.43,1O/6,BUFPBBPITSTL,galvipu01,18,35
2,3,Walter Johnson,5914.1,1907,1927,19-39,417,279,0.599,696,...,7.5,0.1,2.1,5.3,2.57,1H/8974,WSH,johnswa01,19,39
3,4,Phil Niekro,5404.0,1964,1987,25-48,318,274,0.537,592,...,8.4,0.8,3.0,5.6,1.85,1/H,ATLCLEMLNNYYTOR,niekrph01,25,48
4,5,Nolan Ryan,5386.0,1966,1993,19-46,324,292,0.526,616,...,6.6,0.5,4.7,9.5,2.04,1,CALHOUNYMTEX,ryanno01,19,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,1211,Charlie Robertson,1005.0,1919,1928,23-32,49,80,0.380,129,...,10.3,0.3,3.4,2.8,0.82,1,BSNCHWSLB,roberch01,23,32
1211,1212,Sammy Ellis,1004.0,1962,1969,21-28,63,58,0.521,121,...,8.7,1.1,3.4,6.1,1.79,1/H,CALCHWCIN,ellissa01,21,28
1212,1213,Lil Stoner,1003.2,1922,1931,23-32,50,57,0.467,107,...,10.6,0.6,3.4,2.7,0.80,1/4,DETPHIPIT,stoneli01,23,32
1213,1214,Johnny Humphries,1002.0,1938,1946,23-31,52,63,0.452,115,...,9.2,0.4,3.4,2.8,0.85,1,CHWCLEPHI,humphjo02,23,31
1214,1215,Scott Karl,1002.0,1995,2000,23-28,54,56,0.491,110,...,10.5,1.1,3.3,4.6,1.39,1/H,ANACOLMIL,karlsc01,23,28

In [4]:
all_pitchers_df.columns

Index(['Rk', 'Player', 'IP', 'From', 'To', 'Age', 'W', 'L', 'W-L%', 'Dec',
       'ERA', 'G', 'GS', 'CG', 'SHO', 'SV', 'IP.1', 'H', 'R', 'ER', 'HR', 'BB',
       'IBB', 'SO', 'HBP', 'BK', 'WP', 'BF', 'ERA+', 'FIP', 'WHIP', 'H9',
       'HR9', 'BB9', 'SO9', 'SO/BB', 'Pos', 'Team', 'Player-additional',
       'Debut Age', 'Retirement Age'],
      dtype='object')

In [5]:
# Innings Pitched rank, artifact of how Stathead displays query results.
all_pitchers_df.drop('Rk', axis=1, inplace=True)

all_pitchers_df.rename(columns={'IP': 'Innings Pitched'}, inplace=True)
all_pitchers_df.rename(columns={'From': 'Debut Year'}, inplace=True)
all_pitchers_df.rename(columns={'To': 'Retirement Year'}, inplace=True)
all_pitchers_df.rename(columns={'W': 'Wins'}, inplace=True)
all_pitchers_df.rename(columns={'L': 'Losses'}, inplace=True)
all_pitchers_df.rename(columns={'W-L%': 'Win Percentage'}, inplace=True)
all_pitchers_df.rename(columns={'Dec': 'Total Decisions'}, inplace=True)
all_pitchers_df.rename(columns={'ERA': 'Earned Run Average'}, inplace=True)
all_pitchers_df.rename(columns={'G': 'Total Games'}, inplace=True)
all_pitchers_df.rename(columns={'GS': 'Games Started'}, inplace=True)
all_pitchers_df.rename(columns={'CG': 'Complete Games'}, inplace=True)
all_pitchers_df.rename(columns={'SHO': 'Shutouts'}, inplace=True)
all_pitchers_df.rename(columns={'SV': 'Saves'}, inplace=True)

# Duplicate of Innings Pitched, artifact of how Stathead displays query results
all_pitchers_df.drop('IP.1', axis=1, inplace=True)

all_pitchers_df.rename(columns={'H': 'Hits Allowed'}, inplace=True)
all_pitchers_df.rename(columns={'R': 'Runs Allowed'}, inplace=True)
all_pitchers_df.rename(columns={'ER': 'Earned Runs Allowed'}, inplace=True)
all_pitchers_df.rename(columns={'HR': 'Home Runs Allowed'}, inplace=True)
all_pitchers_df.rename(columns={'BB': 'Walks Allowed'}, inplace=True)

# May drop this as it was not tracked until 1955.
all_pitchers_df.rename(columns={'IBB': 'Intentional Walks Allowed'}, inplace=True)

all_pitchers_df.rename(columns={'SO': 'Strikeouts'}, inplace=True)
all_pitchers_df.rename(columns={'HBP': 'Batters Hit By Pitch'}, inplace=True)
all_pitchers_df.rename(columns={'BK': 'Balks'}, inplace=True)
all_pitchers_df.rename(columns={'WP': 'Wild Pitches'}, inplace=True)

all_pitchers_df.rename(columns={'BP': 'Batters Faced'}, inplace=True)
#all_pitchers_df.rename(columns={'ERA+': 'Ballpark Adjusted ERA'}, inplace=True)
#all_pitchers_df.rename(columns={'FIP': 'Fielding Independent Pitching'}, inplace=True)
#all_pitchers_df.rename(columns={'WHIP': 'Walks Plus Hits Per Inning Pitched'}, inplace=True)
#all_pitchers_df.rename(columns={'H9': 'Hits Per 9 Innings Pitched'}, inplace=True)
#all_pitchers_df.rename(columns={'HR9': 'Year'}, inplace=True)

# Tracks other positions the pitcher may have played at some point. Unfair comparison, so dropping.
all_pitchers_df.drop('Pos', axis=1, inplace=True)

# Lists every MLB the pitcher played for. Unfair comparison, so dropping.
all_pitchers_df.drop('Team', axis=1, inplace=True)

In [6]:
# New columns
all_pitchers_df[['Debut Age', 'Retirement Age']] = all_pitchers_df['Age'].str.split('-', expand=True).astype(int)
all_pitchers_df.drop('Age', axis=1, inplace=True)

all_pitchers_df['Relief Appearances'] = all_pitchers_df['Total Games'] - all_pitchers_df['Games Started']

all_pitchers_df['Career Length'] = all_pitchers_df['Retirement Year'] - all_pitchers_df['Debut Year']

In [7]:
all_pitchers_df.columns

Index(['Player', 'Innings Pitched', 'Debut Year', 'Retirement Year', 'Wins',
       'Losses', 'Win Percentage', 'Total Decisions', 'Earned Run Average',
       'Total Games', 'Games Started', 'Complete Games', 'Shutouts', 'Saves',
       'Hits Allowed', 'Runs Allowed', 'Earned Runs Allowed',
       'Home Runs Allowed', 'Walks Allowed', 'Intentional Walks Allowed',
       'Strikeouts', 'Batters Hit By Pitch', 'Balks', 'Wild Pitches', 'BF',
       'ERA+', 'FIP', 'WHIP', 'H9', 'HR9', 'BB9', 'SO9', 'SO/BB',
       'Player-additional', 'Debut Age', 'Retirement Age',
       'Relief Appearances', 'Career Length'],
      dtype='object')

In [8]:
all_pitchers_df = all_pitchers_df[['Player', 'Debut Year', 'Debut Age', 'Retirement Year', 'Retirement Age',
       'Career Length', 'Wins', 'Losses', 'Win Percentage', 'Total Decisions',
       'Earned Run Average', 'Total Games', 'Games Started', 'Relief Appearances', 'Complete Games',
       'Shutouts', 'Saves', 'Innings Pitched', 'Hits Allowed', 'Runs Allowed',
       'Earned Runs Allowed', 'Home Runs Allowed', 'Walks Allowed',
       'Intentional Walks Allowed', 'Strikeouts', 'Batters Hit By Pitch',
       'Balks', 'Wild Pitches', 'BF', 'ERA+', 'FIP', 'WHIP', 'H9', 'HR9',
       'BB9', 'SO9', 'SO/BB', 'Player-additional']]

In [9]:
all_pitchers_df

,Player,Debut Year,Debut Age,Retirement Year,Retirement Age,Career Length,Wins,Losses,Win Percentage,Total Decisions,...,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/BB,Player-additional
0,Cy Young,1890,23,1911,44,21,511,315,0.619,826,...,29565,138,2.84,1.130,8.7,0.2,1.5,3.4,2.30,youngcy01
1,Pud Galvin,1875,18,1892,35,17,365,310,0.541,675,...,25415,107,2.96,1.191,9.6,0.2,1.1,2.7,2.43,galvipu01
2,Walter Johnson,1907,19,1927,39,20,417,279,0.599,696,...,23415,147,2.38,1.061,7.5,0.1,2.1,5.3,2.57,johnswa01
3,Phil Niekro,1964,25,1987,48,23,318,274,0.537,592,...,22677,115,3.62,1.268,8.4,0.8,3.0,5.6,1.85,niekrph01
4,Nolan Ryan,1966,19,1993,46,27,324,292,0.526,616,...,22575,112,2.97,1.247,6.6,0.5,4.7,9.5,2.04,ryanno01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,Charlie Robertson,1919,23,1928,32,9,49,80,0.380,129,...,4453,90,3.89,1.518,10.3,0.3,3.4,2.8,0.82,roberch01
1211,Sammy Ellis,1962,21,1969,28,7,63,58,0.521,121,...,4296,88,3.90,1.340,8.7,1.1,3.4,6.1,1.79,ellissa01
1212,Lil Stoner,1922,23,1931,32,9,50,57,0.467,107,...,4466,87,4.13,1.548,10.6,0.6,3.4,2.7,0.80,stoneli01
1213,Johnny Humphries,1938,23,1946,31,8,52,63,0.452,115,...,4342,97,3.80,1.394,9.2,0.4,3.4,2.8,0.85,humphjo02
1214,Scott Karl,1995,23,2000,28,5,54,56,0.491,110,...,4444,100,4.87,1.530,10.5,1.1,3.3,4.6,1.39,karlsc01

In [10]:
all_pitchers_df

,Player,Debut Year,Debut Age,Retirement Year,Retirement Age,Career Length,Wins,Losses,Win Percentage,Total Decisions,...,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/BB,Player-additional
0,Cy Young,1890,23,1911,44,21,511,315,0.619,826,...,29565,138,2.84,1.130,8.7,0.2,1.5,3.4,2.30,youngcy01
1,Pud Galvin,1875,18,1892,35,17,365,310,0.541,675,...,25415,107,2.96,1.191,9.6,0.2,1.1,2.7,2.43,galvipu01
2,Walter Johnson,1907,19,1927,39,20,417,279,0.599,696,...,23415,147,2.38,1.061,7.5,0.1,2.1,5.3,2.57,johnswa01
3,Phil Niekro,1964,25,1987,48,23,318,274,0.537,592,...,22677,115,3.62,1.268,8.4,0.8,3.0,5.6,1.85,niekrph01
4,Nolan Ryan,1966,19,1993,46,27,324,292,0.526,616,...,22575,112,2.97,1.247,6.6,0.5,4.7,9.5,2.04,ryanno01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,Charlie Robertson,1919,23,1928,32,9,49,80,0.380,129,...,4453,90,3.89,1.518,10.3,0.3,3.4,2.8,0.82,roberch01
1211,Sammy Ellis,1962,21,1969,28,7,63,58,0.521,121,...,4296,88,3.90,1.340,8.7,1.1,3.4,6.1,1.79,ellissa01
1212,Lil Stoner,1922,23,1931,32,9,50,57,0.467,107,...,4466,87,4.13,1.548,10.6,0.6,3.4,2.7,0.80,stoneli01
1213,Johnny Humphries,1938,23,1946,31,8,52,63,0.452,115,...,4342,97,3.80,1.394,9.2,0.4,3.4,2.8,0.85,humphjo02
1214,Scott Karl,1995,23,2000,28,5,54,56,0.491,110,...,4444,100,4.87,1.530,10.5,1.1,3.3,4.6,1.39,karlsc01

In [11]:
all_star_count = pd.read_csv('Pitchers All Star count.txt')
all_star_count.rename(columns={'Count': 'All Star Appearances'}, inplace=True)
all_star_count = all_star_count[['Player', 'Player-additional', 'All Star Appearances']]
all_star_count

             Player Player-additional  All Star Appearances
0      Warren Spahn         spahnwa01                    14
1    Mariano Rivera         riverma01                    13
2        Tom Seaver         seaveto01                    12
3     Roger Clemens         clemero02                    11
4       Tom Glavine         glavito02                    10
..              ...               ...                   ...
767     Bert Hunter         huntebe01                     1
768       Babe Ruth          ruthba01                     1
769    Sam Streeter         streesa01                     1
770    Mule Suttles         suttlmu99                     1
771      Jim Willis         williji05                     1

[772 rows x 3 columns]

In [12]:
hall_of_fame_df = pd.read_csv('Pitchers HOF.txt')
hall_of_fame_df = hall_of_fame_df[['Player', 'Player-additional']]
hall_of_fame_df

             Player Player-additional
0          Cy Young         youngcy01
1        Pud Galvin         galvipu01
2    Walter Johnson         johnswa01
3       Phil Niekro         niekrph01
4        Nolan Ryan          ryanno01
..              ...               ...
119    Tris Speaker         speaktr01
120   Ichiro Suzuki         suzukic01
121    Willie Wells         wellswi99
122       Pete Hill          hillpe99
123     Stan Musial         musiast01

[124 rows x 2 columns]

Merging with HOF data.

In [13]:
all_pitchers_df['Hall of Fame'] = all_pitchers_df['Player-additional'].isin(
    hall_of_fame_df['Player-additional']
).astype(int)

/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_93970/1612717278.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_pitchers_df['Hall of Fame'] = all_pitchers_df['Player-additional'].isin(

In [14]:
all_pitchers_df

,Player,Debut Year,Debut Age,Retirement Year,Retirement Age,Career Length,Wins,Losses,Win Percentage,Total Decisions,...,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/BB,Player-additional,Hall of Fame
0,Cy Young,1890,23,1911,44,21,511,315,0.619,826,...,138,2.84,1.130,8.7,0.2,1.5,3.4,2.30,youngcy01,1
1,Pud Galvin,1875,18,1892,35,17,365,310,0.541,675,...,107,2.96,1.191,9.6,0.2,1.1,2.7,2.43,galvipu01,1
2,Walter Johnson,1907,19,1927,39,20,417,279,0.599,696,...,147,2.38,1.061,7.5,0.1,2.1,5.3,2.57,johnswa01,1
3,Phil Niekro,1964,25,1987,48,23,318,274,0.537,592,...,115,3.62,1.268,8.4,0.8,3.0,5.6,1.85,niekrph01,1
4,Nolan Ryan,1966,19,1993,46,27,324,292,0.526,616,...,112,2.97,1.247,6.6,0.5,4.7,9.5,2.04,ryanno01,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,Charlie Robertson,1919,23,1928,32,9,49,80,0.380,129,...,90,3.89,1.518,10.3,0.3,3.4,2.8,0.82,roberch01,0
1211,Sammy Ellis,1962,21,1969,28,7,63,58,0.521,121,...,88,3.90,1.340,8.7,1.1,3.4,6.1,1.79,ellissa01,0
1212,Lil Stoner,1922,23,1931,32,9,50,57,0.467,107,...,87,4.13,1.548,10.6,0.6,3.4,2.7,0.80,stoneli01,0
1213,Johnny Humphries,1938,23,1946,31,8,52,63,0.452,115,...,97,3.80,1.394,9.2,0.4,3.4,2.8,0.85,humphjo02,0
1214,Scott Karl,1995,23,2000,28,5,54,56,0.491,110,...,100,4.87,1.530,10.5,1.1,3.3,4.6,1.39,karlsc01,0

Merging with All Star count.

In [15]:
# Merge the All-Star counts into all_pitchers_df
all_pitchers_df = all_pitchers_df.merge(
    all_star_count[['Player-additional', 'All Star Appearances']],  # ensure only needed columns
    on='Player-additional',
    how='left'
)

# Replace missing values (players with no All-Star appearances) with 0
all_pitchers_df['All Star Appearances'] = all_pitchers_df['All Star Appearances'].fillna(0).astype(int)

In [16]:
all_pitchers_df

,Player,Debut Year,Debut Age,Retirement Year,Retirement Age,Career Length,Wins,Losses,Win Percentage,Total Decisions,...,FIP,WHIP,H9,HR9,BB9,SO9,SO/BB,Player-additional,Hall of Fame,All Star Appearances
0,Cy Young,1890,23,1911,44,21,511,315,0.619,826,...,2.84,1.130,8.7,0.2,1.5,3.4,2.30,youngcy01,1,0
1,Pud Galvin,1875,18,1892,35,17,365,310,0.541,675,...,2.96,1.191,9.6,0.2,1.1,2.7,2.43,galvipu01,1,0
2,Walter Johnson,1907,19,1927,39,20,417,279,0.599,696,...,2.38,1.061,7.5,0.1,2.1,5.3,2.57,johnswa01,1,0
3,Phil Niekro,1964,25,1987,48,23,318,274,0.537,592,...,3.62,1.268,8.4,0.8,3.0,5.6,1.85,niekrph01,1,5
4,Nolan Ryan,1966,19,1993,46,27,324,292,0.526,616,...,2.97,1.247,6.6,0.5,4.7,9.5,2.04,ryanno01,1,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,Charlie Robertson,1919,23,1928,32,9,49,80,0.380,129,...,3.89,1.518,10.3,0.3,3.4,2.8,0.82,roberch01,0,0
1211,Sammy Ellis,1962,21,1969,28,7,63,58,0.521,121,...,3.90,1.340,8.7,1.1,3.4,6.1,1.79,ellissa01,0,1
1212,Lil Stoner,1922,23,1931,32,9,50,57,0.467,107,...,4.13,1.548,10.6,0.6,3.4,2.7,0.80,stoneli01,0,0
1213,Johnny Humphries,1938,23,1946,31,8,52,63,0.452,115,...,3.80,1.394,9.2,0.4,3.4,2.8,0.85,humphjo02,0,0
1214,Scott Karl,1995,23,2000,28,5,54,56,0.491,110,...,4.87,1.530,10.5,1.1,3.3,4.6,1.39,karlsc01,0,0

Resolve player name ambiguities

In [17]:
all_pitchers_df['Player'].value_counts()

Player
Joe Coleman           2
Jim Bagby             2
Jack Taylor           2
Bill Swift            2
Dutch Leonard         2
                     ..
Casey Patten          1
Steve Gromek          1
Jim Barr              1
Fritz Ostermueller    1
Scott Karl            1
Name: count, Length: 1208, dtype: int64

# Create a new disambiguated player name
all_pitchers_df['Player'] = all_pitchers_df['Player'] + ' (' + all_pitchers_df['Player-additional'].astype(str) + ')'

In [18]:
# Identify player names that appear more than once
duplicates = all_pitchers_df['Player'].duplicated(keep=False)

# For those duplicates, append the unique code from 'Player-additional'
all_pitchers_df.loc[duplicates, 'Player'] = (
    all_pitchers_df.loc[duplicates, 'Player']
    + ' (' + all_pitchers_df.loc[duplicates, 'Player-additional'].astype(str) + ')'
)

In [19]:
all_pitchers_df[all_pitchers_df['Player'].str.contains('Joe Coleman')]

,Player,Debut Year,Debut Age,Retirement Year,Retirement Age,Career Length,Wins,Losses,Win Percentage,Total Decisions,...,FIP,WHIP,H9,HR9,BB9,SO9,SO/BB,Player-additional,Hall of Fame,All Star Appearances
227,Joe Coleman (colemjo05),1965,18,1979,32,14,142,135,0.513,277,...,3.65,1.331,8.5,0.8,3.5,6.1,1.72,colemjo05,0,1
1070,Joe Coleman (colemjo04),1942,19,1955,32,13,52,76,0.406,128,...,4.36,1.533,9.3,0.7,4.5,3.5,0.78,colemjo04,0,1

In [20]:
all_pitchers_df['Hall of Fame'].value_counts()

Hall of Fame
0    1133
1      82
Name: count, dtype: int64

Nothing went wrong here, though I had to check. This is an artifact of occasional pitching appearances by non-pitchers, which usually occurs only in desperate situations. Thus, even though 124 players with at least one pitching appearance are in the Hall of Fame, only 82 of those met the 1000 innings requirement.

In [22]:
all_pitchers_df['Player'].nunique()

1215

In [23]:
all_pitchers_df['Player-additional'].nunique()

1215

We have successfully verified that all player name are disambiguated, so now we can drop the Player-additional column.

In [24]:
all_pitchers_df.drop('Player-additional', axis=1, inplace=True)

The All-Star question?

The MLB All-Star game was not introduced until 1933. Some players in this dataset played in leagues which are retroactively recognized as major leagues, such as the Negro Leagues, and thus were not in MLB. Additionally, there are further non-statistical factors regarding All-Star selection. Because of this, I am dropping it here. However, its integration into the dataset further back in this notebook will remain, so that it can be re-included simply by commenting out the following cell.

In [27]:
all_pitchers_df.drop('All Star Appearances', axis=1, inplace=True)

In [29]:
all_pitchers_df.isnull().sum()

Player                         0
Debut Year                     0
Debut Age                      0
Retirement Year                0
Retirement Age                 0
Career Length                  0
Wins                           0
Losses                         0
Win Percentage                 0
Total Decisions                0
Earned Run Average             0
Total Games                    0
Games Started                  0
Relief Appearances             0
Complete Games                 0
Shutouts                       0
Saves                          0
Innings Pitched                0
Hits Allowed                   0
Runs Allowed                   0
Earned Runs Allowed            0
Home Runs Allowed              0
Walks Allowed                  0
Intentional Walks Allowed    285
Strikeouts                     0
Batters Hit By Pitch           9
Balks                          2
Wild Pitches                   0
BF                             0
ERA+                           0
FIP                            0
WHIP                           0
H9                             0
HR9                            0
BB9                            0
SO9                            0
SO/BB                          0
Hall of Fame                   0
dtype: int64

In [30]:
all_pitchers_df = all_pitchers_df.fillna(0)

In [31]:
all_pitchers_df.to_csv('All Pitchers Cleaned.csv', index=False)