In [2]:
import pandas as pd

url = "https://www.europarl.europa.eu/meps/en/full-list/xml"

df = pd.read_xml(url)
df.head()

,fullName,country,politicalGroup,id,nationalPoliticalGroup
0,Mika AALTOLA,Finland,Group of the European People's Party (Christia...,256810,Kansallinen Kokoomus
1,Maravillas ABADÍA JOVER,Spain,Group of the European People's Party (Christia...,257043,Partido Popular
2,Magdalena ADAMOWICZ,Poland,Group of the European People's Party (Christia...,197490,Independent
3,Georgios AFTIAS,Greece,Group of the European People's Party (Christia...,256820,Nea Demokratia
4,Oihane AGIRREGOITIA MARTÍNEZ,Spain,Renew Europe Group,256987,Partido Nacionalista Vasco

In [3]:
df

,fullName,country,politicalGroup,id,nationalPoliticalGroup
0,Mika AALTOLA,Finland,Group of the European People's Party (Christia...,256810,Kansallinen Kokoomus
1,Maravillas ABADÍA JOVER,Spain,Group of the European People's Party (Christia...,257043,Partido Popular
2,Magdalena ADAMOWICZ,Poland,Group of the European People's Party (Christia...,197490,Independent
3,Georgios AFTIAS,Greece,Group of the European People's Party (Christia...,256820,Nea Demokratia
4,Oihane AGIRREGOITIA MARTÍNEZ,Spain,Renew Europe Group,256987,Partido Nacionalista Vasco
...,...,...,...,...,...
714,Nicola ZINGARETTI,Italy,Group of the Progressive Alliance of Socialist...,28419,Partito Democratico
715,Kosma ZŁOTOWSKI,Poland,European Conservatives and Reformists Group,124884,Prawo i Sprawiedliwość
716,Juan Ignacio ZOIDO ÁLVAREZ,Spain,Group of the European People's Party (Christia...,197621,Partido Popular
717,Željana ZOVKO,Croatia,Group of the European People's Party (Christia...,185341,Hrvatska demokratska zajednica
718,Milan ZVER,Slovenia,Group of the European People's Party (Christia...,96933,Slovenska demokratska stranka